-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity msm_pippenger_control_Pipeline_PUT_INTO_BUCKETS_LOOP is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    x : IN STD_LOGIC_VECTOR (255 downto 0);
    y : IN STD_LOGIC_VECTOR (255 downto 0);
    z : IN STD_LOGIC_VECTOR (255 downto 0);
    t : IN STD_LOGIC_VECTOR (255 downto 0);
    scalar_partition_buffer_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    scalar_partition_buffer_ce0 : OUT STD_LOGIC;
    scalar_partition_buffer_q0 : IN STD_LOGIC_VECTOR (14 downto 0);
    scalar_partition_buffer_2_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    scalar_partition_buffer_2_ce0 : OUT STD_LOGIC;
    scalar_partition_buffer_2_q0 : IN STD_LOGIC_VECTOR (14 downto 0);
    buckets_x_address0 : OUT STD_LOGIC_VECTOR (13 downto 0);
    buckets_x_ce0 : OUT STD_LOGIC;
    buckets_x_we0 : OUT STD_LOGIC;
    buckets_x_d0 : OUT STD_LOGIC_VECTOR (255 downto 0);
    buckets_x_q0 : IN STD_LOGIC_VECTOR (255 downto 0);
    buckets_x_address1 : OUT STD_LOGIC_VECTOR (13 downto 0);
    buckets_x_ce1 : OUT STD_LOGIC;
    buckets_x_we1 : OUT STD_LOGIC;
    buckets_x_d1 : OUT STD_LOGIC_VECTOR (255 downto 0);
    buckets_x_1_address0 : OUT STD_LOGIC_VECTOR (13 downto 0);
    buckets_x_1_ce0 : OUT STD_LOGIC;
    buckets_x_1_we0 : OUT STD_LOGIC;
    buckets_x_1_d0 : OUT STD_LOGIC_VECTOR (255 downto 0);
    buckets_x_1_q0 : IN STD_LOGIC_VECTOR (255 downto 0);
    buckets_x_1_address1 : OUT STD_LOGIC_VECTOR (13 downto 0);
    buckets_x_1_ce1 : OUT STD_LOGIC;
    buckets_x_1_we1 : OUT STD_LOGIC;
    buckets_x_1_d1 : OUT STD_LOGIC_VECTOR (255 downto 0);
    buckets_y_address0 : OUT STD_LOGIC_VECTOR (13 downto 0);
    buckets_y_ce0 : OUT STD_LOGIC;
    buckets_y_we0 : OUT STD_LOGIC;
    buckets_y_d0 : OUT STD_LOGIC_VECTOR (255 downto 0);
    buckets_y_q0 : IN STD_LOGIC_VECTOR (255 downto 0);
    buckets_y_address1 : OUT STD_LOGIC_VECTOR (13 downto 0);
    buckets_y_ce1 : OUT STD_LOGIC;
    buckets_y_we1 : OUT STD_LOGIC;
    buckets_y_d1 : OUT STD_LOGIC_VECTOR (255 downto 0);
    buckets_y_1_address0 : OUT STD_LOGIC_VECTOR (13 downto 0);
    buckets_y_1_ce0 : OUT STD_LOGIC;
    buckets_y_1_we0 : OUT STD_LOGIC;
    buckets_y_1_d0 : OUT STD_LOGIC_VECTOR (255 downto 0);
    buckets_y_1_q0 : IN STD_LOGIC_VECTOR (255 downto 0);
    buckets_y_1_address1 : OUT STD_LOGIC_VECTOR (13 downto 0);
    buckets_y_1_ce1 : OUT STD_LOGIC;
    buckets_y_1_we1 : OUT STD_LOGIC;
    buckets_y_1_d1 : OUT STD_LOGIC_VECTOR (255 downto 0);
    buckets_z_address0 : OUT STD_LOGIC_VECTOR (13 downto 0);
    buckets_z_ce0 : OUT STD_LOGIC;
    buckets_z_we0 : OUT STD_LOGIC;
    buckets_z_d0 : OUT STD_LOGIC_VECTOR (255 downto 0);
    buckets_z_q0 : IN STD_LOGIC_VECTOR (255 downto 0);
    buckets_z_address1 : OUT STD_LOGIC_VECTOR (13 downto 0);
    buckets_z_ce1 : OUT STD_LOGIC;
    buckets_z_we1 : OUT STD_LOGIC;
    buckets_z_d1 : OUT STD_LOGIC_VECTOR (255 downto 0);
    buckets_z_1_address0 : OUT STD_LOGIC_VECTOR (13 downto 0);
    buckets_z_1_ce0 : OUT STD_LOGIC;
    buckets_z_1_we0 : OUT STD_LOGIC;
    buckets_z_1_d0 : OUT STD_LOGIC_VECTOR (255 downto 0);
    buckets_z_1_q0 : IN STD_LOGIC_VECTOR (255 downto 0);
    buckets_z_1_address1 : OUT STD_LOGIC_VECTOR (13 downto 0);
    buckets_z_1_ce1 : OUT STD_LOGIC;
    buckets_z_1_we1 : OUT STD_LOGIC;
    buckets_z_1_d1 : OUT STD_LOGIC_VECTOR (255 downto 0);
    buckets_t_address0 : OUT STD_LOGIC_VECTOR (13 downto 0);
    buckets_t_ce0 : OUT STD_LOGIC;
    buckets_t_we0 : OUT STD_LOGIC;
    buckets_t_d0 : OUT STD_LOGIC_VECTOR (255 downto 0);
    buckets_t_q0 : IN STD_LOGIC_VECTOR (255 downto 0);
    buckets_t_address1 : OUT STD_LOGIC_VECTOR (13 downto 0);
    buckets_t_ce1 : OUT STD_LOGIC;
    buckets_t_we1 : OUT STD_LOGIC;
    buckets_t_d1 : OUT STD_LOGIC_VECTOR (255 downto 0);
    buckets_t_1_address0 : OUT STD_LOGIC_VECTOR (13 downto 0);
    buckets_t_1_ce0 : OUT STD_LOGIC;
    buckets_t_1_we0 : OUT STD_LOGIC;
    buckets_t_1_d0 : OUT STD_LOGIC_VECTOR (255 downto 0);
    buckets_t_1_q0 : IN STD_LOGIC_VECTOR (255 downto 0);
    buckets_t_1_address1 : OUT STD_LOGIC_VECTOR (13 downto 0);
    buckets_t_1_ce1 : OUT STD_LOGIC;
    buckets_t_1_we1 : OUT STD_LOGIC;
    buckets_t_1_d1 : OUT STD_LOGIC_VECTOR (255 downto 0) );
end;


architecture behav of msm_pippenger_control_Pipeline_PUT_INTO_BUCKETS_LOOP is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv256_lc_8 : STD_LOGIC_VECTOR (255 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv256_lc_1 : STD_LOGIC_VECTOR (255 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv5_1A : STD_LOGIC_VECTOR (4 downto 0) := "11010";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter9 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter10 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter11 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter12 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter13 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter14 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter15 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal ap_enable_reg_pp0_iter0_reg : STD_LOGIC := '0';
    signal icmp_ln528_reg_491 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage1 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal j_1_reg_485 : STD_LOGIC_VECTOR (4 downto 0);
    signal icmp_ln528_fu_322_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln528_reg_491_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln528_reg_491_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln528_reg_491_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln531_fu_373_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln531_reg_505 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal trunc_ln531_reg_505_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln531_reg_505_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln531_reg_505_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln531_reg_505_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln531_reg_505_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln531_reg_505_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln531_reg_505_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln531_reg_505_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln531_reg_505_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln531_reg_505_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln531_reg_505_pp0_iter11_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln531_reg_505_pp0_iter12_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln531_reg_505_pp0_iter13_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln531_reg_505_pp0_iter14_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln532_fu_387_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal add_ln532_reg_513 : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_x_addr_reg_518 : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_x_addr_reg_518_pp0_iter2_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_x_addr_reg_518_pp0_iter3_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_x_addr_reg_518_pp0_iter4_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_x_addr_reg_518_pp0_iter5_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_x_addr_reg_518_pp0_iter6_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_x_addr_reg_518_pp0_iter7_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_x_addr_reg_518_pp0_iter8_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_x_addr_reg_518_pp0_iter9_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_x_addr_reg_518_pp0_iter10_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_x_addr_reg_518_pp0_iter11_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_x_addr_reg_518_pp0_iter12_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_x_addr_reg_518_pp0_iter13_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_x_addr_reg_518_pp0_iter14_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_x_addr_reg_518_pp0_iter15_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_x_1_addr_reg_524 : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_x_1_addr_reg_524_pp0_iter2_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_x_1_addr_reg_524_pp0_iter3_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_x_1_addr_reg_524_pp0_iter4_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_x_1_addr_reg_524_pp0_iter5_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_x_1_addr_reg_524_pp0_iter6_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_x_1_addr_reg_524_pp0_iter7_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_x_1_addr_reg_524_pp0_iter8_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_x_1_addr_reg_524_pp0_iter9_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_x_1_addr_reg_524_pp0_iter10_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_x_1_addr_reg_524_pp0_iter11_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_x_1_addr_reg_524_pp0_iter12_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_x_1_addr_reg_524_pp0_iter13_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_x_1_addr_reg_524_pp0_iter14_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_x_1_addr_reg_524_pp0_iter15_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_y_addr_reg_530 : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_y_addr_reg_530_pp0_iter2_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_y_addr_reg_530_pp0_iter3_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_y_addr_reg_530_pp0_iter4_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_y_addr_reg_530_pp0_iter5_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_y_addr_reg_530_pp0_iter6_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_y_addr_reg_530_pp0_iter7_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_y_addr_reg_530_pp0_iter8_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_y_addr_reg_530_pp0_iter9_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_y_addr_reg_530_pp0_iter10_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_y_addr_reg_530_pp0_iter11_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_y_addr_reg_530_pp0_iter12_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_y_addr_reg_530_pp0_iter13_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_y_addr_reg_530_pp0_iter14_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_y_addr_reg_530_pp0_iter15_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_y_1_addr_reg_536 : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_y_1_addr_reg_536_pp0_iter2_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_y_1_addr_reg_536_pp0_iter3_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_y_1_addr_reg_536_pp0_iter4_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_y_1_addr_reg_536_pp0_iter5_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_y_1_addr_reg_536_pp0_iter6_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_y_1_addr_reg_536_pp0_iter7_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_y_1_addr_reg_536_pp0_iter8_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_y_1_addr_reg_536_pp0_iter9_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_y_1_addr_reg_536_pp0_iter10_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_y_1_addr_reg_536_pp0_iter11_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_y_1_addr_reg_536_pp0_iter12_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_y_1_addr_reg_536_pp0_iter13_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_y_1_addr_reg_536_pp0_iter14_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_y_1_addr_reg_536_pp0_iter15_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_z_addr_reg_542 : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_z_addr_reg_542_pp0_iter2_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_z_addr_reg_542_pp0_iter3_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_z_addr_reg_542_pp0_iter4_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_z_addr_reg_542_pp0_iter5_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_z_addr_reg_542_pp0_iter6_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_z_addr_reg_542_pp0_iter7_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_z_addr_reg_542_pp0_iter8_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_z_addr_reg_542_pp0_iter9_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_z_addr_reg_542_pp0_iter10_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_z_addr_reg_542_pp0_iter11_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_z_addr_reg_542_pp0_iter12_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_z_addr_reg_542_pp0_iter13_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_z_addr_reg_542_pp0_iter14_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_z_addr_reg_542_pp0_iter15_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_z_1_addr_reg_548 : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_z_1_addr_reg_548_pp0_iter2_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_z_1_addr_reg_548_pp0_iter3_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_z_1_addr_reg_548_pp0_iter4_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_z_1_addr_reg_548_pp0_iter5_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_z_1_addr_reg_548_pp0_iter6_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_z_1_addr_reg_548_pp0_iter7_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_z_1_addr_reg_548_pp0_iter8_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_z_1_addr_reg_548_pp0_iter9_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_z_1_addr_reg_548_pp0_iter10_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_z_1_addr_reg_548_pp0_iter11_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_z_1_addr_reg_548_pp0_iter12_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_z_1_addr_reg_548_pp0_iter13_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_z_1_addr_reg_548_pp0_iter14_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_z_1_addr_reg_548_pp0_iter15_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_t_addr_reg_554 : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_t_addr_reg_554_pp0_iter2_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_t_addr_reg_554_pp0_iter3_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_t_addr_reg_554_pp0_iter4_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_t_addr_reg_554_pp0_iter5_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_t_addr_reg_554_pp0_iter6_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_t_addr_reg_554_pp0_iter7_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_t_addr_reg_554_pp0_iter8_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_t_addr_reg_554_pp0_iter9_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_t_addr_reg_554_pp0_iter10_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_t_addr_reg_554_pp0_iter11_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_t_addr_reg_554_pp0_iter12_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_t_addr_reg_554_pp0_iter13_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_t_addr_reg_554_pp0_iter14_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_t_addr_reg_554_pp0_iter15_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_t_1_addr_reg_560 : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_t_1_addr_reg_560_pp0_iter2_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_t_1_addr_reg_560_pp0_iter3_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_t_1_addr_reg_560_pp0_iter4_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_t_1_addr_reg_560_pp0_iter5_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_t_1_addr_reg_560_pp0_iter6_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_t_1_addr_reg_560_pp0_iter7_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_t_1_addr_reg_560_pp0_iter8_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_t_1_addr_reg_560_pp0_iter9_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_t_1_addr_reg_560_pp0_iter10_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_t_1_addr_reg_560_pp0_iter11_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_t_1_addr_reg_560_pp0_iter12_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_t_1_addr_reg_560_pp0_iter13_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_t_1_addr_reg_560_pp0_iter14_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_t_1_addr_reg_560_pp0_iter15_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal select_ln482_fu_404_p3 : STD_LOGIC_VECTOR (255 downto 0);
    signal select_ln482_reg_566 : STD_LOGIC_VECTOR (255 downto 0);
    signal select_ln482_1_fu_411_p3 : STD_LOGIC_VECTOR (255 downto 0);
    signal select_ln482_1_reg_572 : STD_LOGIC_VECTOR (255 downto 0);
    signal icmp_ln482_fu_422_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln482_reg_578 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln492_fu_428_p3 : STD_LOGIC_VECTOR (255 downto 0);
    signal select_ln492_reg_582 : STD_LOGIC_VECTOR (255 downto 0);
    signal select_ln492_1_fu_435_p3 : STD_LOGIC_VECTOR (255 downto 0);
    signal select_ln492_1_reg_587 : STD_LOGIC_VECTOR (255 downto 0);
    signal new_bucket_point_x_reg_592 : STD_LOGIC_VECTOR (255 downto 0);
    signal new_bucket_point_y_reg_598 : STD_LOGIC_VECTOR (255 downto 0);
    signal new_bucket_point_z_reg_604 : STD_LOGIC_VECTOR (255 downto 0);
    signal new_bucket_point_t_reg_610 : STD_LOGIC_VECTOR (255 downto 0);
    signal grp_edwards_point_add_fu_300_ap_return_0 : STD_LOGIC_VECTOR (255 downto 0);
    signal grp_edwards_point_add_fu_300_ap_return_1 : STD_LOGIC_VECTOR (255 downto 0);
    signal grp_edwards_point_add_fu_300_ap_return_2 : STD_LOGIC_VECTOR (255 downto 0);
    signal grp_edwards_point_add_fu_300_ap_return_3 : STD_LOGIC_VECTOR (255 downto 0);
    signal ap_phi_reg_pp0_iter0_p_0_0_043_i_i_i_reg_276 : STD_LOGIC_VECTOR (255 downto 0);
    signal ap_phi_reg_pp0_iter1_p_0_0_043_i_i_i_reg_276 : STD_LOGIC_VECTOR (255 downto 0);
    signal ap_phi_reg_pp0_iter2_p_0_0_043_i_i_i_reg_276 : STD_LOGIC_VECTOR (255 downto 0);
    signal ap_phi_reg_pp0_iter3_p_0_0_043_i_i_i_reg_276 : STD_LOGIC_VECTOR (255 downto 0);
    signal ap_phi_reg_pp0_iter4_p_0_0_043_i_i_i_reg_276 : STD_LOGIC_VECTOR (255 downto 0);
    signal ap_phi_reg_pp0_iter0_p_0_0_044_i_i_i_reg_288 : STD_LOGIC_VECTOR (255 downto 0);
    signal ap_phi_reg_pp0_iter1_p_0_0_044_i_i_i_reg_288 : STD_LOGIC_VECTOR (255 downto 0);
    signal ap_phi_reg_pp0_iter2_p_0_0_044_i_i_i_reg_288 : STD_LOGIC_VECTOR (255 downto 0);
    signal ap_phi_reg_pp0_iter3_p_0_0_044_i_i_i_reg_288 : STD_LOGIC_VECTOR (255 downto 0);
    signal ap_phi_reg_pp0_iter4_p_0_0_044_i_i_i_reg_288 : STD_LOGIC_VECTOR (255 downto 0);
    signal ap_block_pp0_stage0_ignoreCallOp122 : BOOLEAN;
    signal zext_ln528_fu_344_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln532_fu_393_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal j_fu_82 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    signal add_ln528_fu_328_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_j_1 : STD_LOGIC_VECTOR (4 downto 0);
    signal scalar_partition_buffer_ce0_local : STD_LOGIC;
    signal scalar_partition_buffer_2_ce0_local : STD_LOGIC;
    signal buckets_x_ce0_local : STD_LOGIC;
    signal buckets_x_address0_local : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_x_we1_local : STD_LOGIC;
    signal ap_block_pp0_stage1 : BOOLEAN;
    signal buckets_x_ce1_local : STD_LOGIC;
    signal buckets_x_we0_local : STD_LOGIC;
    signal buckets_x_1_ce0_local : STD_LOGIC;
    signal buckets_x_1_address0_local : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_x_1_we1_local : STD_LOGIC;
    signal buckets_x_1_ce1_local : STD_LOGIC;
    signal buckets_x_1_we0_local : STD_LOGIC;
    signal buckets_y_ce0_local : STD_LOGIC;
    signal buckets_y_address0_local : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_y_we1_local : STD_LOGIC;
    signal buckets_y_ce1_local : STD_LOGIC;
    signal buckets_y_we0_local : STD_LOGIC;
    signal buckets_y_1_ce0_local : STD_LOGIC;
    signal buckets_y_1_address0_local : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_y_1_we1_local : STD_LOGIC;
    signal buckets_y_1_ce1_local : STD_LOGIC;
    signal buckets_y_1_we0_local : STD_LOGIC;
    signal buckets_z_we1_local : STD_LOGIC;
    signal buckets_z_ce1_local : STD_LOGIC;
    signal buckets_z_ce0_local : STD_LOGIC;
    signal buckets_z_address0_local : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_z_we0_local : STD_LOGIC;
    signal buckets_t_we1_local : STD_LOGIC;
    signal buckets_t_ce1_local : STD_LOGIC;
    signal buckets_t_ce0_local : STD_LOGIC;
    signal buckets_t_address0_local : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_t_we0_local : STD_LOGIC;
    signal buckets_z_1_we1_local : STD_LOGIC;
    signal buckets_z_1_ce1_local : STD_LOGIC;
    signal buckets_z_1_ce0_local : STD_LOGIC;
    signal buckets_z_1_address0_local : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_z_1_we0_local : STD_LOGIC;
    signal buckets_t_1_we1_local : STD_LOGIC;
    signal buckets_t_1_ce1_local : STD_LOGIC;
    signal buckets_t_1_ce0_local : STD_LOGIC;
    signal buckets_t_1_address0_local : STD_LOGIC_VECTOR (13 downto 0);
    signal buckets_t_1_we0_local : STD_LOGIC;
    signal lshr_ln1_fu_334_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln528_fu_362_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal scalar_partition_fu_365_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_fu_355_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal lshr_ln2_fu_377_p4 : STD_LOGIC_VECTOR (13 downto 0);
    signal or_ln482_fu_418_p2 : STD_LOGIC_VECTOR (255 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter7_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter8_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter9_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter10_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter11_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter12_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter13_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter14_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_idle_pp0_1to15 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component msm_edwards_point_add IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        X1 : IN STD_LOGIC_VECTOR (255 downto 0);
        Y1 : IN STD_LOGIC_VECTOR (255 downto 0);
        Z1 : IN STD_LOGIC_VECTOR (255 downto 0);
        T1 : IN STD_LOGIC_VECTOR (255 downto 0);
        X2 : IN STD_LOGIC_VECTOR (255 downto 0);
        Y2 : IN STD_LOGIC_VECTOR (255 downto 0);
        Z2 : IN STD_LOGIC_VECTOR (255 downto 0);
        T2 : IN STD_LOGIC_VECTOR (255 downto 0);
        ap_return_0 : OUT STD_LOGIC_VECTOR (255 downto 0);
        ap_return_1 : OUT STD_LOGIC_VECTOR (255 downto 0);
        ap_return_2 : OUT STD_LOGIC_VECTOR (255 downto 0);
        ap_return_3 : OUT STD_LOGIC_VECTOR (255 downto 0) );
    end component;


    component msm_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    grp_edwards_point_add_fu_300 : component msm_edwards_point_add
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        X1 => ap_phi_reg_pp0_iter4_p_0_0_044_i_i_i_reg_288,
        Y1 => ap_phi_reg_pp0_iter4_p_0_0_043_i_i_i_reg_276,
        Z1 => select_ln492_reg_582,
        T1 => select_ln492_1_reg_587,
        X2 => x,
        Y2 => y,
        Z2 => z,
        T2 => t,
        ap_return_0 => grp_edwards_point_add_fu_300_ap_return_0,
        ap_return_1 => grp_edwards_point_add_fu_300_ap_return_1,
        ap_return_2 => grp_edwards_point_add_fu_300_ap_return_2,
        ap_return_3 => grp_edwards_point_add_fu_300_ap_return_3);

    flow_control_loop_pipe_sequential_init_U : component msm_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage1,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter14_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage1)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter10_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter10 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter11_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter11 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter12_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter12 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter13_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter13 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter14_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter14 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter15_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter15 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
                end if; 
            end if;
        end if;
    end process;


    ap_phi_reg_pp0_iter2_p_0_0_043_i_i_i_reg_276_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln482_fu_422_p2 = ap_const_lv1_0) and (icmp_ln528_reg_491_pp0_iter1_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                ap_phi_reg_pp0_iter2_p_0_0_043_i_i_i_reg_276 <= select_ln482_1_reg_572;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln482_fu_422_p2 = ap_const_lv1_1) and (icmp_ln528_reg_491_pp0_iter1_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                ap_phi_reg_pp0_iter2_p_0_0_043_i_i_i_reg_276 <= ap_const_lv256_lc_8;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                ap_phi_reg_pp0_iter2_p_0_0_043_i_i_i_reg_276 <= ap_phi_reg_pp0_iter1_p_0_0_043_i_i_i_reg_276;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter2_p_0_0_044_i_i_i_reg_288_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln482_fu_422_p2 = ap_const_lv1_0) and (icmp_ln528_reg_491_pp0_iter1_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                ap_phi_reg_pp0_iter2_p_0_0_044_i_i_i_reg_288 <= select_ln482_reg_566;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln482_fu_422_p2 = ap_const_lv1_1) and (icmp_ln528_reg_491_pp0_iter1_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                ap_phi_reg_pp0_iter2_p_0_0_044_i_i_i_reg_288 <= ap_const_lv256_lc_1;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                ap_phi_reg_pp0_iter2_p_0_0_044_i_i_i_reg_288 <= ap_phi_reg_pp0_iter1_p_0_0_044_i_i_i_reg_288;
            end if; 
        end if;
    end process;

    j_fu_82_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln528_fu_322_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    j_fu_82 <= add_ln528_fu_328_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    j_fu_82 <= ap_const_lv5_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                add_ln532_reg_513 <= add_ln532_fu_387_p2;
                ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
                ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
                ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
                ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
                ap_loop_exit_ready_pp0_iter14_reg <= ap_loop_exit_ready_pp0_iter13_reg;
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
                ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
                ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
                select_ln482_1_reg_572 <= select_ln482_1_fu_411_p3;
                select_ln482_reg_566 <= select_ln482_fu_404_p3;
                select_ln492_1_reg_587 <= select_ln492_1_fu_435_p3;
                select_ln492_reg_582 <= select_ln492_fu_428_p3;
                trunc_ln531_reg_505 <= trunc_ln531_fu_373_p1;
                trunc_ln531_reg_505_pp0_iter10_reg <= trunc_ln531_reg_505_pp0_iter9_reg;
                trunc_ln531_reg_505_pp0_iter11_reg <= trunc_ln531_reg_505_pp0_iter10_reg;
                trunc_ln531_reg_505_pp0_iter12_reg <= trunc_ln531_reg_505_pp0_iter11_reg;
                trunc_ln531_reg_505_pp0_iter13_reg <= trunc_ln531_reg_505_pp0_iter12_reg;
                trunc_ln531_reg_505_pp0_iter14_reg <= trunc_ln531_reg_505_pp0_iter13_reg;
                trunc_ln531_reg_505_pp0_iter1_reg <= trunc_ln531_reg_505;
                trunc_ln531_reg_505_pp0_iter2_reg <= trunc_ln531_reg_505_pp0_iter1_reg;
                trunc_ln531_reg_505_pp0_iter3_reg <= trunc_ln531_reg_505_pp0_iter2_reg;
                trunc_ln531_reg_505_pp0_iter4_reg <= trunc_ln531_reg_505_pp0_iter3_reg;
                trunc_ln531_reg_505_pp0_iter5_reg <= trunc_ln531_reg_505_pp0_iter4_reg;
                trunc_ln531_reg_505_pp0_iter6_reg <= trunc_ln531_reg_505_pp0_iter5_reg;
                trunc_ln531_reg_505_pp0_iter7_reg <= trunc_ln531_reg_505_pp0_iter6_reg;
                trunc_ln531_reg_505_pp0_iter8_reg <= trunc_ln531_reg_505_pp0_iter7_reg;
                trunc_ln531_reg_505_pp0_iter9_reg <= trunc_ln531_reg_505_pp0_iter8_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                ap_phi_reg_pp0_iter1_p_0_0_043_i_i_i_reg_276 <= ap_phi_reg_pp0_iter0_p_0_0_043_i_i_i_reg_276;
                ap_phi_reg_pp0_iter1_p_0_0_044_i_i_i_reg_288 <= ap_phi_reg_pp0_iter0_p_0_0_044_i_i_i_reg_288;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                ap_phi_reg_pp0_iter3_p_0_0_043_i_i_i_reg_276 <= ap_phi_reg_pp0_iter2_p_0_0_043_i_i_i_reg_276;
                ap_phi_reg_pp0_iter3_p_0_0_044_i_i_i_reg_288 <= ap_phi_reg_pp0_iter2_p_0_0_044_i_i_i_reg_288;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                ap_phi_reg_pp0_iter4_p_0_0_043_i_i_i_reg_276 <= ap_phi_reg_pp0_iter3_p_0_0_043_i_i_i_reg_276;
                ap_phi_reg_pp0_iter4_p_0_0_044_i_i_i_reg_288 <= ap_phi_reg_pp0_iter3_p_0_0_044_i_i_i_reg_288;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                buckets_t_1_addr_reg_560 <= zext_ln532_fu_393_p1(14 - 1 downto 0);
                buckets_t_1_addr_reg_560_pp0_iter10_reg <= buckets_t_1_addr_reg_560_pp0_iter9_reg;
                buckets_t_1_addr_reg_560_pp0_iter11_reg <= buckets_t_1_addr_reg_560_pp0_iter10_reg;
                buckets_t_1_addr_reg_560_pp0_iter12_reg <= buckets_t_1_addr_reg_560_pp0_iter11_reg;
                buckets_t_1_addr_reg_560_pp0_iter13_reg <= buckets_t_1_addr_reg_560_pp0_iter12_reg;
                buckets_t_1_addr_reg_560_pp0_iter14_reg <= buckets_t_1_addr_reg_560_pp0_iter13_reg;
                buckets_t_1_addr_reg_560_pp0_iter15_reg <= buckets_t_1_addr_reg_560_pp0_iter14_reg;
                buckets_t_1_addr_reg_560_pp0_iter2_reg <= buckets_t_1_addr_reg_560;
                buckets_t_1_addr_reg_560_pp0_iter3_reg <= buckets_t_1_addr_reg_560_pp0_iter2_reg;
                buckets_t_1_addr_reg_560_pp0_iter4_reg <= buckets_t_1_addr_reg_560_pp0_iter3_reg;
                buckets_t_1_addr_reg_560_pp0_iter5_reg <= buckets_t_1_addr_reg_560_pp0_iter4_reg;
                buckets_t_1_addr_reg_560_pp0_iter6_reg <= buckets_t_1_addr_reg_560_pp0_iter5_reg;
                buckets_t_1_addr_reg_560_pp0_iter7_reg <= buckets_t_1_addr_reg_560_pp0_iter6_reg;
                buckets_t_1_addr_reg_560_pp0_iter8_reg <= buckets_t_1_addr_reg_560_pp0_iter7_reg;
                buckets_t_1_addr_reg_560_pp0_iter9_reg <= buckets_t_1_addr_reg_560_pp0_iter8_reg;
                buckets_t_addr_reg_554 <= zext_ln532_fu_393_p1(14 - 1 downto 0);
                buckets_t_addr_reg_554_pp0_iter10_reg <= buckets_t_addr_reg_554_pp0_iter9_reg;
                buckets_t_addr_reg_554_pp0_iter11_reg <= buckets_t_addr_reg_554_pp0_iter10_reg;
                buckets_t_addr_reg_554_pp0_iter12_reg <= buckets_t_addr_reg_554_pp0_iter11_reg;
                buckets_t_addr_reg_554_pp0_iter13_reg <= buckets_t_addr_reg_554_pp0_iter12_reg;
                buckets_t_addr_reg_554_pp0_iter14_reg <= buckets_t_addr_reg_554_pp0_iter13_reg;
                buckets_t_addr_reg_554_pp0_iter15_reg <= buckets_t_addr_reg_554_pp0_iter14_reg;
                buckets_t_addr_reg_554_pp0_iter2_reg <= buckets_t_addr_reg_554;
                buckets_t_addr_reg_554_pp0_iter3_reg <= buckets_t_addr_reg_554_pp0_iter2_reg;
                buckets_t_addr_reg_554_pp0_iter4_reg <= buckets_t_addr_reg_554_pp0_iter3_reg;
                buckets_t_addr_reg_554_pp0_iter5_reg <= buckets_t_addr_reg_554_pp0_iter4_reg;
                buckets_t_addr_reg_554_pp0_iter6_reg <= buckets_t_addr_reg_554_pp0_iter5_reg;
                buckets_t_addr_reg_554_pp0_iter7_reg <= buckets_t_addr_reg_554_pp0_iter6_reg;
                buckets_t_addr_reg_554_pp0_iter8_reg <= buckets_t_addr_reg_554_pp0_iter7_reg;
                buckets_t_addr_reg_554_pp0_iter9_reg <= buckets_t_addr_reg_554_pp0_iter8_reg;
                buckets_x_1_addr_reg_524 <= zext_ln532_fu_393_p1(14 - 1 downto 0);
                buckets_x_1_addr_reg_524_pp0_iter10_reg <= buckets_x_1_addr_reg_524_pp0_iter9_reg;
                buckets_x_1_addr_reg_524_pp0_iter11_reg <= buckets_x_1_addr_reg_524_pp0_iter10_reg;
                buckets_x_1_addr_reg_524_pp0_iter12_reg <= buckets_x_1_addr_reg_524_pp0_iter11_reg;
                buckets_x_1_addr_reg_524_pp0_iter13_reg <= buckets_x_1_addr_reg_524_pp0_iter12_reg;
                buckets_x_1_addr_reg_524_pp0_iter14_reg <= buckets_x_1_addr_reg_524_pp0_iter13_reg;
                buckets_x_1_addr_reg_524_pp0_iter15_reg <= buckets_x_1_addr_reg_524_pp0_iter14_reg;
                buckets_x_1_addr_reg_524_pp0_iter2_reg <= buckets_x_1_addr_reg_524;
                buckets_x_1_addr_reg_524_pp0_iter3_reg <= buckets_x_1_addr_reg_524_pp0_iter2_reg;
                buckets_x_1_addr_reg_524_pp0_iter4_reg <= buckets_x_1_addr_reg_524_pp0_iter3_reg;
                buckets_x_1_addr_reg_524_pp0_iter5_reg <= buckets_x_1_addr_reg_524_pp0_iter4_reg;
                buckets_x_1_addr_reg_524_pp0_iter6_reg <= buckets_x_1_addr_reg_524_pp0_iter5_reg;
                buckets_x_1_addr_reg_524_pp0_iter7_reg <= buckets_x_1_addr_reg_524_pp0_iter6_reg;
                buckets_x_1_addr_reg_524_pp0_iter8_reg <= buckets_x_1_addr_reg_524_pp0_iter7_reg;
                buckets_x_1_addr_reg_524_pp0_iter9_reg <= buckets_x_1_addr_reg_524_pp0_iter8_reg;
                buckets_x_addr_reg_518 <= zext_ln532_fu_393_p1(14 - 1 downto 0);
                buckets_x_addr_reg_518_pp0_iter10_reg <= buckets_x_addr_reg_518_pp0_iter9_reg;
                buckets_x_addr_reg_518_pp0_iter11_reg <= buckets_x_addr_reg_518_pp0_iter10_reg;
                buckets_x_addr_reg_518_pp0_iter12_reg <= buckets_x_addr_reg_518_pp0_iter11_reg;
                buckets_x_addr_reg_518_pp0_iter13_reg <= buckets_x_addr_reg_518_pp0_iter12_reg;
                buckets_x_addr_reg_518_pp0_iter14_reg <= buckets_x_addr_reg_518_pp0_iter13_reg;
                buckets_x_addr_reg_518_pp0_iter15_reg <= buckets_x_addr_reg_518_pp0_iter14_reg;
                buckets_x_addr_reg_518_pp0_iter2_reg <= buckets_x_addr_reg_518;
                buckets_x_addr_reg_518_pp0_iter3_reg <= buckets_x_addr_reg_518_pp0_iter2_reg;
                buckets_x_addr_reg_518_pp0_iter4_reg <= buckets_x_addr_reg_518_pp0_iter3_reg;
                buckets_x_addr_reg_518_pp0_iter5_reg <= buckets_x_addr_reg_518_pp0_iter4_reg;
                buckets_x_addr_reg_518_pp0_iter6_reg <= buckets_x_addr_reg_518_pp0_iter5_reg;
                buckets_x_addr_reg_518_pp0_iter7_reg <= buckets_x_addr_reg_518_pp0_iter6_reg;
                buckets_x_addr_reg_518_pp0_iter8_reg <= buckets_x_addr_reg_518_pp0_iter7_reg;
                buckets_x_addr_reg_518_pp0_iter9_reg <= buckets_x_addr_reg_518_pp0_iter8_reg;
                buckets_y_1_addr_reg_536 <= zext_ln532_fu_393_p1(14 - 1 downto 0);
                buckets_y_1_addr_reg_536_pp0_iter10_reg <= buckets_y_1_addr_reg_536_pp0_iter9_reg;
                buckets_y_1_addr_reg_536_pp0_iter11_reg <= buckets_y_1_addr_reg_536_pp0_iter10_reg;
                buckets_y_1_addr_reg_536_pp0_iter12_reg <= buckets_y_1_addr_reg_536_pp0_iter11_reg;
                buckets_y_1_addr_reg_536_pp0_iter13_reg <= buckets_y_1_addr_reg_536_pp0_iter12_reg;
                buckets_y_1_addr_reg_536_pp0_iter14_reg <= buckets_y_1_addr_reg_536_pp0_iter13_reg;
                buckets_y_1_addr_reg_536_pp0_iter15_reg <= buckets_y_1_addr_reg_536_pp0_iter14_reg;
                buckets_y_1_addr_reg_536_pp0_iter2_reg <= buckets_y_1_addr_reg_536;
                buckets_y_1_addr_reg_536_pp0_iter3_reg <= buckets_y_1_addr_reg_536_pp0_iter2_reg;
                buckets_y_1_addr_reg_536_pp0_iter4_reg <= buckets_y_1_addr_reg_536_pp0_iter3_reg;
                buckets_y_1_addr_reg_536_pp0_iter5_reg <= buckets_y_1_addr_reg_536_pp0_iter4_reg;
                buckets_y_1_addr_reg_536_pp0_iter6_reg <= buckets_y_1_addr_reg_536_pp0_iter5_reg;
                buckets_y_1_addr_reg_536_pp0_iter7_reg <= buckets_y_1_addr_reg_536_pp0_iter6_reg;
                buckets_y_1_addr_reg_536_pp0_iter8_reg <= buckets_y_1_addr_reg_536_pp0_iter7_reg;
                buckets_y_1_addr_reg_536_pp0_iter9_reg <= buckets_y_1_addr_reg_536_pp0_iter8_reg;
                buckets_y_addr_reg_530 <= zext_ln532_fu_393_p1(14 - 1 downto 0);
                buckets_y_addr_reg_530_pp0_iter10_reg <= buckets_y_addr_reg_530_pp0_iter9_reg;
                buckets_y_addr_reg_530_pp0_iter11_reg <= buckets_y_addr_reg_530_pp0_iter10_reg;
                buckets_y_addr_reg_530_pp0_iter12_reg <= buckets_y_addr_reg_530_pp0_iter11_reg;
                buckets_y_addr_reg_530_pp0_iter13_reg <= buckets_y_addr_reg_530_pp0_iter12_reg;
                buckets_y_addr_reg_530_pp0_iter14_reg <= buckets_y_addr_reg_530_pp0_iter13_reg;
                buckets_y_addr_reg_530_pp0_iter15_reg <= buckets_y_addr_reg_530_pp0_iter14_reg;
                buckets_y_addr_reg_530_pp0_iter2_reg <= buckets_y_addr_reg_530;
                buckets_y_addr_reg_530_pp0_iter3_reg <= buckets_y_addr_reg_530_pp0_iter2_reg;
                buckets_y_addr_reg_530_pp0_iter4_reg <= buckets_y_addr_reg_530_pp0_iter3_reg;
                buckets_y_addr_reg_530_pp0_iter5_reg <= buckets_y_addr_reg_530_pp0_iter4_reg;
                buckets_y_addr_reg_530_pp0_iter6_reg <= buckets_y_addr_reg_530_pp0_iter5_reg;
                buckets_y_addr_reg_530_pp0_iter7_reg <= buckets_y_addr_reg_530_pp0_iter6_reg;
                buckets_y_addr_reg_530_pp0_iter8_reg <= buckets_y_addr_reg_530_pp0_iter7_reg;
                buckets_y_addr_reg_530_pp0_iter9_reg <= buckets_y_addr_reg_530_pp0_iter8_reg;
                buckets_z_1_addr_reg_548 <= zext_ln532_fu_393_p1(14 - 1 downto 0);
                buckets_z_1_addr_reg_548_pp0_iter10_reg <= buckets_z_1_addr_reg_548_pp0_iter9_reg;
                buckets_z_1_addr_reg_548_pp0_iter11_reg <= buckets_z_1_addr_reg_548_pp0_iter10_reg;
                buckets_z_1_addr_reg_548_pp0_iter12_reg <= buckets_z_1_addr_reg_548_pp0_iter11_reg;
                buckets_z_1_addr_reg_548_pp0_iter13_reg <= buckets_z_1_addr_reg_548_pp0_iter12_reg;
                buckets_z_1_addr_reg_548_pp0_iter14_reg <= buckets_z_1_addr_reg_548_pp0_iter13_reg;
                buckets_z_1_addr_reg_548_pp0_iter15_reg <= buckets_z_1_addr_reg_548_pp0_iter14_reg;
                buckets_z_1_addr_reg_548_pp0_iter2_reg <= buckets_z_1_addr_reg_548;
                buckets_z_1_addr_reg_548_pp0_iter3_reg <= buckets_z_1_addr_reg_548_pp0_iter2_reg;
                buckets_z_1_addr_reg_548_pp0_iter4_reg <= buckets_z_1_addr_reg_548_pp0_iter3_reg;
                buckets_z_1_addr_reg_548_pp0_iter5_reg <= buckets_z_1_addr_reg_548_pp0_iter4_reg;
                buckets_z_1_addr_reg_548_pp0_iter6_reg <= buckets_z_1_addr_reg_548_pp0_iter5_reg;
                buckets_z_1_addr_reg_548_pp0_iter7_reg <= buckets_z_1_addr_reg_548_pp0_iter6_reg;
                buckets_z_1_addr_reg_548_pp0_iter8_reg <= buckets_z_1_addr_reg_548_pp0_iter7_reg;
                buckets_z_1_addr_reg_548_pp0_iter9_reg <= buckets_z_1_addr_reg_548_pp0_iter8_reg;
                buckets_z_addr_reg_542 <= zext_ln532_fu_393_p1(14 - 1 downto 0);
                buckets_z_addr_reg_542_pp0_iter10_reg <= buckets_z_addr_reg_542_pp0_iter9_reg;
                buckets_z_addr_reg_542_pp0_iter11_reg <= buckets_z_addr_reg_542_pp0_iter10_reg;
                buckets_z_addr_reg_542_pp0_iter12_reg <= buckets_z_addr_reg_542_pp0_iter11_reg;
                buckets_z_addr_reg_542_pp0_iter13_reg <= buckets_z_addr_reg_542_pp0_iter12_reg;
                buckets_z_addr_reg_542_pp0_iter14_reg <= buckets_z_addr_reg_542_pp0_iter13_reg;
                buckets_z_addr_reg_542_pp0_iter15_reg <= buckets_z_addr_reg_542_pp0_iter14_reg;
                buckets_z_addr_reg_542_pp0_iter2_reg <= buckets_z_addr_reg_542;
                buckets_z_addr_reg_542_pp0_iter3_reg <= buckets_z_addr_reg_542_pp0_iter2_reg;
                buckets_z_addr_reg_542_pp0_iter4_reg <= buckets_z_addr_reg_542_pp0_iter3_reg;
                buckets_z_addr_reg_542_pp0_iter5_reg <= buckets_z_addr_reg_542_pp0_iter4_reg;
                buckets_z_addr_reg_542_pp0_iter6_reg <= buckets_z_addr_reg_542_pp0_iter5_reg;
                buckets_z_addr_reg_542_pp0_iter7_reg <= buckets_z_addr_reg_542_pp0_iter6_reg;
                buckets_z_addr_reg_542_pp0_iter8_reg <= buckets_z_addr_reg_542_pp0_iter7_reg;
                buckets_z_addr_reg_542_pp0_iter9_reg <= buckets_z_addr_reg_542_pp0_iter8_reg;
                icmp_ln482_reg_578 <= icmp_ln482_fu_422_p2;
                icmp_ln528_reg_491 <= icmp_ln528_fu_322_p2;
                icmp_ln528_reg_491_pp0_iter1_reg <= icmp_ln528_reg_491;
                icmp_ln528_reg_491_pp0_iter2_reg <= icmp_ln528_reg_491_pp0_iter1_reg;
                icmp_ln528_reg_491_pp0_iter3_reg <= icmp_ln528_reg_491_pp0_iter2_reg;
                j_1_reg_485 <= ap_sig_allocacmp_j_1;
                new_bucket_point_t_reg_610 <= grp_edwards_point_add_fu_300_ap_return_3;
                new_bucket_point_x_reg_592 <= grp_edwards_point_add_fu_300_ap_return_0;
                new_bucket_point_y_reg_598 <= grp_edwards_point_add_fu_300_ap_return_1;
                new_bucket_point_z_reg_604 <= grp_edwards_point_add_fu_300_ap_return_2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage1_subdone, ap_block_pp0_stage0_subdone, ap_idle_pp0_1to15, ap_start_int)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((ap_start_int = ap_const_logic_0) and (ap_idle_pp0_1to15 = ap_const_logic_1))) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    add_ln528_fu_328_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_j_1) + unsigned(ap_const_lv5_1));
    add_ln532_fu_387_p2 <= std_logic_vector(unsigned(tmp_fu_355_p3) + unsigned(lshr_ln2_fu_377_p4));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(1);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_ignoreCallOp122 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage1_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone, ap_enable_reg_pp0_iter0_reg, icmp_ln528_reg_491)
    begin
        if (((icmp_ln528_reg_491 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_condition_exit_pp0_iter0_stage1 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage1 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter14_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter14_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_enable_reg_pp0_iter0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0_reg, ap_start_int)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
            ap_enable_reg_pp0_iter0 <= ap_start_int;
        else 
            ap_enable_reg_pp0_iter0 <= ap_enable_reg_pp0_iter0_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10, ap_enable_reg_pp0_iter11, ap_enable_reg_pp0_iter12, ap_enable_reg_pp0_iter13, ap_enable_reg_pp0_iter14, ap_enable_reg_pp0_iter15)
    begin
        if (((ap_enable_reg_pp0_iter15 = ap_const_logic_0) and (ap_enable_reg_pp0_iter14 = ap_const_logic_0) and (ap_enable_reg_pp0_iter13 = ap_const_logic_0) and (ap_enable_reg_pp0_iter12 = ap_const_logic_0) and (ap_enable_reg_pp0_iter11 = ap_const_logic_0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_1to15_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10, ap_enable_reg_pp0_iter11, ap_enable_reg_pp0_iter12, ap_enable_reg_pp0_iter13, ap_enable_reg_pp0_iter14, ap_enable_reg_pp0_iter15)
    begin
        if (((ap_enable_reg_pp0_iter15 = ap_const_logic_0) and (ap_enable_reg_pp0_iter14 = ap_const_logic_0) and (ap_enable_reg_pp0_iter13 = ap_const_logic_0) and (ap_enable_reg_pp0_iter12 = ap_const_logic_0) and (ap_enable_reg_pp0_iter11 = ap_const_logic_0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) then 
            ap_idle_pp0_1to15 <= ap_const_logic_1;
        else 
            ap_idle_pp0_1to15 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage1;
    ap_phi_reg_pp0_iter0_p_0_0_043_i_i_i_reg_276 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter0_p_0_0_044_i_i_i_reg_288 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone, ap_enable_reg_pp0_iter0_reg)
    begin
        if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_j_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, j_fu_82, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_j_1 <= ap_const_lv5_0;
        else 
            ap_sig_allocacmp_j_1 <= j_fu_82;
        end if; 
    end process;

    buckets_t_1_address0 <= buckets_t_1_address0_local;

    buckets_t_1_address0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter15, ap_CS_fsm_pp0_stage1, buckets_t_1_addr_reg_560_pp0_iter2_reg, buckets_t_1_addr_reg_560_pp0_iter15_reg, ap_block_pp0_stage0, ap_block_pp0_stage1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter15 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            buckets_t_1_address0_local <= buckets_t_1_addr_reg_560_pp0_iter15_reg;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            buckets_t_1_address0_local <= buckets_t_1_addr_reg_560_pp0_iter2_reg;
        else 
            buckets_t_1_address0_local <= "XXXXXXXXXXXXXX";
        end if; 
    end process;

    buckets_t_1_address1 <= buckets_t_1_addr_reg_560_pp0_iter2_reg;
    buckets_t_1_ce0 <= buckets_t_1_ce0_local;

    buckets_t_1_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter15, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter15 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            buckets_t_1_ce0_local <= ap_const_logic_1;
        else 
            buckets_t_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    buckets_t_1_ce1 <= buckets_t_1_ce1_local;

    buckets_t_1_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            buckets_t_1_ce1_local <= ap_const_logic_1;
        else 
            buckets_t_1_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    buckets_t_1_d0 <= new_bucket_point_t_reg_610;
    buckets_t_1_d1 <= ap_const_lv256_lc_1;
    buckets_t_1_we0 <= buckets_t_1_we0_local;

    buckets_t_1_we0_local_assign_proc : process(ap_enable_reg_pp0_iter15, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, trunc_ln531_reg_505_pp0_iter14_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter15 = ap_const_logic_1) and (trunc_ln531_reg_505_pp0_iter14_reg = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            buckets_t_1_we0_local <= ap_const_logic_1;
        else 
            buckets_t_1_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    buckets_t_1_we1 <= buckets_t_1_we1_local;

    buckets_t_1_we1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, trunc_ln531_reg_505_pp0_iter1_reg, icmp_ln482_reg_578)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (icmp_ln482_reg_578 = ap_const_lv1_1) and (trunc_ln531_reg_505_pp0_iter1_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            buckets_t_1_we1_local <= ap_const_logic_1;
        else 
            buckets_t_1_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    buckets_t_address0 <= buckets_t_address0_local;

    buckets_t_address0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter15, ap_CS_fsm_pp0_stage1, buckets_t_addr_reg_554_pp0_iter2_reg, buckets_t_addr_reg_554_pp0_iter15_reg, ap_block_pp0_stage0, ap_block_pp0_stage1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter15 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            buckets_t_address0_local <= buckets_t_addr_reg_554_pp0_iter15_reg;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            buckets_t_address0_local <= buckets_t_addr_reg_554_pp0_iter2_reg;
        else 
            buckets_t_address0_local <= "XXXXXXXXXXXXXX";
        end if; 
    end process;

    buckets_t_address1 <= buckets_t_addr_reg_554_pp0_iter2_reg;
    buckets_t_ce0 <= buckets_t_ce0_local;

    buckets_t_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter15, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter15 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            buckets_t_ce0_local <= ap_const_logic_1;
        else 
            buckets_t_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    buckets_t_ce1 <= buckets_t_ce1_local;

    buckets_t_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            buckets_t_ce1_local <= ap_const_logic_1;
        else 
            buckets_t_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    buckets_t_d0 <= new_bucket_point_t_reg_610;
    buckets_t_d1 <= ap_const_lv256_lc_1;
    buckets_t_we0 <= buckets_t_we0_local;

    buckets_t_we0_local_assign_proc : process(ap_enable_reg_pp0_iter15, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, trunc_ln531_reg_505_pp0_iter14_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter15 = ap_const_logic_1) and (trunc_ln531_reg_505_pp0_iter14_reg = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            buckets_t_we0_local <= ap_const_logic_1;
        else 
            buckets_t_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    buckets_t_we1 <= buckets_t_we1_local;

    buckets_t_we1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, trunc_ln531_reg_505_pp0_iter1_reg, icmp_ln482_reg_578)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (icmp_ln482_reg_578 = ap_const_lv1_1) and (trunc_ln531_reg_505_pp0_iter1_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            buckets_t_we1_local <= ap_const_logic_1;
        else 
            buckets_t_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    buckets_x_1_address0 <= buckets_x_1_address0_local;

    buckets_x_1_address0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter15, ap_CS_fsm_pp0_stage1, buckets_x_1_addr_reg_524_pp0_iter15_reg, ap_block_pp0_stage0, zext_ln532_fu_393_p1, ap_block_pp0_stage1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter15 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            buckets_x_1_address0_local <= buckets_x_1_addr_reg_524_pp0_iter15_reg;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            buckets_x_1_address0_local <= zext_ln532_fu_393_p1(14 - 1 downto 0);
        else 
            buckets_x_1_address0_local <= "XXXXXXXXXXXXXX";
        end if; 
    end process;

    buckets_x_1_address1 <= buckets_x_1_addr_reg_524_pp0_iter2_reg;
    buckets_x_1_ce0 <= buckets_x_1_ce0_local;

    buckets_x_1_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter15, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter15 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            buckets_x_1_ce0_local <= ap_const_logic_1;
        else 
            buckets_x_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    buckets_x_1_ce1 <= buckets_x_1_ce1_local;

    buckets_x_1_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            buckets_x_1_ce1_local <= ap_const_logic_1;
        else 
            buckets_x_1_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    buckets_x_1_d0 <= new_bucket_point_x_reg_592;
    buckets_x_1_d1 <= ap_const_lv256_lc_1;
    buckets_x_1_we0 <= buckets_x_1_we0_local;

    buckets_x_1_we0_local_assign_proc : process(ap_enable_reg_pp0_iter15, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, trunc_ln531_reg_505_pp0_iter14_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter15 = ap_const_logic_1) and (trunc_ln531_reg_505_pp0_iter14_reg = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            buckets_x_1_we0_local <= ap_const_logic_1;
        else 
            buckets_x_1_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    buckets_x_1_we1 <= buckets_x_1_we1_local;

    buckets_x_1_we1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, trunc_ln531_reg_505_pp0_iter1_reg, icmp_ln482_reg_578)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (icmp_ln482_reg_578 = ap_const_lv1_1) and (trunc_ln531_reg_505_pp0_iter1_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            buckets_x_1_we1_local <= ap_const_logic_1;
        else 
            buckets_x_1_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    buckets_x_address0 <= buckets_x_address0_local;

    buckets_x_address0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter15, ap_CS_fsm_pp0_stage1, buckets_x_addr_reg_518_pp0_iter15_reg, ap_block_pp0_stage0, zext_ln532_fu_393_p1, ap_block_pp0_stage1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter15 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            buckets_x_address0_local <= buckets_x_addr_reg_518_pp0_iter15_reg;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            buckets_x_address0_local <= zext_ln532_fu_393_p1(14 - 1 downto 0);
        else 
            buckets_x_address0_local <= "XXXXXXXXXXXXXX";
        end if; 
    end process;

    buckets_x_address1 <= buckets_x_addr_reg_518_pp0_iter2_reg;
    buckets_x_ce0 <= buckets_x_ce0_local;

    buckets_x_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter15, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter15 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            buckets_x_ce0_local <= ap_const_logic_1;
        else 
            buckets_x_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    buckets_x_ce1 <= buckets_x_ce1_local;

    buckets_x_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            buckets_x_ce1_local <= ap_const_logic_1;
        else 
            buckets_x_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    buckets_x_d0 <= new_bucket_point_x_reg_592;
    buckets_x_d1 <= ap_const_lv256_lc_1;
    buckets_x_we0 <= buckets_x_we0_local;

    buckets_x_we0_local_assign_proc : process(ap_enable_reg_pp0_iter15, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, trunc_ln531_reg_505_pp0_iter14_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter15 = ap_const_logic_1) and (trunc_ln531_reg_505_pp0_iter14_reg = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            buckets_x_we0_local <= ap_const_logic_1;
        else 
            buckets_x_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    buckets_x_we1 <= buckets_x_we1_local;

    buckets_x_we1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, trunc_ln531_reg_505_pp0_iter1_reg, icmp_ln482_reg_578)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (icmp_ln482_reg_578 = ap_const_lv1_1) and (trunc_ln531_reg_505_pp0_iter1_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            buckets_x_we1_local <= ap_const_logic_1;
        else 
            buckets_x_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    buckets_y_1_address0 <= buckets_y_1_address0_local;

    buckets_y_1_address0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter15, ap_CS_fsm_pp0_stage1, buckets_y_1_addr_reg_536_pp0_iter15_reg, ap_block_pp0_stage0, zext_ln532_fu_393_p1, ap_block_pp0_stage1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter15 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            buckets_y_1_address0_local <= buckets_y_1_addr_reg_536_pp0_iter15_reg;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            buckets_y_1_address0_local <= zext_ln532_fu_393_p1(14 - 1 downto 0);
        else 
            buckets_y_1_address0_local <= "XXXXXXXXXXXXXX";
        end if; 
    end process;

    buckets_y_1_address1 <= buckets_y_1_addr_reg_536_pp0_iter2_reg;
    buckets_y_1_ce0 <= buckets_y_1_ce0_local;

    buckets_y_1_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter15, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter15 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            buckets_y_1_ce0_local <= ap_const_logic_1;
        else 
            buckets_y_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    buckets_y_1_ce1 <= buckets_y_1_ce1_local;

    buckets_y_1_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            buckets_y_1_ce1_local <= ap_const_logic_1;
        else 
            buckets_y_1_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    buckets_y_1_d0 <= new_bucket_point_y_reg_598;
    buckets_y_1_d1 <= ap_const_lv256_lc_8;
    buckets_y_1_we0 <= buckets_y_1_we0_local;

    buckets_y_1_we0_local_assign_proc : process(ap_enable_reg_pp0_iter15, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, trunc_ln531_reg_505_pp0_iter14_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter15 = ap_const_logic_1) and (trunc_ln531_reg_505_pp0_iter14_reg = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            buckets_y_1_we0_local <= ap_const_logic_1;
        else 
            buckets_y_1_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    buckets_y_1_we1 <= buckets_y_1_we1_local;

    buckets_y_1_we1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, trunc_ln531_reg_505_pp0_iter1_reg, icmp_ln482_reg_578)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (icmp_ln482_reg_578 = ap_const_lv1_1) and (trunc_ln531_reg_505_pp0_iter1_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            buckets_y_1_we1_local <= ap_const_logic_1;
        else 
            buckets_y_1_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    buckets_y_address0 <= buckets_y_address0_local;

    buckets_y_address0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter15, ap_CS_fsm_pp0_stage1, buckets_y_addr_reg_530_pp0_iter15_reg, ap_block_pp0_stage0, zext_ln532_fu_393_p1, ap_block_pp0_stage1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter15 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            buckets_y_address0_local <= buckets_y_addr_reg_530_pp0_iter15_reg;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            buckets_y_address0_local <= zext_ln532_fu_393_p1(14 - 1 downto 0);
        else 
            buckets_y_address0_local <= "XXXXXXXXXXXXXX";
        end if; 
    end process;

    buckets_y_address1 <= buckets_y_addr_reg_530_pp0_iter2_reg;
    buckets_y_ce0 <= buckets_y_ce0_local;

    buckets_y_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter15, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter15 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            buckets_y_ce0_local <= ap_const_logic_1;
        else 
            buckets_y_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    buckets_y_ce1 <= buckets_y_ce1_local;

    buckets_y_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            buckets_y_ce1_local <= ap_const_logic_1;
        else 
            buckets_y_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    buckets_y_d0 <= new_bucket_point_y_reg_598;
    buckets_y_d1 <= ap_const_lv256_lc_8;
    buckets_y_we0 <= buckets_y_we0_local;

    buckets_y_we0_local_assign_proc : process(ap_enable_reg_pp0_iter15, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, trunc_ln531_reg_505_pp0_iter14_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter15 = ap_const_logic_1) and (trunc_ln531_reg_505_pp0_iter14_reg = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            buckets_y_we0_local <= ap_const_logic_1;
        else 
            buckets_y_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    buckets_y_we1 <= buckets_y_we1_local;

    buckets_y_we1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, trunc_ln531_reg_505_pp0_iter1_reg, icmp_ln482_reg_578)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (icmp_ln482_reg_578 = ap_const_lv1_1) and (trunc_ln531_reg_505_pp0_iter1_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            buckets_y_we1_local <= ap_const_logic_1;
        else 
            buckets_y_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    buckets_z_1_address0 <= buckets_z_1_address0_local;

    buckets_z_1_address0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter15, ap_CS_fsm_pp0_stage1, buckets_z_1_addr_reg_548_pp0_iter2_reg, buckets_z_1_addr_reg_548_pp0_iter15_reg, ap_block_pp0_stage0, ap_block_pp0_stage1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter15 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            buckets_z_1_address0_local <= buckets_z_1_addr_reg_548_pp0_iter15_reg;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            buckets_z_1_address0_local <= buckets_z_1_addr_reg_548_pp0_iter2_reg;
        else 
            buckets_z_1_address0_local <= "XXXXXXXXXXXXXX";
        end if; 
    end process;

    buckets_z_1_address1 <= buckets_z_1_addr_reg_548_pp0_iter2_reg;
    buckets_z_1_ce0 <= buckets_z_1_ce0_local;

    buckets_z_1_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter15, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter15 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            buckets_z_1_ce0_local <= ap_const_logic_1;
        else 
            buckets_z_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    buckets_z_1_ce1 <= buckets_z_1_ce1_local;

    buckets_z_1_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            buckets_z_1_ce1_local <= ap_const_logic_1;
        else 
            buckets_z_1_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    buckets_z_1_d0 <= new_bucket_point_z_reg_604;
    buckets_z_1_d1 <= ap_const_lv256_lc_8;
    buckets_z_1_we0 <= buckets_z_1_we0_local;

    buckets_z_1_we0_local_assign_proc : process(ap_enable_reg_pp0_iter15, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, trunc_ln531_reg_505_pp0_iter14_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter15 = ap_const_logic_1) and (trunc_ln531_reg_505_pp0_iter14_reg = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            buckets_z_1_we0_local <= ap_const_logic_1;
        else 
            buckets_z_1_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    buckets_z_1_we1 <= buckets_z_1_we1_local;

    buckets_z_1_we1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, trunc_ln531_reg_505_pp0_iter1_reg, icmp_ln482_reg_578)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (icmp_ln482_reg_578 = ap_const_lv1_1) and (trunc_ln531_reg_505_pp0_iter1_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            buckets_z_1_we1_local <= ap_const_logic_1;
        else 
            buckets_z_1_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    buckets_z_address0 <= buckets_z_address0_local;

    buckets_z_address0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter15, ap_CS_fsm_pp0_stage1, buckets_z_addr_reg_542_pp0_iter2_reg, buckets_z_addr_reg_542_pp0_iter15_reg, ap_block_pp0_stage0, ap_block_pp0_stage1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter15 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            buckets_z_address0_local <= buckets_z_addr_reg_542_pp0_iter15_reg;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            buckets_z_address0_local <= buckets_z_addr_reg_542_pp0_iter2_reg;
        else 
            buckets_z_address0_local <= "XXXXXXXXXXXXXX";
        end if; 
    end process;

    buckets_z_address1 <= buckets_z_addr_reg_542_pp0_iter2_reg;
    buckets_z_ce0 <= buckets_z_ce0_local;

    buckets_z_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter15, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter15 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            buckets_z_ce0_local <= ap_const_logic_1;
        else 
            buckets_z_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    buckets_z_ce1 <= buckets_z_ce1_local;

    buckets_z_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            buckets_z_ce1_local <= ap_const_logic_1;
        else 
            buckets_z_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    buckets_z_d0 <= new_bucket_point_z_reg_604;
    buckets_z_d1 <= ap_const_lv256_lc_8;
    buckets_z_we0 <= buckets_z_we0_local;

    buckets_z_we0_local_assign_proc : process(ap_enable_reg_pp0_iter15, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, trunc_ln531_reg_505_pp0_iter14_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter15 = ap_const_logic_1) and (trunc_ln531_reg_505_pp0_iter14_reg = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            buckets_z_we0_local <= ap_const_logic_1;
        else 
            buckets_z_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    buckets_z_we1 <= buckets_z_we1_local;

    buckets_z_we1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, trunc_ln531_reg_505_pp0_iter1_reg, icmp_ln482_reg_578)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (icmp_ln482_reg_578 = ap_const_lv1_1) and (trunc_ln531_reg_505_pp0_iter1_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            buckets_z_we1_local <= ap_const_logic_1;
        else 
            buckets_z_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln482_fu_422_p2 <= "1" when (or_ln482_fu_418_p2 = ap_const_lv256_lc_1) else "0";
    icmp_ln528_fu_322_p2 <= "1" when (ap_sig_allocacmp_j_1 = ap_const_lv5_1A) else "0";
    lshr_ln1_fu_334_p4 <= ap_sig_allocacmp_j_1(4 downto 1);
    lshr_ln2_fu_377_p4 <= scalar_partition_fu_365_p3(14 downto 1);
    or_ln482_fu_418_p2 <= (select_ln482_reg_566 or select_ln482_1_reg_572);
    scalar_partition_buffer_2_address0 <= zext_ln528_fu_344_p1(4 - 1 downto 0);
    scalar_partition_buffer_2_ce0 <= scalar_partition_buffer_2_ce0_local;

    scalar_partition_buffer_2_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            scalar_partition_buffer_2_ce0_local <= ap_const_logic_1;
        else 
            scalar_partition_buffer_2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    scalar_partition_buffer_address0 <= zext_ln528_fu_344_p1(4 - 1 downto 0);
    scalar_partition_buffer_ce0 <= scalar_partition_buffer_ce0_local;

    scalar_partition_buffer_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            scalar_partition_buffer_ce0_local <= ap_const_logic_1;
        else 
            scalar_partition_buffer_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    scalar_partition_fu_365_p3 <= 
        scalar_partition_buffer_2_q0 when (trunc_ln528_fu_362_p1(0) = '1') else 
        scalar_partition_buffer_q0;
    select_ln482_1_fu_411_p3 <= 
        buckets_y_1_q0 when (trunc_ln531_reg_505(0) = '1') else 
        buckets_y_q0;
    select_ln482_fu_404_p3 <= 
        buckets_x_1_q0 when (trunc_ln531_reg_505(0) = '1') else 
        buckets_x_q0;
    select_ln492_1_fu_435_p3 <= 
        buckets_t_1_q0 when (trunc_ln531_reg_505_pp0_iter2_reg(0) = '1') else 
        buckets_t_q0;
    select_ln492_fu_428_p3 <= 
        buckets_z_1_q0 when (trunc_ln531_reg_505_pp0_iter2_reg(0) = '1') else 
        buckets_z_q0;
    tmp_fu_355_p3 <= (j_1_reg_485 & ap_const_lv9_0);
    trunc_ln528_fu_362_p1 <= j_1_reg_485(1 - 1 downto 0);
    trunc_ln531_fu_373_p1 <= scalar_partition_fu_365_p3(1 - 1 downto 0);
    zext_ln528_fu_344_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln1_fu_334_p4),64));
    zext_ln532_fu_393_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln532_reg_513),64));
end behav;
