-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity pippenger_control is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    x_stream_dout : IN STD_LOGIC_VECTOR (255 downto 0);
    x_stream_empty_n : IN STD_LOGIC;
    x_stream_read : OUT STD_LOGIC;
    y_stream_dout : IN STD_LOGIC_VECTOR (255 downto 0);
    y_stream_empty_n : IN STD_LOGIC;
    y_stream_read : OUT STD_LOGIC;
    z_stream_dout : IN STD_LOGIC_VECTOR (255 downto 0);
    z_stream_empty_n : IN STD_LOGIC;
    z_stream_read : OUT STD_LOGIC;
    t_stream_dout : IN STD_LOGIC_VECTOR (255 downto 0);
    t_stream_empty_n : IN STD_LOGIC;
    t_stream_read : OUT STD_LOGIC;
    scalar_stream_dout : IN STD_LOGIC_VECTOR (255 downto 0);
    scalar_stream_empty_n : IN STD_LOGIC;
    scalar_stream_read : OUT STD_LOGIC;
    out_stream_din : OUT STD_LOGIC_VECTOR (1038 downto 0);
    out_stream_full_n : IN STD_LOGIC;
    out_stream_write : OUT STD_LOGIC );
end;


architecture behav of pippenger_control is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "pippenger_control_pippenger_control,hls_ip_2024_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu7ev-ffvc1156-2-e,HLS_INPUT_CLOCK=4.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=2.920000,HLS_SYN_LAT=218103811,HLS_SYN_TPT=none,HLS_SYN_MEM=4,HLS_SYN_DSP=0,HLS_SYN_FF=89,HLS_SYN_LUT=507,HLS_VERSION=2024_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_0 : BOOLEAN := false;

    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal grp_pippenger_control_Pipeline_VITIS_LOOP_544_1_fu_56_ap_start : STD_LOGIC;
    signal grp_pippenger_control_Pipeline_VITIS_LOOP_544_1_fu_56_ap_done : STD_LOGIC;
    signal grp_pippenger_control_Pipeline_VITIS_LOOP_544_1_fu_56_ap_idle : STD_LOGIC;
    signal grp_pippenger_control_Pipeline_VITIS_LOOP_544_1_fu_56_ap_ready : STD_LOGIC;
    signal grp_pippenger_control_Pipeline_VITIS_LOOP_544_1_fu_56_x_stream_read : STD_LOGIC;
    signal grp_pippenger_control_Pipeline_VITIS_LOOP_544_1_fu_56_y_stream_read : STD_LOGIC;
    signal grp_pippenger_control_Pipeline_VITIS_LOOP_544_1_fu_56_z_stream_read : STD_LOGIC;
    signal grp_pippenger_control_Pipeline_VITIS_LOOP_544_1_fu_56_t_stream_read : STD_LOGIC;
    signal grp_pippenger_control_Pipeline_VITIS_LOOP_544_1_fu_56_scalar_stream_read : STD_LOGIC;
    signal grp_pippenger_control_Pipeline_VITIS_LOOP_568_1_VITIS_LOOP_570_2_fu_70_ap_start : STD_LOGIC;
    signal grp_pippenger_control_Pipeline_VITIS_LOOP_568_1_VITIS_LOOP_570_2_fu_70_ap_done : STD_LOGIC;
    signal grp_pippenger_control_Pipeline_VITIS_LOOP_568_1_VITIS_LOOP_570_2_fu_70_ap_idle : STD_LOGIC;
    signal grp_pippenger_control_Pipeline_VITIS_LOOP_568_1_VITIS_LOOP_570_2_fu_70_ap_ready : STD_LOGIC;
    signal grp_pippenger_control_Pipeline_VITIS_LOOP_568_1_VITIS_LOOP_570_2_fu_70_out_stream_din : STD_LOGIC_VECTOR (1038 downto 0);
    signal grp_pippenger_control_Pipeline_VITIS_LOOP_568_1_VITIS_LOOP_570_2_fu_70_out_stream_write : STD_LOGIC;
    signal grp_pippenger_control_Pipeline_VITIS_LOOP_544_1_fu_56_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal grp_pippenger_control_Pipeline_VITIS_LOOP_568_1_VITIS_LOOP_570_2_fu_70_ap_start_reg : STD_LOGIC := '0';
    signal ap_block_state2_on_subcall_done : BOOLEAN;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component pippenger_control_pippenger_control_Pipeline_VITIS_LOOP_544_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        x_stream_dout : IN STD_LOGIC_VECTOR (255 downto 0);
        x_stream_empty_n : IN STD_LOGIC;
        x_stream_read : OUT STD_LOGIC;
        y_stream_dout : IN STD_LOGIC_VECTOR (255 downto 0);
        y_stream_empty_n : IN STD_LOGIC;
        y_stream_read : OUT STD_LOGIC;
        z_stream_dout : IN STD_LOGIC_VECTOR (255 downto 0);
        z_stream_empty_n : IN STD_LOGIC;
        z_stream_read : OUT STD_LOGIC;
        t_stream_dout : IN STD_LOGIC_VECTOR (255 downto 0);
        t_stream_empty_n : IN STD_LOGIC;
        t_stream_read : OUT STD_LOGIC;
        scalar_stream_dout : IN STD_LOGIC_VECTOR (255 downto 0);
        scalar_stream_empty_n : IN STD_LOGIC;
        scalar_stream_read : OUT STD_LOGIC );
    end component;


    component pippenger_control_pippenger_control_Pipeline_VITIS_LOOP_568_1_VITIS_LOOP_570_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        out_stream_din : OUT STD_LOGIC_VECTOR (1038 downto 0);
        out_stream_full_n : IN STD_LOGIC;
        out_stream_write : OUT STD_LOGIC );
    end component;



begin
    grp_pippenger_control_Pipeline_VITIS_LOOP_544_1_fu_56 : component pippenger_control_pippenger_control_Pipeline_VITIS_LOOP_544_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_pippenger_control_Pipeline_VITIS_LOOP_544_1_fu_56_ap_start,
        ap_done => grp_pippenger_control_Pipeline_VITIS_LOOP_544_1_fu_56_ap_done,
        ap_idle => grp_pippenger_control_Pipeline_VITIS_LOOP_544_1_fu_56_ap_idle,
        ap_ready => grp_pippenger_control_Pipeline_VITIS_LOOP_544_1_fu_56_ap_ready,
        x_stream_dout => x_stream_dout,
        x_stream_empty_n => x_stream_empty_n,
        x_stream_read => grp_pippenger_control_Pipeline_VITIS_LOOP_544_1_fu_56_x_stream_read,
        y_stream_dout => y_stream_dout,
        y_stream_empty_n => y_stream_empty_n,
        y_stream_read => grp_pippenger_control_Pipeline_VITIS_LOOP_544_1_fu_56_y_stream_read,
        z_stream_dout => z_stream_dout,
        z_stream_empty_n => z_stream_empty_n,
        z_stream_read => grp_pippenger_control_Pipeline_VITIS_LOOP_544_1_fu_56_z_stream_read,
        t_stream_dout => t_stream_dout,
        t_stream_empty_n => t_stream_empty_n,
        t_stream_read => grp_pippenger_control_Pipeline_VITIS_LOOP_544_1_fu_56_t_stream_read,
        scalar_stream_dout => scalar_stream_dout,
        scalar_stream_empty_n => scalar_stream_empty_n,
        scalar_stream_read => grp_pippenger_control_Pipeline_VITIS_LOOP_544_1_fu_56_scalar_stream_read);

    grp_pippenger_control_Pipeline_VITIS_LOOP_568_1_VITIS_LOOP_570_2_fu_70 : component pippenger_control_pippenger_control_Pipeline_VITIS_LOOP_568_1_VITIS_LOOP_570_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_pippenger_control_Pipeline_VITIS_LOOP_568_1_VITIS_LOOP_570_2_fu_70_ap_start,
        ap_done => grp_pippenger_control_Pipeline_VITIS_LOOP_568_1_VITIS_LOOP_570_2_fu_70_ap_done,
        ap_idle => grp_pippenger_control_Pipeline_VITIS_LOOP_568_1_VITIS_LOOP_570_2_fu_70_ap_idle,
        ap_ready => grp_pippenger_control_Pipeline_VITIS_LOOP_568_1_VITIS_LOOP_570_2_fu_70_ap_ready,
        out_stream_din => grp_pippenger_control_Pipeline_VITIS_LOOP_568_1_VITIS_LOOP_570_2_fu_70_out_stream_din,
        out_stream_full_n => out_stream_full_n,
        out_stream_write => grp_pippenger_control_Pipeline_VITIS_LOOP_568_1_VITIS_LOOP_570_2_fu_70_out_stream_write);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_pippenger_control_Pipeline_VITIS_LOOP_544_1_fu_56_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_pippenger_control_Pipeline_VITIS_LOOP_544_1_fu_56_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    grp_pippenger_control_Pipeline_VITIS_LOOP_544_1_fu_56_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_pippenger_control_Pipeline_VITIS_LOOP_544_1_fu_56_ap_ready = ap_const_logic_1)) then 
                    grp_pippenger_control_Pipeline_VITIS_LOOP_544_1_fu_56_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_pippenger_control_Pipeline_VITIS_LOOP_568_1_VITIS_LOOP_570_2_fu_70_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_pippenger_control_Pipeline_VITIS_LOOP_568_1_VITIS_LOOP_570_2_fu_70_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    grp_pippenger_control_Pipeline_VITIS_LOOP_568_1_VITIS_LOOP_570_2_fu_70_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_pippenger_control_Pipeline_VITIS_LOOP_568_1_VITIS_LOOP_570_2_fu_70_ap_ready = ap_const_logic_1)) then 
                    grp_pippenger_control_Pipeline_VITIS_LOOP_568_1_VITIS_LOOP_570_2_fu_70_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, ap_block_state2_on_subcall_done)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_boolean_0 = ap_block_state2_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(ap_block_state2_on_subcall_done)
    begin
        if ((ap_const_boolean_1 = ap_block_state2_on_subcall_done)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state2_on_subcall_done_assign_proc : process(grp_pippenger_control_Pipeline_VITIS_LOOP_544_1_fu_56_ap_done, grp_pippenger_control_Pipeline_VITIS_LOOP_568_1_VITIS_LOOP_570_2_fu_70_ap_done)
    begin
                ap_block_state2_on_subcall_done <= ((grp_pippenger_control_Pipeline_VITIS_LOOP_568_1_VITIS_LOOP_570_2_fu_70_ap_done = ap_const_logic_0) or (grp_pippenger_control_Pipeline_VITIS_LOOP_544_1_fu_56_ap_done = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_CS_fsm_state2, ap_block_state2_on_subcall_done)
    begin
        if (((ap_const_boolean_0 = ap_block_state2_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state2, ap_block_state2_on_subcall_done)
    begin
        if (((ap_const_boolean_0 = ap_block_state2_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    grp_pippenger_control_Pipeline_VITIS_LOOP_544_1_fu_56_ap_start <= grp_pippenger_control_Pipeline_VITIS_LOOP_544_1_fu_56_ap_start_reg;
    grp_pippenger_control_Pipeline_VITIS_LOOP_568_1_VITIS_LOOP_570_2_fu_70_ap_start <= grp_pippenger_control_Pipeline_VITIS_LOOP_568_1_VITIS_LOOP_570_2_fu_70_ap_start_reg;
    out_stream_din <= grp_pippenger_control_Pipeline_VITIS_LOOP_568_1_VITIS_LOOP_570_2_fu_70_out_stream_din;
    out_stream_write <= grp_pippenger_control_Pipeline_VITIS_LOOP_568_1_VITIS_LOOP_570_2_fu_70_out_stream_write;
    scalar_stream_read <= grp_pippenger_control_Pipeline_VITIS_LOOP_544_1_fu_56_scalar_stream_read;
    t_stream_read <= grp_pippenger_control_Pipeline_VITIS_LOOP_544_1_fu_56_t_stream_read;
    x_stream_read <= grp_pippenger_control_Pipeline_VITIS_LOOP_544_1_fu_56_x_stream_read;
    y_stream_read <= grp_pippenger_control_Pipeline_VITIS_LOOP_544_1_fu_56_y_stream_read;
    z_stream_read <= grp_pippenger_control_Pipeline_VITIS_LOOP_544_1_fu_56_z_stream_read;
end behav;
