-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity pippenger_control_pippenger_control_Pipeline_VITIS_LOOP_544_1 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    x_stream_dout : IN STD_LOGIC_VECTOR (255 downto 0);
    x_stream_empty_n : IN STD_LOGIC;
    x_stream_read : OUT STD_LOGIC;
    y_stream_dout : IN STD_LOGIC_VECTOR (255 downto 0);
    y_stream_empty_n : IN STD_LOGIC;
    y_stream_read : OUT STD_LOGIC;
    z_stream_dout : IN STD_LOGIC_VECTOR (255 downto 0);
    z_stream_empty_n : IN STD_LOGIC;
    z_stream_read : OUT STD_LOGIC;
    t_stream_dout : IN STD_LOGIC_VECTOR (255 downto 0);
    t_stream_empty_n : IN STD_LOGIC;
    t_stream_read : OUT STD_LOGIC;
    scalar_stream_dout : IN STD_LOGIC_VECTOR (255 downto 0);
    scalar_stream_empty_n : IN STD_LOGIC;
    scalar_stream_read : OUT STD_LOGIC );
end;


architecture behav of pippenger_control_pippenger_control_Pipeline_VITIS_LOOP_544_1 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000000000000001";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000000000000010";
    constant ap_ST_fsm_pp0_stage2 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000000000000100";
    constant ap_ST_fsm_pp0_stage3 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000000000001000";
    constant ap_ST_fsm_pp0_stage4 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000000000010000";
    constant ap_ST_fsm_pp0_stage5 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000000000100000";
    constant ap_ST_fsm_pp0_stage6 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000000001000000";
    constant ap_ST_fsm_pp0_stage7 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000000010000000";
    constant ap_ST_fsm_pp0_stage8 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000000100000000";
    constant ap_ST_fsm_pp0_stage9 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000001000000000";
    constant ap_ST_fsm_pp0_stage10 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000010000000000";
    constant ap_ST_fsm_pp0_stage11 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000100000000000";
    constant ap_ST_fsm_pp0_stage12 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000001000000000000";
    constant ap_ST_fsm_pp0_stage13 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000010000000000000";
    constant ap_ST_fsm_pp0_stage14 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000100000000000000";
    constant ap_ST_fsm_pp0_stage15 : STD_LOGIC_VECTOR (25 downto 0) := "00000000001000000000000000";
    constant ap_ST_fsm_pp0_stage16 : STD_LOGIC_VECTOR (25 downto 0) := "00000000010000000000000000";
    constant ap_ST_fsm_pp0_stage17 : STD_LOGIC_VECTOR (25 downto 0) := "00000000100000000000000000";
    constant ap_ST_fsm_pp0_stage18 : STD_LOGIC_VECTOR (25 downto 0) := "00000001000000000000000000";
    constant ap_ST_fsm_pp0_stage19 : STD_LOGIC_VECTOR (25 downto 0) := "00000010000000000000000000";
    constant ap_ST_fsm_pp0_stage20 : STD_LOGIC_VECTOR (25 downto 0) := "00000100000000000000000000";
    constant ap_ST_fsm_pp0_stage21 : STD_LOGIC_VECTOR (25 downto 0) := "00001000000000000000000000";
    constant ap_ST_fsm_pp0_stage22 : STD_LOGIC_VECTOR (25 downto 0) := "00010000000000000000000000";
    constant ap_ST_fsm_pp0_stage23 : STD_LOGIC_VECTOR (25 downto 0) := "00100000000000000000000000";
    constant ap_ST_fsm_pp0_stage24 : STD_LOGIC_VECTOR (25 downto 0) := "01000000000000000000000000";
    constant ap_ST_fsm_pp0_stage25 : STD_LOGIC_VECTOR (25 downto 0) := "10000000000000000000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal scalar_partition_stream_full_n : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal tmp_nbreadreq_fu_150_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage25 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage25 : signal is "none";
    signal tmp_reg_558 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state26_pp0_stage25_iter0_grp29 : BOOLEAN;
    signal ap_enable_reg_pp0_iter0_reg : STD_LOGIC := '0';
    signal ap_block_pp0_stage25_subdone : BOOLEAN;
    signal x_stream_blk_n : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_block_pp0_stage1_grp1 : BOOLEAN;
    signal ap_block_pp0_stage1_subdone_grp1_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage1_subdone_grp1 : BOOLEAN;
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal y_stream_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage1_grp2 : BOOLEAN;
    signal ap_block_pp0_stage1_subdone_grp2_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage1_subdone_grp2 : BOOLEAN;
    signal z_stream_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage1_grp3 : BOOLEAN;
    signal ap_block_pp0_stage1_subdone_grp3_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage1_subdone_grp3 : BOOLEAN;
    signal t_stream_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage1_grp4 : BOOLEAN;
    signal ap_block_pp0_stage1_subdone_grp4_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage1_subdone_grp4 : BOOLEAN;
    signal scalar_stream_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage1_grp5 : BOOLEAN;
    signal ap_block_pp0_stage1_subdone_grp5_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage1_subdone_grp5 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal ap_block_state2_pp0_stage1_iter0_grp5 : BOOLEAN;
    signal ap_block_pp0_stage1_11001_grp5 : BOOLEAN;
    signal ap_block_state2_pp0_stage1_iter0_grp1 : BOOLEAN;
    signal ap_block_pp0_stage1_11001_grp1 : BOOLEAN;
    signal ap_block_state2_pp0_stage1_iter0_grp2 : BOOLEAN;
    signal ap_block_pp0_stage1_11001_grp2 : BOOLEAN;
    signal ap_block_state2_pp0_stage1_iter0_grp3 : BOOLEAN;
    signal ap_block_pp0_stage1_11001_grp3 : BOOLEAN;
    signal ap_block_state2_pp0_stage1_iter0_grp4 : BOOLEAN;
    signal ap_block_pp0_stage1_11001_grp4 : BOOLEAN;
    signal ap_block_pp0_stage1_01001_grp5 : BOOLEAN;
    signal ap_block_state3_pp0_stage2_iter0_grp6 : BOOLEAN;
    signal ap_block_pp0_stage2_01001_grp6 : BOOLEAN;
    signal ap_block_state4_pp0_stage3_iter0_grp7 : BOOLEAN;
    signal ap_block_pp0_stage3_01001_grp7 : BOOLEAN;
    signal ap_block_state5_pp0_stage4_iter0_grp8 : BOOLEAN;
    signal ap_block_pp0_stage4_01001_grp8 : BOOLEAN;
    signal ap_block_state6_pp0_stage5_iter0_grp9 : BOOLEAN;
    signal ap_block_pp0_stage5_01001_grp9 : BOOLEAN;
    signal ap_block_state7_pp0_stage6_iter0_grp10 : BOOLEAN;
    signal ap_block_pp0_stage6_01001_grp10 : BOOLEAN;
    signal ap_block_state8_pp0_stage7_iter0_grp11 : BOOLEAN;
    signal ap_block_pp0_stage7_01001_grp11 : BOOLEAN;
    signal ap_block_state9_pp0_stage8_iter0_grp12 : BOOLEAN;
    signal ap_block_pp0_stage8_01001_grp12 : BOOLEAN;
    signal ap_block_state10_pp0_stage9_iter0_grp13 : BOOLEAN;
    signal ap_block_pp0_stage9_01001_grp13 : BOOLEAN;
    signal ap_block_state11_pp0_stage10_iter0_grp14 : BOOLEAN;
    signal ap_block_pp0_stage10_01001_grp14 : BOOLEAN;
    signal ap_block_state12_pp0_stage11_iter0_grp15 : BOOLEAN;
    signal ap_block_pp0_stage11_01001_grp15 : BOOLEAN;
    signal ap_block_state13_pp0_stage12_iter0_grp16 : BOOLEAN;
    signal ap_block_pp0_stage12_01001_grp16 : BOOLEAN;
    signal ap_block_state14_pp0_stage13_iter0_grp17 : BOOLEAN;
    signal ap_block_pp0_stage13_01001_grp17 : BOOLEAN;
    signal ap_block_state15_pp0_stage14_iter0_grp18 : BOOLEAN;
    signal ap_block_pp0_stage14_01001_grp18 : BOOLEAN;
    signal ap_block_state16_pp0_stage15_iter0_grp19 : BOOLEAN;
    signal ap_block_pp0_stage15_01001_grp19 : BOOLEAN;
    signal ap_block_state17_pp0_stage16_iter0_grp20 : BOOLEAN;
    signal ap_block_pp0_stage16_01001_grp20 : BOOLEAN;
    signal ap_block_state18_pp0_stage17_iter0_grp21 : BOOLEAN;
    signal ap_block_pp0_stage17_01001_grp21 : BOOLEAN;
    signal ap_block_state19_pp0_stage18_iter0_grp22 : BOOLEAN;
    signal ap_block_pp0_stage18_01001_grp22 : BOOLEAN;
    signal ap_block_state20_pp0_stage19_iter0_grp23 : BOOLEAN;
    signal ap_block_pp0_stage19_01001_grp23 : BOOLEAN;
    signal ap_block_state21_pp0_stage20_iter0_grp24 : BOOLEAN;
    signal ap_block_pp0_stage20_01001_grp24 : BOOLEAN;
    signal ap_block_state22_pp0_stage21_iter0_grp25 : BOOLEAN;
    signal ap_block_pp0_stage21_01001_grp25 : BOOLEAN;
    signal ap_block_state23_pp0_stage22_iter0_grp26 : BOOLEAN;
    signal ap_block_pp0_stage22_01001_grp26 : BOOLEAN;
    signal ap_block_state24_pp0_stage23_iter0_grp27 : BOOLEAN;
    signal ap_block_pp0_stage23_01001_grp27 : BOOLEAN;
    signal ap_block_state25_pp0_stage24_iter0_grp28 : BOOLEAN;
    signal ap_block_pp0_stage24_01001_grp28 : BOOLEAN;
    signal ap_block_pp0_stage25_01001_grp29 : BOOLEAN;
    signal ap_block_pp0_stage0_01001_grp30 : BOOLEAN;
    signal ap_block_pp0_stage2_11001_grp6 : BOOLEAN;
    signal ap_block_pp0_stage3_11001_grp7 : BOOLEAN;
    signal ap_block_pp0_stage4_11001_grp8 : BOOLEAN;
    signal ap_block_pp0_stage5_11001_grp9 : BOOLEAN;
    signal ap_block_pp0_stage6_11001_grp10 : BOOLEAN;
    signal ap_block_pp0_stage7_11001_grp11 : BOOLEAN;
    signal ap_block_pp0_stage8_11001_grp12 : BOOLEAN;
    signal ap_block_pp0_stage9_11001_grp13 : BOOLEAN;
    signal ap_block_pp0_stage10_11001_grp14 : BOOLEAN;
    signal ap_block_pp0_stage11_11001_grp15 : BOOLEAN;
    signal ap_block_pp0_stage12_11001_grp16 : BOOLEAN;
    signal ap_block_pp0_stage13_11001_grp17 : BOOLEAN;
    signal ap_block_pp0_stage14_11001_grp18 : BOOLEAN;
    signal ap_block_pp0_stage15_11001_grp19 : BOOLEAN;
    signal ap_block_pp0_stage16_11001_grp20 : BOOLEAN;
    signal ap_block_pp0_stage17_11001_grp21 : BOOLEAN;
    signal ap_block_pp0_stage18_11001_grp22 : BOOLEAN;
    signal ap_block_pp0_stage19_11001_grp23 : BOOLEAN;
    signal ap_block_pp0_stage20_11001_grp24 : BOOLEAN;
    signal ap_block_pp0_stage21_11001_grp25 : BOOLEAN;
    signal ap_block_pp0_stage22_11001_grp26 : BOOLEAN;
    signal ap_block_pp0_stage23_11001_grp27 : BOOLEAN;
    signal ap_block_pp0_stage24_11001_grp28 : BOOLEAN;
    signal ap_block_pp0_stage25_11001_grp29 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_grp30 : BOOLEAN;
    signal ap_block_pp0_stage2_grp6 : BOOLEAN;
    signal ap_block_pp0_stage3_grp7 : BOOLEAN;
    signal ap_block_pp0_stage4_grp8 : BOOLEAN;
    signal ap_block_pp0_stage5_grp9 : BOOLEAN;
    signal ap_block_pp0_stage6_grp10 : BOOLEAN;
    signal ap_block_pp0_stage7_grp11 : BOOLEAN;
    signal ap_block_pp0_stage8_grp12 : BOOLEAN;
    signal ap_block_pp0_stage9_grp13 : BOOLEAN;
    signal ap_block_pp0_stage10_grp14 : BOOLEAN;
    signal ap_block_pp0_stage11_grp15 : BOOLEAN;
    signal ap_block_pp0_stage12_grp16 : BOOLEAN;
    signal ap_block_pp0_stage13_grp17 : BOOLEAN;
    signal ap_block_pp0_stage14_grp18 : BOOLEAN;
    signal ap_block_pp0_stage15_grp19 : BOOLEAN;
    signal ap_block_pp0_stage16_grp20 : BOOLEAN;
    signal ap_block_pp0_stage17_grp21 : BOOLEAN;
    signal ap_block_pp0_stage18_grp22 : BOOLEAN;
    signal ap_block_pp0_stage19_grp23 : BOOLEAN;
    signal ap_block_pp0_stage20_grp24 : BOOLEAN;
    signal ap_block_pp0_stage21_grp25 : BOOLEAN;
    signal ap_block_pp0_stage22_grp26 : BOOLEAN;
    signal ap_block_pp0_stage23_grp27 : BOOLEAN;
    signal ap_block_pp0_stage24_grp28 : BOOLEAN;
    signal ap_block_pp0_stage25_grp29 : BOOLEAN;
    signal ap_block_pp0_stage0_grp30 : BOOLEAN;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (25 downto 0);
    signal ap_idle_pp0_1to1 : STD_LOGIC;
    signal ap_block_pp0_stage2_subdone : BOOLEAN;
    signal ap_block_pp0_stage3_subdone : BOOLEAN;
    signal ap_block_pp0_stage4_subdone : BOOLEAN;
    signal ap_block_pp0_stage5_subdone : BOOLEAN;
    signal ap_block_pp0_stage6_subdone : BOOLEAN;
    signal ap_block_pp0_stage7_subdone : BOOLEAN;
    signal ap_block_pp0_stage8_subdone : BOOLEAN;
    signal ap_block_pp0_stage9_subdone : BOOLEAN;
    signal ap_block_pp0_stage10_subdone : BOOLEAN;
    signal ap_block_pp0_stage11_subdone : BOOLEAN;
    signal ap_block_pp0_stage12_subdone : BOOLEAN;
    signal ap_block_pp0_stage13_subdone : BOOLEAN;
    signal ap_block_pp0_stage14_subdone : BOOLEAN;
    signal ap_block_pp0_stage15_subdone : BOOLEAN;
    signal ap_block_pp0_stage16_subdone : BOOLEAN;
    signal ap_block_pp0_stage17_subdone : BOOLEAN;
    signal ap_block_pp0_stage18_subdone : BOOLEAN;
    signal ap_block_pp0_stage19_subdone : BOOLEAN;
    signal ap_block_pp0_stage20_subdone : BOOLEAN;
    signal ap_block_pp0_stage21_subdone : BOOLEAN;
    signal ap_block_pp0_stage22_subdone : BOOLEAN;
    signal ap_block_pp0_stage23_subdone : BOOLEAN;
    signal ap_block_pp0_stage24_subdone : BOOLEAN;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_loop_init : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component pippenger_control_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component pippenger_control_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_block_pp0_stage1_subdone_grp1_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage1_subdone_grp1_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then 
                        ap_block_pp0_stage1_subdone_grp1_done_reg <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp1)) then 
                        ap_block_pp0_stage1_subdone_grp1_done_reg <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage1_subdone_grp2_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage1_subdone_grp2_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then 
                        ap_block_pp0_stage1_subdone_grp2_done_reg <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp2)) then 
                        ap_block_pp0_stage1_subdone_grp2_done_reg <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage1_subdone_grp3_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage1_subdone_grp3_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then 
                        ap_block_pp0_stage1_subdone_grp3_done_reg <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp3)) then 
                        ap_block_pp0_stage1_subdone_grp3_done_reg <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage1_subdone_grp4_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage1_subdone_grp4_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then 
                        ap_block_pp0_stage1_subdone_grp4_done_reg <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp4)) then 
                        ap_block_pp0_stage1_subdone_grp4_done_reg <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage1_subdone_grp5_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage1_subdone_grp5_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then 
                        ap_block_pp0_stage1_subdone_grp5_done_reg <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp5)) then 
                        ap_block_pp0_stage1_subdone_grp5_done_reg <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage25_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage25))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                tmp_reg_558 <= tmp_nbreadreq_fu_150_p3;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage0_subdone, ap_condition_exit_pp0_iter0_stage0, ap_block_pp0_stage25_subdone, ap_block_pp0_stage1_subdone, ap_idle_pp0_1to1, ap_block_pp0_stage2_subdone, ap_block_pp0_stage3_subdone, ap_block_pp0_stage4_subdone, ap_block_pp0_stage5_subdone, ap_block_pp0_stage6_subdone, ap_block_pp0_stage7_subdone, ap_block_pp0_stage8_subdone, ap_block_pp0_stage9_subdone, ap_block_pp0_stage10_subdone, ap_block_pp0_stage11_subdone, ap_block_pp0_stage12_subdone, ap_block_pp0_stage13_subdone, ap_block_pp0_stage14_subdone, ap_block_pp0_stage15_subdone, ap_block_pp0_stage16_subdone, ap_block_pp0_stage17_subdone, ap_block_pp0_stage18_subdone, ap_block_pp0_stage19_subdone, ap_block_pp0_stage20_subdone, ap_block_pp0_stage21_subdone, ap_block_pp0_stage22_subdone, ap_block_pp0_stage23_subdone, ap_block_pp0_stage24_subdone, ap_start_int)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif ((not(((ap_start_int = ap_const_logic_0) and (ap_idle_pp0_1to1 = ap_const_logic_1))) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when ap_ST_fsm_pp0_stage2 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage3;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                end if;
            when ap_ST_fsm_pp0_stage3 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage3_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage4;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage3;
                end if;
            when ap_ST_fsm_pp0_stage4 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage4_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage5;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage4;
                end if;
            when ap_ST_fsm_pp0_stage5 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage5_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage6;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage5;
                end if;
            when ap_ST_fsm_pp0_stage6 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage6_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage7;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage6;
                end if;
            when ap_ST_fsm_pp0_stage7 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage7_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage8;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage7;
                end if;
            when ap_ST_fsm_pp0_stage8 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage8_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage9;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage8;
                end if;
            when ap_ST_fsm_pp0_stage9 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage9_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage10;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage9;
                end if;
            when ap_ST_fsm_pp0_stage10 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage10_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage11;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage10;
                end if;
            when ap_ST_fsm_pp0_stage11 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage11_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage12;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage11;
                end if;
            when ap_ST_fsm_pp0_stage12 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage12_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage13;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage12;
                end if;
            when ap_ST_fsm_pp0_stage13 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage13_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage14;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage13;
                end if;
            when ap_ST_fsm_pp0_stage14 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage14_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage15;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage14;
                end if;
            when ap_ST_fsm_pp0_stage15 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage15_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage16;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage15;
                end if;
            when ap_ST_fsm_pp0_stage16 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage16_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage17;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage16;
                end if;
            when ap_ST_fsm_pp0_stage17 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage17_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage18;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage17;
                end if;
            when ap_ST_fsm_pp0_stage18 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage18_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage19;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage18;
                end if;
            when ap_ST_fsm_pp0_stage19 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage19_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage20;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage19;
                end if;
            when ap_ST_fsm_pp0_stage20 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage20_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage21;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage20;
                end if;
            when ap_ST_fsm_pp0_stage21 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage21_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage22;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage21;
                end if;
            when ap_ST_fsm_pp0_stage22 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage22_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage23;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage22;
                end if;
            when ap_ST_fsm_pp0_stage23 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage23_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage24;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage23;
                end if;
            when ap_ST_fsm_pp0_stage24 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage24_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage25;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage24;
                end if;
            when ap_ST_fsm_pp0_stage25 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage25_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage25;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXXXXXXXXXXXXXXX";
        end case;
    end process;
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(1);
    ap_CS_fsm_pp0_stage25 <= ap_CS_fsm(25);

    ap_block_pp0_stage0_01001_grp30_assign_proc : process(ap_enable_reg_pp0_iter1, scalar_partition_stream_full_n)
    begin
                ap_block_pp0_stage0_01001_grp30 <= ((scalar_partition_stream_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, scalar_partition_stream_full_n)
    begin
                ap_block_pp0_stage0_11001 <= ((scalar_partition_stream_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_11001_grp30_assign_proc : process(ap_enable_reg_pp0_iter1, scalar_partition_stream_full_n)
    begin
                ap_block_pp0_stage0_11001_grp30 <= ((scalar_partition_stream_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;

        ap_block_pp0_stage0_grp30 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, scalar_partition_stream_full_n)
    begin
                ap_block_pp0_stage0_subdone <= ((scalar_partition_stream_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage10_01001_grp14_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state11_pp0_stage10_iter0_grp14)
    begin
                ap_block_pp0_stage10_01001_grp14 <= ((ap_const_boolean_1 = ap_block_state11_pp0_stage10_iter0_grp14) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1));
    end process;


    ap_block_pp0_stage10_11001_grp14_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state11_pp0_stage10_iter0_grp14)
    begin
                ap_block_pp0_stage10_11001_grp14 <= ((ap_const_boolean_1 = ap_block_state11_pp0_stage10_iter0_grp14) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1));
    end process;

        ap_block_pp0_stage10_grp14 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage10_subdone_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state11_pp0_stage10_iter0_grp14)
    begin
                ap_block_pp0_stage10_subdone <= ((ap_const_boolean_1 = ap_block_state11_pp0_stage10_iter0_grp14) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1));
    end process;


    ap_block_pp0_stage11_01001_grp15_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state12_pp0_stage11_iter0_grp15)
    begin
                ap_block_pp0_stage11_01001_grp15 <= ((ap_const_boolean_1 = ap_block_state12_pp0_stage11_iter0_grp15) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1));
    end process;


    ap_block_pp0_stage11_11001_grp15_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state12_pp0_stage11_iter0_grp15)
    begin
                ap_block_pp0_stage11_11001_grp15 <= ((ap_const_boolean_1 = ap_block_state12_pp0_stage11_iter0_grp15) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1));
    end process;

        ap_block_pp0_stage11_grp15 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage11_subdone_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state12_pp0_stage11_iter0_grp15)
    begin
                ap_block_pp0_stage11_subdone <= ((ap_const_boolean_1 = ap_block_state12_pp0_stage11_iter0_grp15) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1));
    end process;


    ap_block_pp0_stage12_01001_grp16_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state13_pp0_stage12_iter0_grp16)
    begin
                ap_block_pp0_stage12_01001_grp16 <= ((ap_const_boolean_1 = ap_block_state13_pp0_stage12_iter0_grp16) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1));
    end process;


    ap_block_pp0_stage12_11001_grp16_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state13_pp0_stage12_iter0_grp16)
    begin
                ap_block_pp0_stage12_11001_grp16 <= ((ap_const_boolean_1 = ap_block_state13_pp0_stage12_iter0_grp16) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1));
    end process;

        ap_block_pp0_stage12_grp16 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage12_subdone_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state13_pp0_stage12_iter0_grp16)
    begin
                ap_block_pp0_stage12_subdone <= ((ap_const_boolean_1 = ap_block_state13_pp0_stage12_iter0_grp16) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1));
    end process;


    ap_block_pp0_stage13_01001_grp17_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state14_pp0_stage13_iter0_grp17)
    begin
                ap_block_pp0_stage13_01001_grp17 <= ((ap_const_boolean_1 = ap_block_state14_pp0_stage13_iter0_grp17) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1));
    end process;


    ap_block_pp0_stage13_11001_grp17_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state14_pp0_stage13_iter0_grp17)
    begin
                ap_block_pp0_stage13_11001_grp17 <= ((ap_const_boolean_1 = ap_block_state14_pp0_stage13_iter0_grp17) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1));
    end process;

        ap_block_pp0_stage13_grp17 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage13_subdone_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state14_pp0_stage13_iter0_grp17)
    begin
                ap_block_pp0_stage13_subdone <= ((ap_const_boolean_1 = ap_block_state14_pp0_stage13_iter0_grp17) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1));
    end process;


    ap_block_pp0_stage14_01001_grp18_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state15_pp0_stage14_iter0_grp18)
    begin
                ap_block_pp0_stage14_01001_grp18 <= ((ap_const_boolean_1 = ap_block_state15_pp0_stage14_iter0_grp18) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1));
    end process;


    ap_block_pp0_stage14_11001_grp18_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state15_pp0_stage14_iter0_grp18)
    begin
                ap_block_pp0_stage14_11001_grp18 <= ((ap_const_boolean_1 = ap_block_state15_pp0_stage14_iter0_grp18) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1));
    end process;

        ap_block_pp0_stage14_grp18 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage14_subdone_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state15_pp0_stage14_iter0_grp18)
    begin
                ap_block_pp0_stage14_subdone <= ((ap_const_boolean_1 = ap_block_state15_pp0_stage14_iter0_grp18) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1));
    end process;


    ap_block_pp0_stage15_01001_grp19_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state16_pp0_stage15_iter0_grp19)
    begin
                ap_block_pp0_stage15_01001_grp19 <= ((ap_const_boolean_1 = ap_block_state16_pp0_stage15_iter0_grp19) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1));
    end process;


    ap_block_pp0_stage15_11001_grp19_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state16_pp0_stage15_iter0_grp19)
    begin
                ap_block_pp0_stage15_11001_grp19 <= ((ap_const_boolean_1 = ap_block_state16_pp0_stage15_iter0_grp19) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1));
    end process;

        ap_block_pp0_stage15_grp19 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage15_subdone_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state16_pp0_stage15_iter0_grp19)
    begin
                ap_block_pp0_stage15_subdone <= ((ap_const_boolean_1 = ap_block_state16_pp0_stage15_iter0_grp19) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1));
    end process;


    ap_block_pp0_stage16_01001_grp20_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state17_pp0_stage16_iter0_grp20)
    begin
                ap_block_pp0_stage16_01001_grp20 <= ((ap_const_boolean_1 = ap_block_state17_pp0_stage16_iter0_grp20) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1));
    end process;


    ap_block_pp0_stage16_11001_grp20_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state17_pp0_stage16_iter0_grp20)
    begin
                ap_block_pp0_stage16_11001_grp20 <= ((ap_const_boolean_1 = ap_block_state17_pp0_stage16_iter0_grp20) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1));
    end process;

        ap_block_pp0_stage16_grp20 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage16_subdone_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state17_pp0_stage16_iter0_grp20)
    begin
                ap_block_pp0_stage16_subdone <= ((ap_const_boolean_1 = ap_block_state17_pp0_stage16_iter0_grp20) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1));
    end process;


    ap_block_pp0_stage17_01001_grp21_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state18_pp0_stage17_iter0_grp21)
    begin
                ap_block_pp0_stage17_01001_grp21 <= ((ap_const_boolean_1 = ap_block_state18_pp0_stage17_iter0_grp21) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1));
    end process;


    ap_block_pp0_stage17_11001_grp21_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state18_pp0_stage17_iter0_grp21)
    begin
                ap_block_pp0_stage17_11001_grp21 <= ((ap_const_boolean_1 = ap_block_state18_pp0_stage17_iter0_grp21) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1));
    end process;

        ap_block_pp0_stage17_grp21 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage17_subdone_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state18_pp0_stage17_iter0_grp21)
    begin
                ap_block_pp0_stage17_subdone <= ((ap_const_boolean_1 = ap_block_state18_pp0_stage17_iter0_grp21) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1));
    end process;


    ap_block_pp0_stage18_01001_grp22_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state19_pp0_stage18_iter0_grp22)
    begin
                ap_block_pp0_stage18_01001_grp22 <= ((ap_const_boolean_1 = ap_block_state19_pp0_stage18_iter0_grp22) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1));
    end process;


    ap_block_pp0_stage18_11001_grp22_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state19_pp0_stage18_iter0_grp22)
    begin
                ap_block_pp0_stage18_11001_grp22 <= ((ap_const_boolean_1 = ap_block_state19_pp0_stage18_iter0_grp22) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1));
    end process;

        ap_block_pp0_stage18_grp22 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage18_subdone_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state19_pp0_stage18_iter0_grp22)
    begin
                ap_block_pp0_stage18_subdone <= ((ap_const_boolean_1 = ap_block_state19_pp0_stage18_iter0_grp22) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1));
    end process;


    ap_block_pp0_stage19_01001_grp23_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state20_pp0_stage19_iter0_grp23)
    begin
                ap_block_pp0_stage19_01001_grp23 <= ((ap_const_boolean_1 = ap_block_state20_pp0_stage19_iter0_grp23) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1));
    end process;


    ap_block_pp0_stage19_11001_grp23_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state20_pp0_stage19_iter0_grp23)
    begin
                ap_block_pp0_stage19_11001_grp23 <= ((ap_const_boolean_1 = ap_block_state20_pp0_stage19_iter0_grp23) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1));
    end process;

        ap_block_pp0_stage19_grp23 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage19_subdone_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state20_pp0_stage19_iter0_grp23)
    begin
                ap_block_pp0_stage19_subdone <= ((ap_const_boolean_1 = ap_block_state20_pp0_stage19_iter0_grp23) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1));
    end process;


    ap_block_pp0_stage1_01001_grp5_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_pp0_stage1_subdone_grp5_done_reg, ap_block_state2_pp0_stage1_iter0_grp5)
    begin
                ap_block_pp0_stage1_01001_grp5 <= ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp5_done_reg) and (ap_const_boolean_1 = ap_block_state2_pp0_stage1_iter0_grp5) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1));
    end process;


    ap_block_pp0_stage1_11001_grp1_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_pp0_stage1_subdone_grp1_done_reg, ap_block_state2_pp0_stage1_iter0_grp1)
    begin
                ap_block_pp0_stage1_11001_grp1 <= ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp1_done_reg) and (ap_const_boolean_1 = ap_block_state2_pp0_stage1_iter0_grp1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1));
    end process;


    ap_block_pp0_stage1_11001_grp2_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_pp0_stage1_subdone_grp2_done_reg, ap_block_state2_pp0_stage1_iter0_grp2)
    begin
                ap_block_pp0_stage1_11001_grp2 <= ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp2_done_reg) and (ap_const_boolean_1 = ap_block_state2_pp0_stage1_iter0_grp2) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1));
    end process;


    ap_block_pp0_stage1_11001_grp3_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_pp0_stage1_subdone_grp3_done_reg, ap_block_state2_pp0_stage1_iter0_grp3)
    begin
                ap_block_pp0_stage1_11001_grp3 <= ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp3_done_reg) and (ap_const_boolean_1 = ap_block_state2_pp0_stage1_iter0_grp3) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1));
    end process;


    ap_block_pp0_stage1_11001_grp4_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_pp0_stage1_subdone_grp4_done_reg, ap_block_state2_pp0_stage1_iter0_grp4)
    begin
                ap_block_pp0_stage1_11001_grp4 <= ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp4_done_reg) and (ap_const_boolean_1 = ap_block_state2_pp0_stage1_iter0_grp4) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1));
    end process;


    ap_block_pp0_stage1_11001_grp5_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_pp0_stage1_subdone_grp5_done_reg, ap_block_state2_pp0_stage1_iter0_grp5)
    begin
                ap_block_pp0_stage1_11001_grp5 <= ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp5_done_reg) and (ap_const_boolean_1 = ap_block_state2_pp0_stage1_iter0_grp5) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1));
    end process;

        ap_block_pp0_stage1_grp1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_grp2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_grp3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_grp4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_grp5 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage1_subdone_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_pp0_stage1_subdone_grp1_done_reg, ap_block_pp0_stage1_subdone_grp2_done_reg, ap_block_pp0_stage1_subdone_grp3_done_reg, ap_block_pp0_stage1_subdone_grp4_done_reg, ap_block_pp0_stage1_subdone_grp5_done_reg, ap_block_state2_pp0_stage1_iter0_grp5, ap_block_state2_pp0_stage1_iter0_grp1, ap_block_state2_pp0_stage1_iter0_grp2, ap_block_state2_pp0_stage1_iter0_grp3, ap_block_state2_pp0_stage1_iter0_grp4)
    begin
                ap_block_pp0_stage1_subdone <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp5_done_reg) and (ap_const_boolean_1 = ap_block_state2_pp0_stage1_iter0_grp5)) or ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp4_done_reg) and (ap_const_boolean_1 = ap_block_state2_pp0_stage1_iter0_grp4)) or ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp3_done_reg) and (ap_const_boolean_1 = ap_block_state2_pp0_stage1_iter0_grp3)) or ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp2_done_reg) and (ap_const_boolean_1 = ap_block_state2_pp0_stage1_iter0_grp2)) or ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp1_done_reg) and (ap_const_boolean_1 = ap_block_state2_pp0_stage1_iter0_grp1))));
    end process;


    ap_block_pp0_stage1_subdone_grp1_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_pp0_stage1_subdone_grp1_done_reg, ap_block_state2_pp0_stage1_iter0_grp1)
    begin
                ap_block_pp0_stage1_subdone_grp1 <= ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp1_done_reg) and (ap_const_boolean_1 = ap_block_state2_pp0_stage1_iter0_grp1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1));
    end process;


    ap_block_pp0_stage1_subdone_grp2_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_pp0_stage1_subdone_grp2_done_reg, ap_block_state2_pp0_stage1_iter0_grp2)
    begin
                ap_block_pp0_stage1_subdone_grp2 <= ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp2_done_reg) and (ap_const_boolean_1 = ap_block_state2_pp0_stage1_iter0_grp2) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1));
    end process;


    ap_block_pp0_stage1_subdone_grp3_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_pp0_stage1_subdone_grp3_done_reg, ap_block_state2_pp0_stage1_iter0_grp3)
    begin
                ap_block_pp0_stage1_subdone_grp3 <= ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp3_done_reg) and (ap_const_boolean_1 = ap_block_state2_pp0_stage1_iter0_grp3) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1));
    end process;


    ap_block_pp0_stage1_subdone_grp4_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_pp0_stage1_subdone_grp4_done_reg, ap_block_state2_pp0_stage1_iter0_grp4)
    begin
                ap_block_pp0_stage1_subdone_grp4 <= ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp4_done_reg) and (ap_const_boolean_1 = ap_block_state2_pp0_stage1_iter0_grp4) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1));
    end process;


    ap_block_pp0_stage1_subdone_grp5_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_pp0_stage1_subdone_grp5_done_reg, ap_block_state2_pp0_stage1_iter0_grp5)
    begin
                ap_block_pp0_stage1_subdone_grp5 <= ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp5_done_reg) and (ap_const_boolean_1 = ap_block_state2_pp0_stage1_iter0_grp5) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1));
    end process;


    ap_block_pp0_stage20_01001_grp24_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state21_pp0_stage20_iter0_grp24)
    begin
                ap_block_pp0_stage20_01001_grp24 <= ((ap_const_boolean_1 = ap_block_state21_pp0_stage20_iter0_grp24) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1));
    end process;


    ap_block_pp0_stage20_11001_grp24_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state21_pp0_stage20_iter0_grp24)
    begin
                ap_block_pp0_stage20_11001_grp24 <= ((ap_const_boolean_1 = ap_block_state21_pp0_stage20_iter0_grp24) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1));
    end process;

        ap_block_pp0_stage20_grp24 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage20_subdone_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state21_pp0_stage20_iter0_grp24)
    begin
                ap_block_pp0_stage20_subdone <= ((ap_const_boolean_1 = ap_block_state21_pp0_stage20_iter0_grp24) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1));
    end process;


    ap_block_pp0_stage21_01001_grp25_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state22_pp0_stage21_iter0_grp25)
    begin
                ap_block_pp0_stage21_01001_grp25 <= ((ap_const_boolean_1 = ap_block_state22_pp0_stage21_iter0_grp25) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1));
    end process;


    ap_block_pp0_stage21_11001_grp25_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state22_pp0_stage21_iter0_grp25)
    begin
                ap_block_pp0_stage21_11001_grp25 <= ((ap_const_boolean_1 = ap_block_state22_pp0_stage21_iter0_grp25) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1));
    end process;

        ap_block_pp0_stage21_grp25 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage21_subdone_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state22_pp0_stage21_iter0_grp25)
    begin
                ap_block_pp0_stage21_subdone <= ((ap_const_boolean_1 = ap_block_state22_pp0_stage21_iter0_grp25) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1));
    end process;


    ap_block_pp0_stage22_01001_grp26_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state23_pp0_stage22_iter0_grp26)
    begin
                ap_block_pp0_stage22_01001_grp26 <= ((ap_const_boolean_1 = ap_block_state23_pp0_stage22_iter0_grp26) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1));
    end process;


    ap_block_pp0_stage22_11001_grp26_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state23_pp0_stage22_iter0_grp26)
    begin
                ap_block_pp0_stage22_11001_grp26 <= ((ap_const_boolean_1 = ap_block_state23_pp0_stage22_iter0_grp26) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1));
    end process;

        ap_block_pp0_stage22_grp26 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage22_subdone_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state23_pp0_stage22_iter0_grp26)
    begin
                ap_block_pp0_stage22_subdone <= ((ap_const_boolean_1 = ap_block_state23_pp0_stage22_iter0_grp26) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1));
    end process;


    ap_block_pp0_stage23_01001_grp27_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state24_pp0_stage23_iter0_grp27)
    begin
                ap_block_pp0_stage23_01001_grp27 <= ((ap_const_boolean_1 = ap_block_state24_pp0_stage23_iter0_grp27) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1));
    end process;


    ap_block_pp0_stage23_11001_grp27_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state24_pp0_stage23_iter0_grp27)
    begin
                ap_block_pp0_stage23_11001_grp27 <= ((ap_const_boolean_1 = ap_block_state24_pp0_stage23_iter0_grp27) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1));
    end process;

        ap_block_pp0_stage23_grp27 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage23_subdone_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state24_pp0_stage23_iter0_grp27)
    begin
                ap_block_pp0_stage23_subdone <= ((ap_const_boolean_1 = ap_block_state24_pp0_stage23_iter0_grp27) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1));
    end process;


    ap_block_pp0_stage24_01001_grp28_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state25_pp0_stage24_iter0_grp28)
    begin
                ap_block_pp0_stage24_01001_grp28 <= ((ap_const_boolean_1 = ap_block_state25_pp0_stage24_iter0_grp28) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1));
    end process;


    ap_block_pp0_stage24_11001_grp28_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state25_pp0_stage24_iter0_grp28)
    begin
                ap_block_pp0_stage24_11001_grp28 <= ((ap_const_boolean_1 = ap_block_state25_pp0_stage24_iter0_grp28) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1));
    end process;

        ap_block_pp0_stage24_grp28 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage24_subdone_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state25_pp0_stage24_iter0_grp28)
    begin
                ap_block_pp0_stage24_subdone <= ((ap_const_boolean_1 = ap_block_state25_pp0_stage24_iter0_grp28) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1));
    end process;


    ap_block_pp0_stage25_01001_grp29_assign_proc : process(ap_block_state26_pp0_stage25_iter0_grp29, ap_enable_reg_pp0_iter0_reg)
    begin
                ap_block_pp0_stage25_01001_grp29 <= ((ap_const_boolean_1 = ap_block_state26_pp0_stage25_iter0_grp29) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1));
    end process;


    ap_block_pp0_stage25_11001_grp29_assign_proc : process(ap_block_state26_pp0_stage25_iter0_grp29, ap_enable_reg_pp0_iter0_reg)
    begin
                ap_block_pp0_stage25_11001_grp29 <= ((ap_const_boolean_1 = ap_block_state26_pp0_stage25_iter0_grp29) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1));
    end process;

        ap_block_pp0_stage25_grp29 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage25_subdone_assign_proc : process(ap_block_state26_pp0_stage25_iter0_grp29, ap_enable_reg_pp0_iter0_reg)
    begin
                ap_block_pp0_stage25_subdone <= ((ap_const_boolean_1 = ap_block_state26_pp0_stage25_iter0_grp29) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1));
    end process;


    ap_block_pp0_stage2_01001_grp6_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state3_pp0_stage2_iter0_grp6)
    begin
                ap_block_pp0_stage2_01001_grp6 <= ((ap_const_boolean_1 = ap_block_state3_pp0_stage2_iter0_grp6) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1));
    end process;


    ap_block_pp0_stage2_11001_grp6_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state3_pp0_stage2_iter0_grp6)
    begin
                ap_block_pp0_stage2_11001_grp6 <= ((ap_const_boolean_1 = ap_block_state3_pp0_stage2_iter0_grp6) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1));
    end process;

        ap_block_pp0_stage2_grp6 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage2_subdone_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state3_pp0_stage2_iter0_grp6)
    begin
                ap_block_pp0_stage2_subdone <= ((ap_const_boolean_1 = ap_block_state3_pp0_stage2_iter0_grp6) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1));
    end process;


    ap_block_pp0_stage3_01001_grp7_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state4_pp0_stage3_iter0_grp7)
    begin
                ap_block_pp0_stage3_01001_grp7 <= ((ap_const_boolean_1 = ap_block_state4_pp0_stage3_iter0_grp7) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1));
    end process;


    ap_block_pp0_stage3_11001_grp7_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state4_pp0_stage3_iter0_grp7)
    begin
                ap_block_pp0_stage3_11001_grp7 <= ((ap_const_boolean_1 = ap_block_state4_pp0_stage3_iter0_grp7) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1));
    end process;

        ap_block_pp0_stage3_grp7 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage3_subdone_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state4_pp0_stage3_iter0_grp7)
    begin
                ap_block_pp0_stage3_subdone <= ((ap_const_boolean_1 = ap_block_state4_pp0_stage3_iter0_grp7) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1));
    end process;


    ap_block_pp0_stage4_01001_grp8_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state5_pp0_stage4_iter0_grp8)
    begin
                ap_block_pp0_stage4_01001_grp8 <= ((ap_const_boolean_1 = ap_block_state5_pp0_stage4_iter0_grp8) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1));
    end process;


    ap_block_pp0_stage4_11001_grp8_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state5_pp0_stage4_iter0_grp8)
    begin
                ap_block_pp0_stage4_11001_grp8 <= ((ap_const_boolean_1 = ap_block_state5_pp0_stage4_iter0_grp8) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1));
    end process;

        ap_block_pp0_stage4_grp8 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage4_subdone_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state5_pp0_stage4_iter0_grp8)
    begin
                ap_block_pp0_stage4_subdone <= ((ap_const_boolean_1 = ap_block_state5_pp0_stage4_iter0_grp8) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1));
    end process;


    ap_block_pp0_stage5_01001_grp9_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state6_pp0_stage5_iter0_grp9)
    begin
                ap_block_pp0_stage5_01001_grp9 <= ((ap_const_boolean_1 = ap_block_state6_pp0_stage5_iter0_grp9) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1));
    end process;


    ap_block_pp0_stage5_11001_grp9_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state6_pp0_stage5_iter0_grp9)
    begin
                ap_block_pp0_stage5_11001_grp9 <= ((ap_const_boolean_1 = ap_block_state6_pp0_stage5_iter0_grp9) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1));
    end process;

        ap_block_pp0_stage5_grp9 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage5_subdone_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state6_pp0_stage5_iter0_grp9)
    begin
                ap_block_pp0_stage5_subdone <= ((ap_const_boolean_1 = ap_block_state6_pp0_stage5_iter0_grp9) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1));
    end process;


    ap_block_pp0_stage6_01001_grp10_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state7_pp0_stage6_iter0_grp10)
    begin
                ap_block_pp0_stage6_01001_grp10 <= ((ap_const_boolean_1 = ap_block_state7_pp0_stage6_iter0_grp10) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1));
    end process;


    ap_block_pp0_stage6_11001_grp10_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state7_pp0_stage6_iter0_grp10)
    begin
                ap_block_pp0_stage6_11001_grp10 <= ((ap_const_boolean_1 = ap_block_state7_pp0_stage6_iter0_grp10) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1));
    end process;

        ap_block_pp0_stage6_grp10 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage6_subdone_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state7_pp0_stage6_iter0_grp10)
    begin
                ap_block_pp0_stage6_subdone <= ((ap_const_boolean_1 = ap_block_state7_pp0_stage6_iter0_grp10) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1));
    end process;


    ap_block_pp0_stage7_01001_grp11_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state8_pp0_stage7_iter0_grp11)
    begin
                ap_block_pp0_stage7_01001_grp11 <= ((ap_const_boolean_1 = ap_block_state8_pp0_stage7_iter0_grp11) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1));
    end process;


    ap_block_pp0_stage7_11001_grp11_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state8_pp0_stage7_iter0_grp11)
    begin
                ap_block_pp0_stage7_11001_grp11 <= ((ap_const_boolean_1 = ap_block_state8_pp0_stage7_iter0_grp11) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1));
    end process;

        ap_block_pp0_stage7_grp11 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage7_subdone_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state8_pp0_stage7_iter0_grp11)
    begin
                ap_block_pp0_stage7_subdone <= ((ap_const_boolean_1 = ap_block_state8_pp0_stage7_iter0_grp11) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1));
    end process;


    ap_block_pp0_stage8_01001_grp12_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state9_pp0_stage8_iter0_grp12)
    begin
                ap_block_pp0_stage8_01001_grp12 <= ((ap_const_boolean_1 = ap_block_state9_pp0_stage8_iter0_grp12) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1));
    end process;


    ap_block_pp0_stage8_11001_grp12_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state9_pp0_stage8_iter0_grp12)
    begin
                ap_block_pp0_stage8_11001_grp12 <= ((ap_const_boolean_1 = ap_block_state9_pp0_stage8_iter0_grp12) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1));
    end process;

        ap_block_pp0_stage8_grp12 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage8_subdone_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state9_pp0_stage8_iter0_grp12)
    begin
                ap_block_pp0_stage8_subdone <= ((ap_const_boolean_1 = ap_block_state9_pp0_stage8_iter0_grp12) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1));
    end process;


    ap_block_pp0_stage9_01001_grp13_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state10_pp0_stage9_iter0_grp13)
    begin
                ap_block_pp0_stage9_01001_grp13 <= ((ap_const_boolean_1 = ap_block_state10_pp0_stage9_iter0_grp13) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1));
    end process;


    ap_block_pp0_stage9_11001_grp13_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state10_pp0_stage9_iter0_grp13)
    begin
                ap_block_pp0_stage9_11001_grp13 <= ((ap_const_boolean_1 = ap_block_state10_pp0_stage9_iter0_grp13) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1));
    end process;

        ap_block_pp0_stage9_grp13 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage9_subdone_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state10_pp0_stage9_iter0_grp13)
    begin
                ap_block_pp0_stage9_subdone <= ((ap_const_boolean_1 = ap_block_state10_pp0_stage9_iter0_grp13) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1));
    end process;


    ap_block_state10_pp0_stage9_iter0_grp13_assign_proc : process(scalar_partition_stream_full_n, tmp_reg_558)
    begin
                ap_block_state10_pp0_stage9_iter0_grp13 <= ((scalar_partition_stream_full_n = ap_const_logic_0) and (tmp_reg_558 = ap_const_lv1_1));
    end process;


    ap_block_state11_pp0_stage10_iter0_grp14_assign_proc : process(scalar_partition_stream_full_n, tmp_reg_558)
    begin
                ap_block_state11_pp0_stage10_iter0_grp14 <= ((scalar_partition_stream_full_n = ap_const_logic_0) and (tmp_reg_558 = ap_const_lv1_1));
    end process;


    ap_block_state12_pp0_stage11_iter0_grp15_assign_proc : process(scalar_partition_stream_full_n, tmp_reg_558)
    begin
                ap_block_state12_pp0_stage11_iter0_grp15 <= ((scalar_partition_stream_full_n = ap_const_logic_0) and (tmp_reg_558 = ap_const_lv1_1));
    end process;


    ap_block_state13_pp0_stage12_iter0_grp16_assign_proc : process(scalar_partition_stream_full_n, tmp_reg_558)
    begin
                ap_block_state13_pp0_stage12_iter0_grp16 <= ((scalar_partition_stream_full_n = ap_const_logic_0) and (tmp_reg_558 = ap_const_lv1_1));
    end process;


    ap_block_state14_pp0_stage13_iter0_grp17_assign_proc : process(scalar_partition_stream_full_n, tmp_reg_558)
    begin
                ap_block_state14_pp0_stage13_iter0_grp17 <= ((scalar_partition_stream_full_n = ap_const_logic_0) and (tmp_reg_558 = ap_const_lv1_1));
    end process;


    ap_block_state15_pp0_stage14_iter0_grp18_assign_proc : process(scalar_partition_stream_full_n, tmp_reg_558)
    begin
                ap_block_state15_pp0_stage14_iter0_grp18 <= ((scalar_partition_stream_full_n = ap_const_logic_0) and (tmp_reg_558 = ap_const_lv1_1));
    end process;


    ap_block_state16_pp0_stage15_iter0_grp19_assign_proc : process(scalar_partition_stream_full_n, tmp_reg_558)
    begin
                ap_block_state16_pp0_stage15_iter0_grp19 <= ((scalar_partition_stream_full_n = ap_const_logic_0) and (tmp_reg_558 = ap_const_lv1_1));
    end process;


    ap_block_state17_pp0_stage16_iter0_grp20_assign_proc : process(scalar_partition_stream_full_n, tmp_reg_558)
    begin
                ap_block_state17_pp0_stage16_iter0_grp20 <= ((scalar_partition_stream_full_n = ap_const_logic_0) and (tmp_reg_558 = ap_const_lv1_1));
    end process;


    ap_block_state18_pp0_stage17_iter0_grp21_assign_proc : process(scalar_partition_stream_full_n, tmp_reg_558)
    begin
                ap_block_state18_pp0_stage17_iter0_grp21 <= ((scalar_partition_stream_full_n = ap_const_logic_0) and (tmp_reg_558 = ap_const_lv1_1));
    end process;


    ap_block_state19_pp0_stage18_iter0_grp22_assign_proc : process(scalar_partition_stream_full_n, tmp_reg_558)
    begin
                ap_block_state19_pp0_stage18_iter0_grp22 <= ((scalar_partition_stream_full_n = ap_const_logic_0) and (tmp_reg_558 = ap_const_lv1_1));
    end process;


    ap_block_state20_pp0_stage19_iter0_grp23_assign_proc : process(scalar_partition_stream_full_n, tmp_reg_558)
    begin
                ap_block_state20_pp0_stage19_iter0_grp23 <= ((scalar_partition_stream_full_n = ap_const_logic_0) and (tmp_reg_558 = ap_const_lv1_1));
    end process;


    ap_block_state21_pp0_stage20_iter0_grp24_assign_proc : process(scalar_partition_stream_full_n, tmp_reg_558)
    begin
                ap_block_state21_pp0_stage20_iter0_grp24 <= ((scalar_partition_stream_full_n = ap_const_logic_0) and (tmp_reg_558 = ap_const_lv1_1));
    end process;


    ap_block_state22_pp0_stage21_iter0_grp25_assign_proc : process(scalar_partition_stream_full_n, tmp_reg_558)
    begin
                ap_block_state22_pp0_stage21_iter0_grp25 <= ((scalar_partition_stream_full_n = ap_const_logic_0) and (tmp_reg_558 = ap_const_lv1_1));
    end process;


    ap_block_state23_pp0_stage22_iter0_grp26_assign_proc : process(scalar_partition_stream_full_n, tmp_reg_558)
    begin
                ap_block_state23_pp0_stage22_iter0_grp26 <= ((scalar_partition_stream_full_n = ap_const_logic_0) and (tmp_reg_558 = ap_const_lv1_1));
    end process;


    ap_block_state24_pp0_stage23_iter0_grp27_assign_proc : process(scalar_partition_stream_full_n, tmp_reg_558)
    begin
                ap_block_state24_pp0_stage23_iter0_grp27 <= ((scalar_partition_stream_full_n = ap_const_logic_0) and (tmp_reg_558 = ap_const_lv1_1));
    end process;


    ap_block_state25_pp0_stage24_iter0_grp28_assign_proc : process(scalar_partition_stream_full_n, tmp_reg_558)
    begin
                ap_block_state25_pp0_stage24_iter0_grp28 <= ((scalar_partition_stream_full_n = ap_const_logic_0) and (tmp_reg_558 = ap_const_lv1_1));
    end process;


    ap_block_state26_pp0_stage25_iter0_grp29_assign_proc : process(scalar_partition_stream_full_n, tmp_reg_558)
    begin
                ap_block_state26_pp0_stage25_iter0_grp29 <= ((scalar_partition_stream_full_n = ap_const_logic_0) and (tmp_reg_558 = ap_const_lv1_1));
    end process;


    ap_block_state2_pp0_stage1_iter0_grp1_assign_proc : process(x_stream_empty_n, tmp_reg_558)
    begin
                ap_block_state2_pp0_stage1_iter0_grp1 <= ((x_stream_empty_n = ap_const_logic_0) and (tmp_reg_558 = ap_const_lv1_1));
    end process;


    ap_block_state2_pp0_stage1_iter0_grp2_assign_proc : process(y_stream_empty_n, tmp_reg_558)
    begin
                ap_block_state2_pp0_stage1_iter0_grp2 <= ((y_stream_empty_n = ap_const_logic_0) and (tmp_reg_558 = ap_const_lv1_1));
    end process;


    ap_block_state2_pp0_stage1_iter0_grp3_assign_proc : process(z_stream_empty_n, tmp_reg_558)
    begin
                ap_block_state2_pp0_stage1_iter0_grp3 <= ((z_stream_empty_n = ap_const_logic_0) and (tmp_reg_558 = ap_const_lv1_1));
    end process;


    ap_block_state2_pp0_stage1_iter0_grp4_assign_proc : process(t_stream_empty_n, tmp_reg_558)
    begin
                ap_block_state2_pp0_stage1_iter0_grp4 <= ((t_stream_empty_n = ap_const_logic_0) and (tmp_reg_558 = ap_const_lv1_1));
    end process;


    ap_block_state2_pp0_stage1_iter0_grp5_assign_proc : process(scalar_partition_stream_full_n, scalar_stream_empty_n, tmp_reg_558)
    begin
                ap_block_state2_pp0_stage1_iter0_grp5 <= (((scalar_partition_stream_full_n = ap_const_logic_0) and (tmp_reg_558 = ap_const_lv1_1)) or ((scalar_stream_empty_n = ap_const_logic_0) and (tmp_reg_558 = ap_const_lv1_1)));
    end process;


    ap_block_state3_pp0_stage2_iter0_grp6_assign_proc : process(scalar_partition_stream_full_n, tmp_reg_558)
    begin
                ap_block_state3_pp0_stage2_iter0_grp6 <= ((scalar_partition_stream_full_n = ap_const_logic_0) and (tmp_reg_558 = ap_const_lv1_1));
    end process;


    ap_block_state4_pp0_stage3_iter0_grp7_assign_proc : process(scalar_partition_stream_full_n, tmp_reg_558)
    begin
                ap_block_state4_pp0_stage3_iter0_grp7 <= ((scalar_partition_stream_full_n = ap_const_logic_0) and (tmp_reg_558 = ap_const_lv1_1));
    end process;


    ap_block_state5_pp0_stage4_iter0_grp8_assign_proc : process(scalar_partition_stream_full_n, tmp_reg_558)
    begin
                ap_block_state5_pp0_stage4_iter0_grp8 <= ((scalar_partition_stream_full_n = ap_const_logic_0) and (tmp_reg_558 = ap_const_lv1_1));
    end process;


    ap_block_state6_pp0_stage5_iter0_grp9_assign_proc : process(scalar_partition_stream_full_n, tmp_reg_558)
    begin
                ap_block_state6_pp0_stage5_iter0_grp9 <= ((scalar_partition_stream_full_n = ap_const_logic_0) and (tmp_reg_558 = ap_const_lv1_1));
    end process;


    ap_block_state7_pp0_stage6_iter0_grp10_assign_proc : process(scalar_partition_stream_full_n, tmp_reg_558)
    begin
                ap_block_state7_pp0_stage6_iter0_grp10 <= ((scalar_partition_stream_full_n = ap_const_logic_0) and (tmp_reg_558 = ap_const_lv1_1));
    end process;


    ap_block_state8_pp0_stage7_iter0_grp11_assign_proc : process(scalar_partition_stream_full_n, tmp_reg_558)
    begin
                ap_block_state8_pp0_stage7_iter0_grp11 <= ((scalar_partition_stream_full_n = ap_const_logic_0) and (tmp_reg_558 = ap_const_lv1_1));
    end process;


    ap_block_state9_pp0_stage8_iter0_grp12_assign_proc : process(scalar_partition_stream_full_n, tmp_reg_558)
    begin
                ap_block_state9_pp0_stage8_iter0_grp12 <= ((scalar_partition_stream_full_n = ap_const_logic_0) and (tmp_reg_558 = ap_const_lv1_1));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, tmp_nbreadreq_fu_150_p3)
    begin
        if (((tmp_nbreadreq_fu_150_p3 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_enable_reg_pp0_iter0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0_reg, ap_start_int)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
            ap_enable_reg_pp0_iter0 <= ap_start_int;
        else 
            ap_enable_reg_pp0_iter0 <= ap_enable_reg_pp0_iter0_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_start_int = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_1to1_assign_proc : process(ap_enable_reg_pp0_iter1)
    begin
        if ((ap_enable_reg_pp0_iter1 = ap_const_logic_0)) then 
            ap_idle_pp0_1to1 <= ap_const_logic_1;
        else 
            ap_idle_pp0_1to1 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage25, ap_enable_reg_pp0_iter0_reg, ap_block_pp0_stage25_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage25_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage25) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;

    scalar_partition_stream_full_n <= ap_const_logic_1;

    scalar_stream_blk_n_assign_proc : process(scalar_stream_empty_n, tmp_reg_558, ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_grp5, ap_block_pp0_stage1_subdone_grp5_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp5_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage1_grp5) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (tmp_reg_558 = ap_const_lv1_1))) then 
            scalar_stream_blk_n <= scalar_stream_empty_n;
        else 
            scalar_stream_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    scalar_stream_read_assign_proc : process(tmp_reg_558, ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone_grp5_done_reg, ap_block_pp0_stage1_11001_grp5)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001_grp5) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp5_done_reg) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (tmp_reg_558 = ap_const_lv1_1))) then 
            scalar_stream_read <= ap_const_logic_1;
        else 
            scalar_stream_read <= ap_const_logic_0;
        end if; 
    end process;


    t_stream_blk_n_assign_proc : process(t_stream_empty_n, tmp_reg_558, ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_grp4, ap_block_pp0_stage1_subdone_grp4_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp4_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage1_grp4) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (tmp_reg_558 = ap_const_lv1_1))) then 
            t_stream_blk_n <= t_stream_empty_n;
        else 
            t_stream_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    t_stream_read_assign_proc : process(tmp_reg_558, ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone_grp4_done_reg, ap_block_pp0_stage1_11001_grp4)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001_grp4) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp4_done_reg) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (tmp_reg_558 = ap_const_lv1_1))) then 
            t_stream_read <= ap_const_logic_1;
        else 
            t_stream_read <= ap_const_logic_0;
        end if; 
    end process;

    tmp_nbreadreq_fu_150_p3 <= (0=>(x_stream_empty_n), others=>'-');

    x_stream_blk_n_assign_proc : process(x_stream_empty_n, tmp_reg_558, ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_grp1, ap_block_pp0_stage1_subdone_grp1_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp1_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage1_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (tmp_reg_558 = ap_const_lv1_1))) then 
            x_stream_blk_n <= x_stream_empty_n;
        else 
            x_stream_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    x_stream_read_assign_proc : process(tmp_reg_558, ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone_grp1_done_reg, ap_block_pp0_stage1_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001_grp1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp1_done_reg) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (tmp_reg_558 = ap_const_lv1_1))) then 
            x_stream_read <= ap_const_logic_1;
        else 
            x_stream_read <= ap_const_logic_0;
        end if; 
    end process;


    y_stream_blk_n_assign_proc : process(y_stream_empty_n, tmp_reg_558, ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_grp2, ap_block_pp0_stage1_subdone_grp2_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp2_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage1_grp2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (tmp_reg_558 = ap_const_lv1_1))) then 
            y_stream_blk_n <= y_stream_empty_n;
        else 
            y_stream_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    y_stream_read_assign_proc : process(tmp_reg_558, ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone_grp2_done_reg, ap_block_pp0_stage1_11001_grp2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001_grp2) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp2_done_reg) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (tmp_reg_558 = ap_const_lv1_1))) then 
            y_stream_read <= ap_const_logic_1;
        else 
            y_stream_read <= ap_const_logic_0;
        end if; 
    end process;


    z_stream_blk_n_assign_proc : process(z_stream_empty_n, tmp_reg_558, ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_grp3, ap_block_pp0_stage1_subdone_grp3_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp3_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage1_grp3) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (tmp_reg_558 = ap_const_lv1_1))) then 
            z_stream_blk_n <= z_stream_empty_n;
        else 
            z_stream_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    z_stream_read_assign_proc : process(tmp_reg_558, ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone_grp3_done_reg, ap_block_pp0_stage1_11001_grp3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001_grp3) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp3_done_reg) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (tmp_reg_558 = ap_const_lv1_1))) then 
            z_stream_read <= ap_const_logic_1;
        else 
            z_stream_read <= ap_const_logic_0;
        end if; 
    end process;

end behav;
