// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module msm_edwards_point_add (
        ap_clk,
        ap_rst,
        X1,
        Y1,
        Z1,
        T1,
        X2,
        Y2,
        Z2,
        T2,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3
);


input   ap_clk;
input   ap_rst;
input  [255:0] X1;
input  [255:0] Y1;
input  [255:0] Z1;
input  [255:0] T1;
input  [255:0] X2;
input  [255:0] Y2;
input  [255:0] Z2;
input  [255:0] T2;
output  [255:0] ap_return_0;
output  [255:0] ap_return_1;
output  [255:0] ap_return_2;
output  [255:0] ap_return_3;

wire    ap_block_pp0_stage0_11001;
wire   [256:0] add_ln300_fu_184_p2;
reg   [256:0] add_ln300_reg_662;
wire   [255:0] X1pY1_1_fu_190_p2;
reg   [255:0] X1pY1_1_reg_667;
wire   [256:0] add_ln301_fu_204_p2;
reg   [256:0] add_ln301_reg_673;
wire   [255:0] X2pY2_1_fu_210_p2;
reg   [255:0] X2pY2_1_reg_678;
wire  signed [255:0] X1pY1_2_fu_266_p3;
reg  signed [255:0] X1pY1_2_reg_724;
wire  signed [255:0] X2pY2_2_fu_283_p3;
reg  signed [255:0] X2pY2_2_reg_730;
wire   [511:0] grp_fu_86_p2;
reg   [511:0] mul_ln305_reg_746;
wire   [255:0] grp_fu_127_p2;
reg   [255:0] mul_ln305_1_reg_751;
reg   [255:0] mul_ln305_1_reg_751_pp0_iter5_reg;
wire   [511:0] grp_fu_90_p2;
reg   [511:0] mul_ln306_reg_757;
wire   [255:0] grp_fu_133_p2;
reg   [255:0] mul_ln306_1_reg_762;
reg   [255:0] mul_ln306_1_reg_762_pp0_iter5_reg;
wire   [511:0] grp_fu_94_p2;
reg   [511:0] mul_ln307_reg_768;
wire   [255:0] grp_fu_139_p2;
reg   [255:0] mul_ln307_1_reg_773;
reg   [255:0] mul_ln307_1_reg_773_pp0_iter5_reg;
wire   [511:0] grp_fu_98_p2;
reg   [511:0] mul_ln308_reg_779;
wire   [255:0] grp_fu_145_p2;
reg   [255:0] mul_ln308_1_reg_784;
reg   [255:0] mul_ln308_1_reg_784_pp0_iter5_reg;
wire   [0:0] icmp_ln305_fu_298_p2;
reg   [0:0] icmp_ln305_reg_790;
wire   [0:0] icmp_ln306_fu_303_p2;
reg   [0:0] icmp_ln306_reg_795;
wire   [0:0] icmp_ln307_fu_308_p2;
reg   [0:0] icmp_ln307_reg_800;
wire   [0:0] icmp_ln308_fu_313_p2;
reg   [0:0] icmp_ln308_reg_805;
wire   [255:0] A_fu_323_p3;
reg   [255:0] A_reg_810;
wire   [255:0] B_fu_334_p3;
reg   [255:0] B_reg_817;
wire   [255:0] C_fu_345_p3;
reg   [255:0] C_reg_824;
reg   [255:0] C_reg_824_pp0_iter7_reg;
reg   [255:0] C_reg_824_pp0_iter8_reg;
reg   [255:0] C_reg_824_pp0_iter9_reg;
reg   [255:0] C_reg_824_pp0_iter10_reg;
reg   [255:0] C_reg_824_pp0_iter11_reg;
reg   [255:0] C_reg_824_pp0_iter12_reg;
wire  signed [255:0] T1T2_fu_356_p3;
reg  signed [255:0] T1T2_reg_832;
wire   [511:0] grp_fu_102_p2;
reg   [511:0] mul_ln311_reg_838;
wire   [255:0] grp_fu_151_p2;
reg   [255:0] E_1_reg_843;
reg   [255:0] E_1_reg_843_pp0_iter7_reg;
wire   [0:0] icmp_ln311_fu_366_p2;
reg   [0:0] icmp_ln311_reg_854;
wire   [255:0] E_fu_371_p2;
reg   [255:0] E_reg_859;
wire   [0:0] icmp_ln314_fu_376_p2;
reg   [0:0] icmp_ln314_reg_864;
wire   [255:0] H_fu_380_p2;
reg   [255:0] H_reg_869;
wire   [255:0] AplusB_fu_384_p2;
reg   [255:0] AplusB_reg_875;
wire  signed [255:0] H_2_fu_403_p3;
reg  signed [255:0] H_2_reg_881;
reg  signed [255:0] H_2_reg_881_pp0_iter9_reg;
reg  signed [255:0] H_2_reg_881_pp0_iter10_reg;
reg  signed [255:0] H_2_reg_881_pp0_iter11_reg;
reg  signed [255:0] H_2_reg_881_pp0_iter12_reg;
reg  signed [255:0] H_2_reg_881_pp0_iter13_reg;
reg  signed [255:0] H_2_reg_881_pp0_iter14_reg;
reg  signed [255:0] H_2_reg_881_pp0_iter15_reg;
wire   [0:0] icmp_ln317_fu_410_p2;
reg   [0:0] icmp_ln317_reg_888;
wire   [255:0] E_minus_AplusB_fu_415_p2;
reg   [255:0] E_minus_AplusB_reg_893;
wire  signed [255:0] E_minus_AplusB_2_fu_430_p3;
reg  signed [255:0] E_minus_AplusB_2_reg_899;
reg  signed [255:0] E_minus_AplusB_2_reg_899_pp0_iter10_reg;
reg  signed [255:0] E_minus_AplusB_2_reg_899_pp0_iter11_reg;
reg  signed [255:0] E_minus_AplusB_2_reg_899_pp0_iter12_reg;
reg  signed [255:0] E_minus_AplusB_2_reg_899_pp0_iter13_reg;
reg  signed [255:0] E_minus_AplusB_2_reg_899_pp0_iter14_reg;
reg  signed [255:0] E_minus_AplusB_2_reg_899_pp0_iter15_reg;
wire   [508:0] grp_fu_122_p2;
reg   [508:0] mul_ln309_reg_906;
wire   [255:0] grp_fu_171_p2;
reg   [255:0] mul_ln309_1_reg_911;
reg   [255:0] mul_ln309_1_reg_911_pp0_iter12_reg;
wire   [0:0] icmp_ln309_fu_437_p2;
reg   [0:0] icmp_ln309_reg_917;
wire   [255:0] add_ln309_fu_442_p2;
reg   [255:0] add_ln309_reg_922;
wire   [0:0] icmp_ln312_fu_452_p2;
reg   [0:0] icmp_ln312_reg_927;
wire   [255:0] F_fu_457_p2;
reg   [255:0] F_reg_932;
wire   [256:0] add_ln313_fu_469_p2;
reg   [256:0] add_ln313_reg_938;
wire   [255:0] G_1_fu_475_p2;
reg   [255:0] G_1_reg_943;
wire  signed [255:0] F_2_fu_490_p3;
reg  signed [255:0] F_2_reg_949;
reg  signed [255:0] F_2_reg_949_pp0_iter15_reg;
wire  signed [255:0] G_2_fu_507_p3;
reg  signed [255:0] G_2_reg_956;
reg  signed [255:0] G_2_reg_956_pp0_iter15_reg;
wire   [511:0] zext_ln321_fu_514_p1;
wire   [511:0] zext_ln321_1_fu_519_p1;
wire   [511:0] zext_ln322_fu_524_p1;
wire   [511:0] zext_ln322_1_fu_529_p1;
wire   [511:0] grp_fu_106_p2;
reg   [511:0] mul_ln321_reg_987;
wire   [511:0] grp_fu_110_p2;
reg   [511:0] mul_ln322_reg_992;
wire   [511:0] grp_fu_114_p2;
reg   [511:0] mul_ln323_reg_997;
wire   [511:0] grp_fu_118_p2;
reg   [511:0] mul_ln324_reg_1002;
wire   [0:0] icmp_ln321_fu_534_p2;
reg   [0:0] icmp_ln321_reg_1007;
wire   [255:0] grp_fu_155_p2;
reg   [255:0] X3_tmp_1_reg_1012;
wire   [0:0] icmp_ln322_fu_539_p2;
reg   [0:0] icmp_ln322_reg_1018;
wire   [255:0] grp_fu_159_p2;
reg   [255:0] Y3_tmp_1_reg_1023;
wire   [0:0] icmp_ln323_fu_544_p2;
reg   [0:0] icmp_ln323_reg_1029;
wire   [255:0] grp_fu_163_p2;
reg   [255:0] T3_tmp_1_reg_1034;
wire   [0:0] icmp_ln324_fu_549_p2;
reg   [0:0] icmp_ln324_reg_1040;
wire   [255:0] grp_fu_167_p2;
reg   [255:0] Z3_tmp_1_reg_1045;
wire   [255:0] grp_fu_86_p0;
wire   [255:0] grp_fu_86_p1;
wire    ap_block_pp0_stage0;
wire   [255:0] grp_fu_90_p0;
wire   [255:0] grp_fu_90_p1;
wire   [255:0] grp_fu_94_p0;
wire   [255:0] grp_fu_94_p1;
wire   [255:0] grp_fu_98_p0;
wire   [255:0] grp_fu_98_p1;
wire   [255:0] grp_fu_102_p0;
wire   [255:0] grp_fu_102_p1;
wire   [255:0] grp_fu_106_p0;
wire   [255:0] grp_fu_106_p1;
wire   [255:0] grp_fu_110_p0;
wire   [255:0] grp_fu_110_p1;
wire   [255:0] grp_fu_114_p0;
wire   [255:0] grp_fu_114_p1;
wire   [255:0] grp_fu_118_p0;
wire   [255:0] grp_fu_118_p1;
wire   [255:0] grp_fu_122_p0;
wire   [253:0] grp_fu_122_p1;
wire   [253:0] grp_fu_171_p1;
wire  signed [255:0] zext_ln300_fu_176_p0;
wire  signed [255:0] zext_ln300_1_fu_180_p0;
wire   [256:0] zext_ln300_1_fu_180_p1;
wire   [256:0] zext_ln300_fu_176_p1;
wire  signed [255:0] X1pY1_1_fu_190_p0;
wire  signed [255:0] X1pY1_1_fu_190_p1;
wire  signed [255:0] zext_ln301_fu_196_p0;
wire  signed [255:0] zext_ln301_1_fu_200_p0;
wire   [256:0] zext_ln301_1_fu_200_p1;
wire   [256:0] zext_ln301_fu_196_p1;
wire  signed [255:0] X2pY2_1_fu_210_p0;
wire  signed [255:0] X2pY2_1_fu_210_p1;
wire  signed [255:0] zext_ln305_fu_216_p0;
wire  signed [255:0] zext_ln305_1_fu_221_p0;
wire  signed [255:0] zext_ln306_fu_226_p0;
wire  signed [255:0] zext_ln306_1_fu_231_p0;
wire  signed [255:0] zext_ln307_fu_236_p0;
wire  signed [255:0] zext_ln307_1_fu_241_p0;
wire  signed [255:0] zext_ln308_fu_246_p0;
wire  signed [255:0] zext_ln308_1_fu_251_p0;
wire   [0:0] icmp_ln300_fu_256_p2;
wire   [255:0] X1pY1_fu_261_p2;
wire   [0:0] icmp_ln301_fu_273_p2;
wire   [255:0] X2pY2_fu_278_p2;
wire   [255:0] add_ln305_fu_318_p2;
wire   [255:0] add_ln306_fu_329_p2;
wire   [255:0] add_ln307_fu_340_p2;
wire   [255:0] add_ln308_fu_351_p2;
wire   [0:0] xor_ln314_fu_393_p2;
wire   [255:0] H_1_fu_398_p2;
wire   [255:0] E_2_fu_388_p3;
wire   [0:0] E_geq_AplusB_fu_420_p2;
wire   [255:0] E_minus_AplusB_1_fu_425_p2;
wire   [255:0] D_fu_447_p3;
wire   [256:0] zext_ln313_1_fu_465_p1;
wire   [256:0] zext_ln313_fu_462_p1;
wire   [0:0] xor_ln312_fu_480_p2;
wire   [255:0] F_1_fu_485_p2;
wire   [0:0] icmp_ln313_fu_497_p2;
wire   [255:0] G_fu_502_p2;
wire   [255:0] X3_tmp_fu_554_p2;
wire   [255:0] Y3_tmp_fu_565_p2;
wire   [255:0] T3_tmp_fu_576_p2;
wire   [255:0] Z3_tmp_fu_587_p2;
wire   [255:0] X3_tmp_2_fu_559_p3;
wire   [255:0] Y3_tmp_2_fu_570_p3;
wire   [255:0] Z3_tmp_2_fu_592_p3;
wire   [255:0] T3_tmp_2_fu_581_p3;
reg  signed [255:0] X1_int_reg;
reg  signed [255:0] Y1_int_reg;
reg  signed [255:0] Z1_int_reg;
reg  signed [255:0] T1_int_reg;
reg  signed [255:0] X2_int_reg;
reg  signed [255:0] Y2_int_reg;
reg  signed [255:0] Z2_int_reg;
reg  signed [255:0] T2_int_reg;
wire   [511:0] grp_fu_102_p00;
wire   [511:0] grp_fu_102_p10;
wire   [508:0] grp_fu_122_p00;
wire   [511:0] grp_fu_86_p00;
wire   [511:0] grp_fu_86_p10;
wire   [511:0] grp_fu_90_p00;
wire   [511:0] grp_fu_90_p10;
wire   [511:0] grp_fu_94_p00;
wire   [511:0] grp_fu_94_p10;
wire   [511:0] grp_fu_98_p00;
wire   [511:0] grp_fu_98_p10;
wire    ap_ce_reg;

msm_mul_256ns_256ns_512_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 256 ),
    .din1_WIDTH( 256 ),
    .dout_WIDTH( 512 ))
mul_256ns_256ns_512_5_1_U27(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_86_p0),
    .din1(grp_fu_86_p1),
    .ce(1'b1),
    .dout(grp_fu_86_p2)
);

msm_mul_256ns_256ns_512_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 256 ),
    .din1_WIDTH( 256 ),
    .dout_WIDTH( 512 ))
mul_256ns_256ns_512_5_1_U28(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_90_p0),
    .din1(grp_fu_90_p1),
    .ce(1'b1),
    .dout(grp_fu_90_p2)
);

msm_mul_256ns_256ns_512_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 256 ),
    .din1_WIDTH( 256 ),
    .dout_WIDTH( 512 ))
mul_256ns_256ns_512_5_1_U29(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_94_p0),
    .din1(grp_fu_94_p1),
    .ce(1'b1),
    .dout(grp_fu_94_p2)
);

msm_mul_256ns_256ns_512_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 256 ),
    .din1_WIDTH( 256 ),
    .dout_WIDTH( 512 ))
mul_256ns_256ns_512_5_1_U30(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_98_p0),
    .din1(grp_fu_98_p1),
    .ce(1'b1),
    .dout(grp_fu_98_p2)
);

msm_mul_256ns_256ns_512_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 256 ),
    .din1_WIDTH( 256 ),
    .dout_WIDTH( 512 ))
mul_256ns_256ns_512_5_1_U31(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_102_p0),
    .din1(grp_fu_102_p1),
    .ce(1'b1),
    .dout(grp_fu_102_p2)
);

msm_mul_256ns_256ns_512_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 256 ),
    .din1_WIDTH( 256 ),
    .dout_WIDTH( 512 ))
mul_256ns_256ns_512_5_1_U32(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_106_p0),
    .din1(grp_fu_106_p1),
    .ce(1'b1),
    .dout(grp_fu_106_p2)
);

msm_mul_256ns_256ns_512_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 256 ),
    .din1_WIDTH( 256 ),
    .dout_WIDTH( 512 ))
mul_256ns_256ns_512_5_1_U33(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_110_p0),
    .din1(grp_fu_110_p1),
    .ce(1'b1),
    .dout(grp_fu_110_p2)
);

msm_mul_256ns_256ns_512_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 256 ),
    .din1_WIDTH( 256 ),
    .dout_WIDTH( 512 ))
mul_256ns_256ns_512_5_1_U34(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_114_p0),
    .din1(grp_fu_114_p1),
    .ce(1'b1),
    .dout(grp_fu_114_p2)
);

msm_mul_256ns_256ns_512_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 256 ),
    .din1_WIDTH( 256 ),
    .dout_WIDTH( 512 ))
mul_256ns_256ns_512_5_1_U35(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_118_p0),
    .din1(grp_fu_118_p1),
    .ce(1'b1),
    .dout(grp_fu_118_p2)
);

msm_mul_256ns_254ns_509_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 256 ),
    .din1_WIDTH( 254 ),
    .dout_WIDTH( 509 ))
mul_256ns_254ns_509_5_1_U36(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_122_p0),
    .din1(grp_fu_122_p1),
    .ce(1'b1),
    .dout(grp_fu_122_p2)
);

msm_mul_256s_256s_256_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 256 ),
    .din1_WIDTH( 256 ),
    .dout_WIDTH( 256 ))
mul_256s_256s_256_5_1_U37(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(X2_int_reg),
    .din1(X1_int_reg),
    .ce(1'b1),
    .dout(grp_fu_127_p2)
);

msm_mul_256s_256s_256_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 256 ),
    .din1_WIDTH( 256 ),
    .dout_WIDTH( 256 ))
mul_256s_256s_256_5_1_U38(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(Y2_int_reg),
    .din1(Y1_int_reg),
    .ce(1'b1),
    .dout(grp_fu_133_p2)
);

msm_mul_256s_256s_256_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 256 ),
    .din1_WIDTH( 256 ),
    .dout_WIDTH( 256 ))
mul_256s_256s_256_5_1_U39(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(Z2_int_reg),
    .din1(Z1_int_reg),
    .ce(1'b1),
    .dout(grp_fu_139_p2)
);

msm_mul_256s_256s_256_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 256 ),
    .din1_WIDTH( 256 ),
    .dout_WIDTH( 256 ))
mul_256s_256s_256_5_1_U40(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(T2_int_reg),
    .din1(T1_int_reg),
    .ce(1'b1),
    .dout(grp_fu_145_p2)
);

msm_mul_256s_256s_256_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 256 ),
    .din1_WIDTH( 256 ),
    .dout_WIDTH( 256 ))
mul_256s_256s_256_5_1_U41(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(X2pY2_2_reg_730),
    .din1(X1pY1_2_reg_724),
    .ce(1'b1),
    .dout(grp_fu_151_p2)
);

msm_mul_256s_256s_256_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 256 ),
    .din1_WIDTH( 256 ),
    .dout_WIDTH( 256 ))
mul_256s_256s_256_5_1_U42(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(F_2_reg_949_pp0_iter15_reg),
    .din1(E_minus_AplusB_2_reg_899_pp0_iter15_reg),
    .ce(1'b1),
    .dout(grp_fu_155_p2)
);

msm_mul_256s_256s_256_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 256 ),
    .din1_WIDTH( 256 ),
    .dout_WIDTH( 256 ))
mul_256s_256s_256_5_1_U43(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(G_2_reg_956_pp0_iter15_reg),
    .din1(H_2_reg_881_pp0_iter15_reg),
    .ce(1'b1),
    .dout(grp_fu_159_p2)
);

msm_mul_256s_256s_256_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 256 ),
    .din1_WIDTH( 256 ),
    .dout_WIDTH( 256 ))
mul_256s_256s_256_5_1_U44(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(E_minus_AplusB_2_reg_899_pp0_iter15_reg),
    .din1(H_2_reg_881_pp0_iter15_reg),
    .ce(1'b1),
    .dout(grp_fu_163_p2)
);

msm_mul_256s_256s_256_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 256 ),
    .din1_WIDTH( 256 ),
    .dout_WIDTH( 256 ))
mul_256s_256s_256_5_1_U45(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(G_2_reg_956_pp0_iter15_reg),
    .din1(F_2_reg_949_pp0_iter15_reg),
    .ce(1'b1),
    .dout(grp_fu_167_p2)
);

msm_mul_256s_254ns_256_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 256 ),
    .din1_WIDTH( 254 ),
    .dout_WIDTH( 256 ))
mul_256s_254ns_256_5_1_U46(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(T1T2_reg_832),
    .din1(grp_fu_171_p1),
    .ce(1'b1),
    .dout(grp_fu_171_p2)
);

always @ (posedge ap_clk) begin
    T1_int_reg <= T1;
end

always @ (posedge ap_clk) begin
    T2_int_reg <= T2;
end

always @ (posedge ap_clk) begin
    X1_int_reg <= X1;
end

always @ (posedge ap_clk) begin
    X2_int_reg <= X2;
end

always @ (posedge ap_clk) begin
    Y1_int_reg <= Y1;
end

always @ (posedge ap_clk) begin
    Y2_int_reg <= Y2;
end

always @ (posedge ap_clk) begin
    Z1_int_reg <= Z1;
end

always @ (posedge ap_clk) begin
    Z2_int_reg <= Z2;
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        A_reg_810 <= A_fu_323_p3;
        AplusB_reg_875 <= AplusB_fu_384_p2;
        B_reg_817 <= B_fu_334_p3;
        C_reg_824 <= C_fu_345_p3;
        C_reg_824_pp0_iter10_reg <= C_reg_824_pp0_iter9_reg;
        C_reg_824_pp0_iter11_reg <= C_reg_824_pp0_iter10_reg;
        C_reg_824_pp0_iter12_reg <= C_reg_824_pp0_iter11_reg;
        C_reg_824_pp0_iter7_reg <= C_reg_824;
        C_reg_824_pp0_iter8_reg <= C_reg_824_pp0_iter7_reg;
        C_reg_824_pp0_iter9_reg <= C_reg_824_pp0_iter8_reg;
        E_1_reg_843 <= grp_fu_151_p2;
        E_1_reg_843_pp0_iter7_reg <= E_1_reg_843;
        E_minus_AplusB_2_reg_899 <= E_minus_AplusB_2_fu_430_p3;
        E_minus_AplusB_2_reg_899_pp0_iter10_reg <= E_minus_AplusB_2_reg_899;
        E_minus_AplusB_2_reg_899_pp0_iter11_reg <= E_minus_AplusB_2_reg_899_pp0_iter10_reg;
        E_minus_AplusB_2_reg_899_pp0_iter12_reg <= E_minus_AplusB_2_reg_899_pp0_iter11_reg;
        E_minus_AplusB_2_reg_899_pp0_iter13_reg <= E_minus_AplusB_2_reg_899_pp0_iter12_reg;
        E_minus_AplusB_2_reg_899_pp0_iter14_reg <= E_minus_AplusB_2_reg_899_pp0_iter13_reg;
        E_minus_AplusB_2_reg_899_pp0_iter15_reg <= E_minus_AplusB_2_reg_899_pp0_iter14_reg;
        E_minus_AplusB_reg_893 <= E_minus_AplusB_fu_415_p2;
        E_reg_859 <= E_fu_371_p2;
        F_2_reg_949 <= F_2_fu_490_p3;
        F_2_reg_949_pp0_iter15_reg <= F_2_reg_949;
        F_reg_932 <= F_fu_457_p2;
        G_1_reg_943 <= G_1_fu_475_p2;
        G_2_reg_956 <= G_2_fu_507_p3;
        G_2_reg_956_pp0_iter15_reg <= G_2_reg_956;
        H_2_reg_881 <= H_2_fu_403_p3;
        H_2_reg_881_pp0_iter10_reg <= H_2_reg_881_pp0_iter9_reg;
        H_2_reg_881_pp0_iter11_reg <= H_2_reg_881_pp0_iter10_reg;
        H_2_reg_881_pp0_iter12_reg <= H_2_reg_881_pp0_iter11_reg;
        H_2_reg_881_pp0_iter13_reg <= H_2_reg_881_pp0_iter12_reg;
        H_2_reg_881_pp0_iter14_reg <= H_2_reg_881_pp0_iter13_reg;
        H_2_reg_881_pp0_iter15_reg <= H_2_reg_881_pp0_iter14_reg;
        H_2_reg_881_pp0_iter9_reg <= H_2_reg_881;
        H_reg_869 <= H_fu_380_p2;
        T1T2_reg_832 <= T1T2_fu_356_p3;
        T3_tmp_1_reg_1034 <= grp_fu_163_p2;
        X1pY1_1_reg_667 <= X1pY1_1_fu_190_p2;
        X1pY1_2_reg_724 <= X1pY1_2_fu_266_p3;
        X2pY2_1_reg_678 <= X2pY2_1_fu_210_p2;
        X2pY2_2_reg_730 <= X2pY2_2_fu_283_p3;
        X3_tmp_1_reg_1012 <= grp_fu_155_p2;
        Y3_tmp_1_reg_1023 <= grp_fu_159_p2;
        Z3_tmp_1_reg_1045 <= grp_fu_167_p2;
        add_ln300_reg_662 <= add_ln300_fu_184_p2;
        add_ln301_reg_673 <= add_ln301_fu_204_p2;
        add_ln309_reg_922 <= add_ln309_fu_442_p2;
        add_ln313_reg_938 <= add_ln313_fu_469_p2;
        icmp_ln305_reg_790 <= icmp_ln305_fu_298_p2;
        icmp_ln306_reg_795 <= icmp_ln306_fu_303_p2;
        icmp_ln307_reg_800 <= icmp_ln307_fu_308_p2;
        icmp_ln308_reg_805 <= icmp_ln308_fu_313_p2;
        icmp_ln309_reg_917 <= icmp_ln309_fu_437_p2;
        icmp_ln311_reg_854 <= icmp_ln311_fu_366_p2;
        icmp_ln312_reg_927 <= icmp_ln312_fu_452_p2;
        icmp_ln314_reg_864 <= icmp_ln314_fu_376_p2;
        icmp_ln317_reg_888 <= icmp_ln317_fu_410_p2;
        icmp_ln321_reg_1007 <= icmp_ln321_fu_534_p2;
        icmp_ln322_reg_1018 <= icmp_ln322_fu_539_p2;
        icmp_ln323_reg_1029 <= icmp_ln323_fu_544_p2;
        icmp_ln324_reg_1040 <= icmp_ln324_fu_549_p2;
        mul_ln305_1_reg_751 <= grp_fu_127_p2;
        mul_ln305_1_reg_751_pp0_iter5_reg <= mul_ln305_1_reg_751;
        mul_ln305_reg_746 <= grp_fu_86_p2;
        mul_ln306_1_reg_762 <= grp_fu_133_p2;
        mul_ln306_1_reg_762_pp0_iter5_reg <= mul_ln306_1_reg_762;
        mul_ln306_reg_757 <= grp_fu_90_p2;
        mul_ln307_1_reg_773 <= grp_fu_139_p2;
        mul_ln307_1_reg_773_pp0_iter5_reg <= mul_ln307_1_reg_773;
        mul_ln307_reg_768 <= grp_fu_94_p2;
        mul_ln308_1_reg_784 <= grp_fu_145_p2;
        mul_ln308_1_reg_784_pp0_iter5_reg <= mul_ln308_1_reg_784;
        mul_ln308_reg_779 <= grp_fu_98_p2;
        mul_ln309_1_reg_911 <= grp_fu_171_p2;
        mul_ln309_1_reg_911_pp0_iter12_reg <= mul_ln309_1_reg_911;
        mul_ln309_reg_906 <= grp_fu_122_p2;
        mul_ln311_reg_838 <= grp_fu_102_p2;
        mul_ln321_reg_987 <= grp_fu_106_p2;
        mul_ln322_reg_992 <= grp_fu_110_p2;
        mul_ln323_reg_997 <= grp_fu_114_p2;
        mul_ln324_reg_1002 <= grp_fu_118_p2;
    end
end

assign A_fu_323_p3 = ((icmp_ln305_reg_790[0:0] == 1'b1) ? add_ln305_fu_318_p2 : mul_ln305_1_reg_751_pp0_iter5_reg);

assign AplusB_fu_384_p2 = (B_reg_817 + A_reg_810);

assign B_fu_334_p3 = ((icmp_ln306_reg_795[0:0] == 1'b1) ? add_ln306_fu_329_p2 : mul_ln306_1_reg_762_pp0_iter5_reg);

assign C_fu_345_p3 = ((icmp_ln307_reg_800[0:0] == 1'b1) ? add_ln307_fu_340_p2 : mul_ln307_1_reg_773_pp0_iter5_reg);

assign D_fu_447_p3 = ((icmp_ln309_reg_917[0:0] == 1'b1) ? add_ln309_reg_922 : mul_ln309_1_reg_911_pp0_iter12_reg);

assign E_2_fu_388_p3 = ((icmp_ln311_reg_854[0:0] == 1'b1) ? E_reg_859 : E_1_reg_843_pp0_iter7_reg);

assign E_fu_371_p2 = ($signed(E_1_reg_843) + $signed(256'd93903846365476920201324579263430632764721620265224529695759379821337321144319));

assign E_geq_AplusB_fu_420_p2 = (icmp_ln317_reg_888 ^ 1'd1);

assign E_minus_AplusB_1_fu_425_p2 = (E_minus_AplusB_reg_893 + 256'd43776485743678550444492811490514550177096728800832068687396408373151616991234);

assign E_minus_AplusB_2_fu_430_p3 = ((E_geq_AplusB_fu_420_p2[0:0] == 1'b1) ? E_minus_AplusB_reg_893 : E_minus_AplusB_1_fu_425_p2);

assign E_minus_AplusB_fu_415_p2 = (E_2_fu_388_p3 - AplusB_reg_875);

assign F_1_fu_485_p2 = (F_reg_932 + 256'd21888242871839275222246405745257275088548364400416034343698204186575808495617);

assign F_2_fu_490_p3 = ((xor_ln312_fu_480_p2[0:0] == 1'b1) ? F_reg_932 : F_1_fu_485_p2);

assign F_fu_457_p2 = (C_reg_824_pp0_iter12_reg - D_fu_447_p3);

assign G_1_fu_475_p2 = (D_fu_447_p3 + C_reg_824_pp0_iter12_reg);

assign G_2_fu_507_p3 = ((icmp_ln313_fu_497_p2[0:0] == 1'b1) ? G_fu_502_p2 : G_1_reg_943);

assign G_fu_502_p2 = ($signed(G_1_reg_943) + $signed(256'd93903846365476920201324579263430632764721620265224529695759379821337321144319));

assign H_1_fu_398_p2 = (H_reg_869 + 256'd21888242871839275222246405745257275088548364400416034343698204186575808495617);

assign H_2_fu_403_p3 = ((xor_ln314_fu_393_p2[0:0] == 1'b1) ? H_reg_869 : H_1_fu_398_p2);

assign H_fu_380_p2 = (B_reg_817 - A_reg_810);

assign T1T2_fu_356_p3 = ((icmp_ln308_reg_805[0:0] == 1'b1) ? add_ln308_fu_351_p2 : mul_ln308_1_reg_784_pp0_iter5_reg);

assign T3_tmp_2_fu_581_p3 = ((icmp_ln323_reg_1029[0:0] == 1'b1) ? T3_tmp_fu_576_p2 : T3_tmp_1_reg_1034);

assign T3_tmp_fu_576_p2 = ($signed(T3_tmp_1_reg_1034) + $signed(256'd93903846365476920201324579263430632764721620265224529695759379821337321144319));

assign X1pY1_1_fu_190_p0 = Y1_int_reg;

assign X1pY1_1_fu_190_p1 = X1_int_reg;

assign X1pY1_1_fu_190_p2 = ($signed(X1pY1_1_fu_190_p0) + $signed(X1pY1_1_fu_190_p1));

assign X1pY1_2_fu_266_p3 = ((icmp_ln300_fu_256_p2[0:0] == 1'b1) ? X1pY1_fu_261_p2 : X1pY1_1_reg_667);

assign X1pY1_fu_261_p2 = ($signed(X1pY1_1_reg_667) + $signed(256'd93903846365476920201324579263430632764721620265224529695759379821337321144319));

assign X2pY2_1_fu_210_p0 = Y2_int_reg;

assign X2pY2_1_fu_210_p1 = X2_int_reg;

assign X2pY2_1_fu_210_p2 = ($signed(X2pY2_1_fu_210_p0) + $signed(X2pY2_1_fu_210_p1));

assign X2pY2_2_fu_283_p3 = ((icmp_ln301_fu_273_p2[0:0] == 1'b1) ? X2pY2_fu_278_p2 : X2pY2_1_reg_678);

assign X2pY2_fu_278_p2 = ($signed(X2pY2_1_reg_678) + $signed(256'd93903846365476920201324579263430632764721620265224529695759379821337321144319));

assign X3_tmp_2_fu_559_p3 = ((icmp_ln321_reg_1007[0:0] == 1'b1) ? X3_tmp_fu_554_p2 : X3_tmp_1_reg_1012);

assign X3_tmp_fu_554_p2 = ($signed(X3_tmp_1_reg_1012) + $signed(256'd93903846365476920201324579263430632764721620265224529695759379821337321144319));

assign Y3_tmp_2_fu_570_p3 = ((icmp_ln322_reg_1018[0:0] == 1'b1) ? Y3_tmp_fu_565_p2 : Y3_tmp_1_reg_1023);

assign Y3_tmp_fu_565_p2 = ($signed(Y3_tmp_1_reg_1023) + $signed(256'd93903846365476920201324579263430632764721620265224529695759379821337321144319));

assign Z3_tmp_2_fu_592_p3 = ((icmp_ln324_reg_1040[0:0] == 1'b1) ? Z3_tmp_fu_587_p2 : Z3_tmp_1_reg_1045);

assign Z3_tmp_fu_587_p2 = ($signed(Z3_tmp_1_reg_1045) + $signed(256'd93903846365476920201324579263430632764721620265224529695759379821337321144319));

assign add_ln300_fu_184_p2 = (zext_ln300_1_fu_180_p1 + zext_ln300_fu_176_p1);

assign add_ln301_fu_204_p2 = (zext_ln301_1_fu_200_p1 + zext_ln301_fu_196_p1);

assign add_ln305_fu_318_p2 = ($signed(mul_ln305_1_reg_751_pp0_iter5_reg) + $signed(256'd93903846365476920201324579263430632764721620265224529695759379821337321144319));

assign add_ln306_fu_329_p2 = ($signed(mul_ln306_1_reg_762_pp0_iter5_reg) + $signed(256'd93903846365476920201324579263430632764721620265224529695759379821337321144319));

assign add_ln307_fu_340_p2 = ($signed(mul_ln307_1_reg_773_pp0_iter5_reg) + $signed(256'd93903846365476920201324579263430632764721620265224529695759379821337321144319));

assign add_ln308_fu_351_p2 = ($signed(mul_ln308_1_reg_784_pp0_iter5_reg) + $signed(256'd93903846365476920201324579263430632764721620265224529695759379821337321144319));

assign add_ln309_fu_442_p2 = ($signed(mul_ln309_1_reg_911) + $signed(256'd93903846365476920201324579263430632764721620265224529695759379821337321144319));

assign add_ln313_fu_469_p2 = (zext_ln313_1_fu_465_p1 + zext_ln313_fu_462_p1);

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_return_0 = X3_tmp_2_fu_559_p3;

assign ap_return_1 = Y3_tmp_2_fu_570_p3;

assign ap_return_2 = Z3_tmp_2_fu_592_p3;

assign ap_return_3 = T3_tmp_2_fu_581_p3;

assign grp_fu_102_p0 = grp_fu_102_p00;

assign grp_fu_102_p00 = $unsigned(X2pY2_2_reg_730);

assign grp_fu_102_p1 = grp_fu_102_p10;

assign grp_fu_102_p10 = $unsigned(X1pY1_2_reg_724);

assign grp_fu_106_p0 = zext_ln321_1_fu_519_p1;

assign grp_fu_106_p1 = zext_ln321_fu_514_p1;

assign grp_fu_110_p0 = zext_ln322_fu_524_p1;

assign grp_fu_110_p1 = zext_ln322_1_fu_529_p1;

assign grp_fu_114_p0 = zext_ln321_fu_514_p1;

assign grp_fu_114_p1 = zext_ln322_1_fu_529_p1;

assign grp_fu_118_p0 = zext_ln322_fu_524_p1;

assign grp_fu_118_p1 = zext_ln321_1_fu_519_p1;

assign grp_fu_122_p0 = grp_fu_122_p00;

assign grp_fu_122_p00 = $unsigned(T1T2_reg_832);

assign grp_fu_122_p1 = 509'd9706598848417545097372247223557719406784115219466060233080913168975159366771;

assign grp_fu_171_p1 = 256'd9706598848417545097372247223557719406784115219466060233080913168975159366771;

assign grp_fu_86_p0 = grp_fu_86_p00;

assign grp_fu_86_p00 = $unsigned(zext_ln305_1_fu_221_p0);

assign grp_fu_86_p1 = grp_fu_86_p10;

assign grp_fu_86_p10 = $unsigned(zext_ln305_fu_216_p0);

assign grp_fu_90_p0 = grp_fu_90_p00;

assign grp_fu_90_p00 = $unsigned(zext_ln306_1_fu_231_p0);

assign grp_fu_90_p1 = grp_fu_90_p10;

assign grp_fu_90_p10 = $unsigned(zext_ln306_fu_226_p0);

assign grp_fu_94_p0 = grp_fu_94_p00;

assign grp_fu_94_p00 = $unsigned(zext_ln307_1_fu_241_p0);

assign grp_fu_94_p1 = grp_fu_94_p10;

assign grp_fu_94_p10 = $unsigned(zext_ln307_fu_236_p0);

assign grp_fu_98_p0 = grp_fu_98_p00;

assign grp_fu_98_p00 = $unsigned(zext_ln308_1_fu_251_p0);

assign grp_fu_98_p1 = grp_fu_98_p10;

assign grp_fu_98_p10 = $unsigned(zext_ln308_fu_246_p0);

assign icmp_ln300_fu_256_p2 = ((add_ln300_reg_662 > 257'd21888242871839275222246405745257275088548364400416034343698204186575808495616) ? 1'b1 : 1'b0);

assign icmp_ln301_fu_273_p2 = ((add_ln301_reg_673 > 257'd21888242871839275222246405745257275088548364400416034343698204186575808495616) ? 1'b1 : 1'b0);

assign icmp_ln305_fu_298_p2 = ((mul_ln305_reg_746 > 512'd21888242871839275222246405745257275088548364400416034343698204186575808495616) ? 1'b1 : 1'b0);

assign icmp_ln306_fu_303_p2 = ((mul_ln306_reg_757 > 512'd21888242871839275222246405745257275088548364400416034343698204186575808495616) ? 1'b1 : 1'b0);

assign icmp_ln307_fu_308_p2 = ((mul_ln307_reg_768 > 512'd21888242871839275222246405745257275088548364400416034343698204186575808495616) ? 1'b1 : 1'b0);

assign icmp_ln308_fu_313_p2 = ((mul_ln308_reg_779 > 512'd21888242871839275222246405745257275088548364400416034343698204186575808495616) ? 1'b1 : 1'b0);

assign icmp_ln309_fu_437_p2 = ((mul_ln309_reg_906 > 509'd21888242871839275222246405745257275088548364400416034343698204186575808495616) ? 1'b1 : 1'b0);

assign icmp_ln311_fu_366_p2 = ((mul_ln311_reg_838 > 512'd21888242871839275222246405745257275088548364400416034343698204186575808495616) ? 1'b1 : 1'b0);

assign icmp_ln312_fu_452_p2 = ((C_reg_824_pp0_iter12_reg < D_fu_447_p3) ? 1'b1 : 1'b0);

assign icmp_ln313_fu_497_p2 = ((add_ln313_reg_938 > 257'd21888242871839275222246405745257275088548364400416034343698204186575808495616) ? 1'b1 : 1'b0);

assign icmp_ln314_fu_376_p2 = ((B_reg_817 < A_reg_810) ? 1'b1 : 1'b0);

assign icmp_ln317_fu_410_p2 = ((E_2_fu_388_p3 < AplusB_reg_875) ? 1'b1 : 1'b0);

assign icmp_ln321_fu_534_p2 = ((mul_ln321_reg_987 > 512'd21888242871839275222246405745257275088548364400416034343698204186575808495616) ? 1'b1 : 1'b0);

assign icmp_ln322_fu_539_p2 = ((mul_ln322_reg_992 > 512'd21888242871839275222246405745257275088548364400416034343698204186575808495616) ? 1'b1 : 1'b0);

assign icmp_ln323_fu_544_p2 = ((mul_ln323_reg_997 > 512'd21888242871839275222246405745257275088548364400416034343698204186575808495616) ? 1'b1 : 1'b0);

assign icmp_ln324_fu_549_p2 = ((mul_ln324_reg_1002 > 512'd21888242871839275222246405745257275088548364400416034343698204186575808495616) ? 1'b1 : 1'b0);

assign xor_ln312_fu_480_p2 = (icmp_ln312_reg_927 ^ 1'd1);

assign xor_ln314_fu_393_p2 = (icmp_ln314_reg_864 ^ 1'd1);

assign zext_ln300_1_fu_180_p0 = Y1_int_reg;

assign zext_ln300_1_fu_180_p1 = $unsigned(zext_ln300_1_fu_180_p0);

assign zext_ln300_fu_176_p0 = X1_int_reg;

assign zext_ln300_fu_176_p1 = $unsigned(zext_ln300_fu_176_p0);

assign zext_ln301_1_fu_200_p0 = Y2_int_reg;

assign zext_ln301_1_fu_200_p1 = $unsigned(zext_ln301_1_fu_200_p0);

assign zext_ln301_fu_196_p0 = X2_int_reg;

assign zext_ln301_fu_196_p1 = $unsigned(zext_ln301_fu_196_p0);

assign zext_ln305_1_fu_221_p0 = X2_int_reg;

assign zext_ln305_fu_216_p0 = X1_int_reg;

assign zext_ln306_1_fu_231_p0 = Y2_int_reg;

assign zext_ln306_fu_226_p0 = Y1_int_reg;

assign zext_ln307_1_fu_241_p0 = Z2_int_reg;

assign zext_ln307_fu_236_p0 = Z1_int_reg;

assign zext_ln308_1_fu_251_p0 = T2_int_reg;

assign zext_ln308_fu_246_p0 = T1_int_reg;

assign zext_ln313_1_fu_465_p1 = D_fu_447_p3;

assign zext_ln313_fu_462_p1 = C_reg_824_pp0_iter12_reg;

assign zext_ln321_1_fu_519_p1 = $unsigned(F_2_reg_949);

assign zext_ln321_fu_514_p1 = $unsigned(E_minus_AplusB_2_reg_899_pp0_iter14_reg);

assign zext_ln322_1_fu_529_p1 = $unsigned(H_2_reg_881_pp0_iter14_reg);

assign zext_ln322_fu_524_p1 = $unsigned(G_2_reg_956);

endmodule //msm_edwards_point_add
