// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module pippenger_control_add_point_to_bucket (
        ap_clk,
        ap_rst,
        bucket_point_x_read,
        bucket_point_y_read,
        bucket_point_z_read,
        bucket_point_t_read,
        x,
        y,
        z,
        t,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_ce
);


input   ap_clk;
input   ap_rst;
input  [255:0] bucket_point_x_read;
input  [255:0] bucket_point_y_read;
input  [255:0] bucket_point_z_read;
input  [255:0] bucket_point_t_read;
input  [255:0] x;
input  [255:0] y;
input  [255:0] z;
input  [255:0] t;
output  [255:0] ap_return_0;
output  [255:0] ap_return_1;
output  [255:0] ap_return_2;
output  [255:0] ap_return_3;
input   ap_ce;

reg[255:0] ap_return_0;
reg[255:0] ap_return_1;
reg[255:0] ap_return_2;
reg[255:0] ap_return_3;

wire    ap_block_pp0_stage0_11001;
wire   [255:0] grp_edwards_point_add_fu_76_ap_return_0;
wire   [255:0] grp_edwards_point_add_fu_76_ap_return_1;
wire   [255:0] grp_edwards_point_add_fu_76_ap_return_2;
wire   [255:0] grp_edwards_point_add_fu_76_ap_return_3;
reg    grp_edwards_point_add_fu_76_ap_ce;
wire    ap_block_pp0_stage0_11001_ignoreCallOp1568;
wire    ap_block_pp0_stage0_ignoreCallOp1568;
reg    ap_ce_reg;
reg   [255:0] bucket_point_x_read_int_reg;
reg   [255:0] bucket_point_y_read_int_reg;
reg   [255:0] bucket_point_z_read_int_reg;
reg   [255:0] bucket_point_t_read_int_reg;
reg   [255:0] x_int_reg;
reg   [255:0] y_int_reg;
reg   [255:0] z_int_reg;
reg   [255:0] t_int_reg;
reg   [255:0] ap_return_0_int_reg;
reg   [255:0] ap_return_1_int_reg;
reg   [255:0] ap_return_2_int_reg;
reg   [255:0] ap_return_3_int_reg;

pippenger_control_edwards_point_add grp_edwards_point_add_fu_76(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .X1(bucket_point_x_read_int_reg),
    .Y1(bucket_point_y_read_int_reg),
    .Z1(bucket_point_z_read_int_reg),
    .T1(bucket_point_t_read_int_reg),
    .X2(x_int_reg),
    .Y2(y_int_reg),
    .Z2(z_int_reg),
    .T2(t_int_reg),
    .ap_return_0(grp_edwards_point_add_fu_76_ap_return_0),
    .ap_return_1(grp_edwards_point_add_fu_76_ap_return_1),
    .ap_return_2(grp_edwards_point_add_fu_76_ap_return_2),
    .ap_return_3(grp_edwards_point_add_fu_76_ap_return_3),
    .ap_ce(grp_edwards_point_add_fu_76_ap_ce)
);

always @ (posedge ap_clk) begin
    ap_ce_reg <= ap_ce;
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce_reg)) begin
        ap_return_0_int_reg <= grp_edwards_point_add_fu_76_ap_return_0;
        ap_return_1_int_reg <= grp_edwards_point_add_fu_76_ap_return_1;
        ap_return_2_int_reg <= grp_edwards_point_add_fu_76_ap_return_2;
        ap_return_3_int_reg <= grp_edwards_point_add_fu_76_ap_return_3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce)) begin
        bucket_point_t_read_int_reg <= bucket_point_t_read;
        bucket_point_x_read_int_reg <= bucket_point_x_read;
        bucket_point_y_read_int_reg <= bucket_point_y_read;
        bucket_point_z_read_int_reg <= bucket_point_z_read;
        t_int_reg <= t;
        x_int_reg <= x;
        y_int_reg <= y;
        z_int_reg <= z;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_0 = ap_return_0_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_0 = grp_edwards_point_add_fu_76_ap_return_0;
    end else begin
        ap_return_0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_1 = ap_return_1_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_1 = grp_edwards_point_add_fu_76_ap_return_1;
    end else begin
        ap_return_1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_2 = ap_return_2_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_2 = grp_edwards_point_add_fu_76_ap_return_2;
    end else begin
        ap_return_2 = 'bx;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_3 = ap_return_3_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_3 = grp_edwards_point_add_fu_76_ap_return_3;
    end else begin
        ap_return_3 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp1568) & (1'b1 == ap_ce_reg))) begin
        grp_edwards_point_add_fu_76_ap_ce = 1'b1;
    end else begin
        grp_edwards_point_add_fu_76_ap_ce = 1'b0;
    end
end

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001_ignoreCallOp1568 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_ignoreCallOp1568 = ~(1'b1 == 1'b1);

endmodule //pippenger_control_add_point_to_bucket
