// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module pippenger_control_pippenger_control_Pipeline_VITIS_LOOP_568_1_VITIS_LOOP_570_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        out_stream_din,
        out_stream_full_n,
        out_stream_write
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [1038:0] out_stream_din;
input   out_stream_full_n;
output   out_stream_write;

reg ap_idle;
reg out_stream_write;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln568_fu_163_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [13:0] buckets_y_0_address0;
wire   [0:0] buckets_y_0_q0;
wire   [13:0] buckets_y_1_address0;
wire   [0:0] buckets_y_1_q0;
wire   [13:0] buckets_z_0_address0;
wire   [0:0] buckets_z_0_q0;
wire   [13:0] buckets_z_1_address0;
wire   [0:0] buckets_z_1_q0;
reg    out_stream_blk_n;
wire    ap_block_pp0_stage0;
wire   [4:0] select_ln568_1_fu_201_p3;
reg   [4:0] select_ln568_1_reg_327;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] trunc_ln570_fu_209_p1;
reg   [0:0] trunc_ln570_reg_332;
wire   [9:0] trunc_ln577_fu_239_p1;
reg   [9:0] trunc_ln577_reg_358;
wire   [63:0] zext_ln572_fu_231_p1;
reg   [10:0] j_fu_74;
wire   [10:0] j_1_fu_243_p2;
wire    ap_loop_init;
reg   [10:0] ap_sig_allocacmp_j_load;
reg   [4:0] i_fu_78;
reg   [4:0] ap_sig_allocacmp_i_load;
reg   [14:0] indvar_flatten_fu_82;
wire   [14:0] add_ln568_fu_169_p2;
reg   [14:0] ap_sig_allocacmp_indvar_flatten_load;
reg    ap_block_pp0_stage0_01001;
reg    buckets_y_0_ce0_local;
reg    buckets_y_1_ce0_local;
reg    buckets_z_0_ce0_local;
reg    buckets_z_1_ce0_local;
wire   [0:0] icmp_ln570_fu_187_p2;
wire   [4:0] i_2_fu_181_p2;
wire   [10:0] select_ln568_fu_193_p3;
wire   [8:0] lshr_ln_fu_213_p4;
wire   [13:0] tmp_3_fu_223_p3;
wire   [0:0] bucket_result_point_z_fu_264_p3;
wire   [0:0] select_ln574_fu_271_p3;
wire   [256:0] tmp_4_fu_278_p4;
wire   [767:0] zext_ln577_fu_288_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 j_fu_74 = 11'd0;
#0 i_fu_78 = 5'd0;
#0 indvar_flatten_fu_82 = 15'd0;
#0 ap_done_reg = 1'b0;
end

pippenger_control_pippenger_control_Pipeline_VITIS_LOOP_568_1_VITIS_LOOP_570_2_buckets_y_0_RAM_bkb #(
    .DataWidth( 1 ),
    .AddressRange( 13312 ),
    .AddressWidth( 14 ))
buckets_y_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(buckets_y_0_address0),
    .ce0(buckets_y_0_ce0_local),
    .q0(buckets_y_0_q0)
);

pippenger_control_pippenger_control_Pipeline_VITIS_LOOP_568_1_VITIS_LOOP_570_2_buckets_y_0_RAM_bkb #(
    .DataWidth( 1 ),
    .AddressRange( 13312 ),
    .AddressWidth( 14 ))
buckets_y_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(buckets_y_1_address0),
    .ce0(buckets_y_1_ce0_local),
    .q0(buckets_y_1_q0)
);

pippenger_control_pippenger_control_Pipeline_VITIS_LOOP_568_1_VITIS_LOOP_570_2_buckets_y_0_RAM_bkb #(
    .DataWidth( 1 ),
    .AddressRange( 13312 ),
    .AddressWidth( 14 ))
buckets_z_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(buckets_z_0_address0),
    .ce0(buckets_z_0_ce0_local),
    .q0(buckets_z_0_q0)
);

pippenger_control_pippenger_control_Pipeline_VITIS_LOOP_568_1_VITIS_LOOP_570_2_buckets_y_0_RAM_bkb #(
    .DataWidth( 1 ),
    .AddressRange( 13312 ),
    .AddressWidth( 14 ))
buckets_z_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(buckets_z_1_address0),
    .ce0(buckets_z_1_ce0_local),
    .q0(buckets_z_1_q0)
);

pippenger_control_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln568_fu_163_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_78 <= select_ln568_1_fu_201_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_78 <= 5'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln568_fu_163_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten_fu_82 <= add_ln568_fu_169_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_82 <= 15'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln568_fu_163_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            j_fu_74 <= j_1_fu_243_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            j_fu_74 <= 11'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        select_ln568_1_reg_327 <= select_ln568_1_fu_201_p3;
        trunc_ln570_reg_332 <= trunc_ln570_fu_209_p1;
        trunc_ln577_reg_358 <= trunc_ln577_fu_239_p1;
    end
end

always @ (*) begin
    if (((icmp_ln568_fu_163_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_load = 5'd0;
    end else begin
        ap_sig_allocacmp_i_load = i_fu_78;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten_load = 15'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_82;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_j_load = 11'd0;
    end else begin
        ap_sig_allocacmp_j_load = j_fu_74;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buckets_y_0_ce0_local = 1'b1;
    end else begin
        buckets_y_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buckets_y_1_ce0_local = 1'b1;
    end else begin
        buckets_y_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buckets_z_0_ce0_local = 1'b1;
    end else begin
        buckets_z_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buckets_z_1_ce0_local = 1'b1;
    end else begin
        buckets_z_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out_stream_blk_n = out_stream_full_n;
    end else begin
        out_stream_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out_stream_write = 1'b1;
    end else begin
        out_stream_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln568_fu_169_p2 = (ap_sig_allocacmp_indvar_flatten_load + 15'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = (out_stream_full_n == 1'b0);
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign bucket_result_point_z_fu_264_p3 = ((trunc_ln570_reg_332[0:0] == 1'b1) ? buckets_z_1_q0 : buckets_z_0_q0);

assign buckets_y_0_address0 = zext_ln572_fu_231_p1;

assign buckets_y_1_address0 = zext_ln572_fu_231_p1;

assign buckets_z_0_address0 = zext_ln572_fu_231_p1;

assign buckets_z_1_address0 = zext_ln572_fu_231_p1;

assign i_2_fu_181_p2 = (ap_sig_allocacmp_i_load + 5'd1);

assign icmp_ln568_fu_163_p2 = ((ap_sig_allocacmp_indvar_flatten_load == 15'd26624) ? 1'b1 : 1'b0);

assign icmp_ln570_fu_187_p2 = ((ap_sig_allocacmp_j_load == 11'd1024) ? 1'b1 : 1'b0);

assign j_1_fu_243_p2 = (select_ln568_fu_193_p3 + 11'd1);

assign lshr_ln_fu_213_p4 = {{select_ln568_fu_193_p3[9:1]}};

assign out_stream_din = {{{{select_ln568_1_reg_327}, {trunc_ln577_reg_358}}, {zext_ln577_fu_288_p1}}, {256'd0}};

assign select_ln568_1_fu_201_p3 = ((icmp_ln570_fu_187_p2[0:0] == 1'b1) ? i_2_fu_181_p2 : ap_sig_allocacmp_i_load);

assign select_ln568_fu_193_p3 = ((icmp_ln570_fu_187_p2[0:0] == 1'b1) ? 11'd0 : ap_sig_allocacmp_j_load);

assign select_ln574_fu_271_p3 = ((trunc_ln570_reg_332[0:0] == 1'b1) ? buckets_y_1_q0 : buckets_y_0_q0);

assign tmp_3_fu_223_p3 = {{select_ln568_1_fu_201_p3}, {lshr_ln_fu_213_p4}};

assign tmp_4_fu_278_p4 = {{{bucket_result_point_z_fu_264_p3}, {255'd0}}, {select_ln574_fu_271_p3}};

assign trunc_ln570_fu_209_p1 = select_ln568_fu_193_p3[0:0];

assign trunc_ln577_fu_239_p1 = select_ln568_fu_193_p3[9:0];

assign zext_ln572_fu_231_p1 = tmp_3_fu_223_p3;

assign zext_ln577_fu_288_p1 = tmp_4_fu_278_p4;

endmodule //pippenger_control_pippenger_control_Pipeline_VITIS_LOOP_568_1_VITIS_LOOP_570_2
