// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module pippenger_control_pippenger_control_Pipeline_AGGREGATE_AND_OUT_VITIS_LOOP_570_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        out_stream_din,
        out_stream_full_n,
        out_stream_write,
        buckets_x_address0,
        buckets_x_ce0,
        buckets_x_q0,
        buckets_x_1_address0,
        buckets_x_1_ce0,
        buckets_x_1_q0,
        buckets_y_address0,
        buckets_y_ce0,
        buckets_y_q0,
        buckets_y_1_address0,
        buckets_y_1_ce0,
        buckets_y_1_q0,
        buckets_z_address0,
        buckets_z_ce0,
        buckets_z_q0,
        buckets_z_1_address0,
        buckets_z_1_ce0,
        buckets_z_1_q0,
        buckets_t_address0,
        buckets_t_ce0,
        buckets_t_q0,
        buckets_t_1_address0,
        buckets_t_1_ce0,
        buckets_t_1_q0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [1038:0] out_stream_din;
input   out_stream_full_n;
output   out_stream_write;
output  [13:0] buckets_x_address0;
output   buckets_x_ce0;
input  [255:0] buckets_x_q0;
output  [13:0] buckets_x_1_address0;
output   buckets_x_1_ce0;
input  [255:0] buckets_x_1_q0;
output  [13:0] buckets_y_address0;
output   buckets_y_ce0;
input  [255:0] buckets_y_q0;
output  [13:0] buckets_y_1_address0;
output   buckets_y_1_ce0;
input  [255:0] buckets_y_1_q0;
output  [13:0] buckets_z_address0;
output   buckets_z_ce0;
input  [255:0] buckets_z_q0;
output  [13:0] buckets_z_1_address0;
output   buckets_z_1_ce0;
input  [255:0] buckets_z_1_q0;
output  [13:0] buckets_t_address0;
output   buckets_t_ce0;
input  [255:0] buckets_t_q0;
output  [13:0] buckets_t_1_address0;
output   buckets_t_1_ce0;
input  [255:0] buckets_t_1_q0;

reg ap_idle;
reg out_stream_write;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln568_fu_217_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    out_stream_blk_n;
wire    ap_block_pp0_stage0_grp1;
reg    ap_block_pp0_stage0_11001;
wire   [4:0] select_ln568_1_fu_255_p3;
reg   [4:0] select_ln568_1_reg_386;
reg   [4:0] select_ln568_1_reg_386_pp0_iter1_reg;
wire   [0:0] trunc_ln570_fu_263_p1;
reg   [0:0] trunc_ln570_reg_391;
wire   [9:0] trunc_ln577_fu_297_p1;
reg   [9:0] trunc_ln577_reg_439;
reg   [9:0] trunc_ln577_reg_439_pp0_iter1_reg;
wire   [255:0] bucket_result_point_x_fu_322_p3;
reg   [255:0] bucket_result_point_x_reg_444;
wire   [255:0] bucket_result_point_y_fu_329_p3;
reg   [255:0] bucket_result_point_y_reg_449;
wire   [255:0] bucket_result_point_z_fu_336_p3;
reg   [255:0] bucket_result_point_z_reg_454;
wire   [255:0] bucket_result_point_t_fu_343_p3;
reg   [255:0] bucket_result_point_t_reg_459;
wire   [63:0] zext_ln572_fu_285_p1;
wire    ap_block_pp0_stage0;
reg   [10:0] j_fu_76;
wire   [10:0] j_2_fu_301_p2;
wire    ap_loop_init;
reg   [10:0] ap_sig_allocacmp_j_load;
reg   [4:0] i_fu_80;
reg   [4:0] ap_sig_allocacmp_i_load;
reg   [14:0] indvar_flatten6_fu_84;
wire   [14:0] add_ln568_fu_223_p2;
reg   [14:0] ap_sig_allocacmp_indvar_flatten6_load;
reg    ap_block_pp0_stage0_01001_grp1;
reg    ap_block_pp0_stage0_11001_grp1;
reg    buckets_x_ce0_local;
reg    buckets_x_1_ce0_local;
reg    buckets_y_ce0_local;
reg    buckets_y_1_ce0_local;
reg    buckets_z_ce0_local;
reg    buckets_z_1_ce0_local;
reg    buckets_t_ce0_local;
reg    buckets_t_1_ce0_local;
wire   [0:0] icmp_ln570_fu_241_p2;
wire   [4:0] i_4_fu_235_p2;
wire   [10:0] select_ln568_fu_247_p3;
wire   [8:0] lshr_ln1_fu_267_p4;
wire   [13:0] tmp_3_fu_277_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 j_fu_76 = 11'd0;
#0 i_fu_80 = 5'd0;
#0 indvar_flatten6_fu_84 = 15'd0;
#0 ap_done_reg = 1'b0;
end

pippenger_control_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln568_fu_217_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_80 <= select_ln568_1_fu_255_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_80 <= 5'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln568_fu_217_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten6_fu_84 <= add_ln568_fu_223_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten6_fu_84 <= 15'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln568_fu_217_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            j_fu_76 <= j_2_fu_301_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            j_fu_76 <= 11'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        bucket_result_point_t_reg_459 <= bucket_result_point_t_fu_343_p3;
        bucket_result_point_x_reg_444 <= bucket_result_point_x_fu_322_p3;
        bucket_result_point_y_reg_449 <= bucket_result_point_y_fu_329_p3;
        bucket_result_point_z_reg_454 <= bucket_result_point_z_fu_336_p3;
        select_ln568_1_reg_386 <= select_ln568_1_fu_255_p3;
        select_ln568_1_reg_386_pp0_iter1_reg <= select_ln568_1_reg_386;
        trunc_ln570_reg_391 <= trunc_ln570_fu_263_p1;
        trunc_ln577_reg_439 <= trunc_ln577_fu_297_p1;
        trunc_ln577_reg_439_pp0_iter1_reg <= trunc_ln577_reg_439;
    end
end

always @ (*) begin
    if (((icmp_ln568_fu_217_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_load = 5'd0;
    end else begin
        ap_sig_allocacmp_i_load = i_fu_80;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten6_load = 15'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten6_load = indvar_flatten6_fu_84;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_j_load = 11'd0;
    end else begin
        ap_sig_allocacmp_j_load = j_fu_76;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buckets_t_1_ce0_local = 1'b1;
    end else begin
        buckets_t_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buckets_t_ce0_local = 1'b1;
    end else begin
        buckets_t_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buckets_x_1_ce0_local = 1'b1;
    end else begin
        buckets_x_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buckets_x_ce0_local = 1'b1;
    end else begin
        buckets_x_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buckets_y_1_ce0_local = 1'b1;
    end else begin
        buckets_y_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buckets_y_ce0_local = 1'b1;
    end else begin
        buckets_y_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buckets_z_1_ce0_local = 1'b1;
    end else begin
        buckets_z_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buckets_z_ce0_local = 1'b1;
    end else begin
        buckets_z_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_grp1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        out_stream_blk_n = out_stream_full_n;
    end else begin
        out_stream_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        out_stream_write = 1'b1;
    end else begin
        out_stream_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln568_fu_223_p2 = (ap_sig_allocacmp_indvar_flatten6_load + 15'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001_grp1 = ((out_stream_full_n == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((out_stream_full_n == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = ((out_stream_full_n == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1));
end

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((out_stream_full_n == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign bucket_result_point_t_fu_343_p3 = ((trunc_ln570_reg_391[0:0] == 1'b1) ? buckets_t_1_q0 : buckets_t_q0);

assign bucket_result_point_x_fu_322_p3 = ((trunc_ln570_reg_391[0:0] == 1'b1) ? buckets_x_1_q0 : buckets_x_q0);

assign bucket_result_point_y_fu_329_p3 = ((trunc_ln570_reg_391[0:0] == 1'b1) ? buckets_y_1_q0 : buckets_y_q0);

assign bucket_result_point_z_fu_336_p3 = ((trunc_ln570_reg_391[0:0] == 1'b1) ? buckets_z_1_q0 : buckets_z_q0);

assign buckets_t_1_address0 = zext_ln572_fu_285_p1;

assign buckets_t_1_ce0 = buckets_t_1_ce0_local;

assign buckets_t_address0 = zext_ln572_fu_285_p1;

assign buckets_t_ce0 = buckets_t_ce0_local;

assign buckets_x_1_address0 = zext_ln572_fu_285_p1;

assign buckets_x_1_ce0 = buckets_x_1_ce0_local;

assign buckets_x_address0 = zext_ln572_fu_285_p1;

assign buckets_x_ce0 = buckets_x_ce0_local;

assign buckets_y_1_address0 = zext_ln572_fu_285_p1;

assign buckets_y_1_ce0 = buckets_y_1_ce0_local;

assign buckets_y_address0 = zext_ln572_fu_285_p1;

assign buckets_y_ce0 = buckets_y_ce0_local;

assign buckets_z_1_address0 = zext_ln572_fu_285_p1;

assign buckets_z_1_ce0 = buckets_z_1_ce0_local;

assign buckets_z_address0 = zext_ln572_fu_285_p1;

assign buckets_z_ce0 = buckets_z_ce0_local;

assign i_4_fu_235_p2 = (ap_sig_allocacmp_i_load + 5'd1);

assign icmp_ln568_fu_217_p2 = ((ap_sig_allocacmp_indvar_flatten6_load == 15'd26624) ? 1'b1 : 1'b0);

assign icmp_ln570_fu_241_p2 = ((ap_sig_allocacmp_j_load == 11'd1024) ? 1'b1 : 1'b0);

assign j_2_fu_301_p2 = (select_ln568_fu_247_p3 + 11'd1);

assign lshr_ln1_fu_267_p4 = {{select_ln568_fu_247_p3[9:1]}};

assign out_stream_din = {{{{{{select_ln568_1_reg_386_pp0_iter1_reg}, {trunc_ln577_reg_439_pp0_iter1_reg}}, {bucket_result_point_t_reg_459}}, {bucket_result_point_z_reg_454}}, {bucket_result_point_y_reg_449}}, {bucket_result_point_x_reg_444}};

assign select_ln568_1_fu_255_p3 = ((icmp_ln570_fu_241_p2[0:0] == 1'b1) ? i_4_fu_235_p2 : ap_sig_allocacmp_i_load);

assign select_ln568_fu_247_p3 = ((icmp_ln570_fu_241_p2[0:0] == 1'b1) ? 11'd0 : ap_sig_allocacmp_j_load);

assign tmp_3_fu_277_p3 = {{select_ln568_1_fu_255_p3}, {lshr_ln1_fu_267_p4}};

assign trunc_ln570_fu_263_p1 = select_ln568_fu_247_p3[0:0];

assign trunc_ln577_fu_297_p1 = select_ln568_fu_247_p3[9:0];

assign zext_ln572_fu_285_p1 = tmp_3_fu_277_p3;

endmodule //pippenger_control_pippenger_control_Pipeline_AGGREGATE_AND_OUT_VITIS_LOOP_570_1
