// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================
`timescale 1 ns / 1 ps
module pippenger_control_pippenger_control_Pipeline_VITIS_LOOP_571_1_VITIS_LOOP_573_2_buckets_y_0_RAM_bkb (
    address0, ce0, q0, 
    reset, clk);

parameter DataWidth = 1;
parameter AddressWidth = 14;
parameter AddressRange = 13312;
 
input[AddressWidth-1:0] address0;
input ce0;
output reg[DataWidth-1:0] q0;

input reset;
input clk;

 
(* rom_style = "block" *)reg [DataWidth-1:0] rom0[0:AddressRange-1];


initial begin
     
    $readmemh("./pippenger_control_pippenger_control_Pipeline_VITIS_LOOP_571_1_VITIS_LOOP_573_2_buckets_y_0_RAM_bkb.dat", rom0);
end

  
always @(posedge clk) 
begin 
    if (ce0) 
    begin
        q0 <= rom0[address0];
    end
end


endmodule

