// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="msm_msm,hls_ip_2024_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu7ev-ffvc1156-2-e,HLS_INPUT_CLOCK=4.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=2.920000,HLS_SYN_LAT=-1,HLS_SYN_TPT=-1,HLS_SYN_MEM=239,HLS_SYN_DSP=0,HLS_SYN_FF=45661,HLS_SYN_LUT=60949,HLS_VERSION=2024_2}" *)

module msm (
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        ap_clk,
        ap_rst_n,
        m_axi_gmem0_AWVALID,
        m_axi_gmem0_AWREADY,
        m_axi_gmem0_AWADDR,
        m_axi_gmem0_AWID,
        m_axi_gmem0_AWLEN,
        m_axi_gmem0_AWSIZE,
        m_axi_gmem0_AWBURST,
        m_axi_gmem0_AWLOCK,
        m_axi_gmem0_AWCACHE,
        m_axi_gmem0_AWPROT,
        m_axi_gmem0_AWQOS,
        m_axi_gmem0_AWREGION,
        m_axi_gmem0_AWUSER,
        m_axi_gmem0_WVALID,
        m_axi_gmem0_WREADY,
        m_axi_gmem0_WDATA,
        m_axi_gmem0_WSTRB,
        m_axi_gmem0_WLAST,
        m_axi_gmem0_WID,
        m_axi_gmem0_WUSER,
        m_axi_gmem0_ARVALID,
        m_axi_gmem0_ARREADY,
        m_axi_gmem0_ARADDR,
        m_axi_gmem0_ARID,
        m_axi_gmem0_ARLEN,
        m_axi_gmem0_ARSIZE,
        m_axi_gmem0_ARBURST,
        m_axi_gmem0_ARLOCK,
        m_axi_gmem0_ARCACHE,
        m_axi_gmem0_ARPROT,
        m_axi_gmem0_ARQOS,
        m_axi_gmem0_ARREGION,
        m_axi_gmem0_ARUSER,
        m_axi_gmem0_RVALID,
        m_axi_gmem0_RREADY,
        m_axi_gmem0_RDATA,
        m_axi_gmem0_RLAST,
        m_axi_gmem0_RID,
        m_axi_gmem0_RUSER,
        m_axi_gmem0_RRESP,
        m_axi_gmem0_BVALID,
        m_axi_gmem0_BREADY,
        m_axi_gmem0_BRESP,
        m_axi_gmem0_BID,
        m_axi_gmem0_BUSER,
        m_axi_gmem1_AWVALID,
        m_axi_gmem1_AWREADY,
        m_axi_gmem1_AWADDR,
        m_axi_gmem1_AWID,
        m_axi_gmem1_AWLEN,
        m_axi_gmem1_AWSIZE,
        m_axi_gmem1_AWBURST,
        m_axi_gmem1_AWLOCK,
        m_axi_gmem1_AWCACHE,
        m_axi_gmem1_AWPROT,
        m_axi_gmem1_AWQOS,
        m_axi_gmem1_AWREGION,
        m_axi_gmem1_AWUSER,
        m_axi_gmem1_WVALID,
        m_axi_gmem1_WREADY,
        m_axi_gmem1_WDATA,
        m_axi_gmem1_WSTRB,
        m_axi_gmem1_WLAST,
        m_axi_gmem1_WID,
        m_axi_gmem1_WUSER,
        m_axi_gmem1_ARVALID,
        m_axi_gmem1_ARREADY,
        m_axi_gmem1_ARADDR,
        m_axi_gmem1_ARID,
        m_axi_gmem1_ARLEN,
        m_axi_gmem1_ARSIZE,
        m_axi_gmem1_ARBURST,
        m_axi_gmem1_ARLOCK,
        m_axi_gmem1_ARCACHE,
        m_axi_gmem1_ARPROT,
        m_axi_gmem1_ARQOS,
        m_axi_gmem1_ARREGION,
        m_axi_gmem1_ARUSER,
        m_axi_gmem1_RVALID,
        m_axi_gmem1_RREADY,
        m_axi_gmem1_RDATA,
        m_axi_gmem1_RLAST,
        m_axi_gmem1_RID,
        m_axi_gmem1_RUSER,
        m_axi_gmem1_RRESP,
        m_axi_gmem1_BVALID,
        m_axi_gmem1_BREADY,
        m_axi_gmem1_BRESP,
        m_axi_gmem1_BID,
        m_axi_gmem1_BUSER,
        m_axi_gmem2_AWVALID,
        m_axi_gmem2_AWREADY,
        m_axi_gmem2_AWADDR,
        m_axi_gmem2_AWID,
        m_axi_gmem2_AWLEN,
        m_axi_gmem2_AWSIZE,
        m_axi_gmem2_AWBURST,
        m_axi_gmem2_AWLOCK,
        m_axi_gmem2_AWCACHE,
        m_axi_gmem2_AWPROT,
        m_axi_gmem2_AWQOS,
        m_axi_gmem2_AWREGION,
        m_axi_gmem2_AWUSER,
        m_axi_gmem2_WVALID,
        m_axi_gmem2_WREADY,
        m_axi_gmem2_WDATA,
        m_axi_gmem2_WSTRB,
        m_axi_gmem2_WLAST,
        m_axi_gmem2_WID,
        m_axi_gmem2_WUSER,
        m_axi_gmem2_ARVALID,
        m_axi_gmem2_ARREADY,
        m_axi_gmem2_ARADDR,
        m_axi_gmem2_ARID,
        m_axi_gmem2_ARLEN,
        m_axi_gmem2_ARSIZE,
        m_axi_gmem2_ARBURST,
        m_axi_gmem2_ARLOCK,
        m_axi_gmem2_ARCACHE,
        m_axi_gmem2_ARPROT,
        m_axi_gmem2_ARQOS,
        m_axi_gmem2_ARREGION,
        m_axi_gmem2_ARUSER,
        m_axi_gmem2_RVALID,
        m_axi_gmem2_RREADY,
        m_axi_gmem2_RDATA,
        m_axi_gmem2_RLAST,
        m_axi_gmem2_RID,
        m_axi_gmem2_RUSER,
        m_axi_gmem2_RRESP,
        m_axi_gmem2_BVALID,
        m_axi_gmem2_BREADY,
        m_axi_gmem2_BRESP,
        m_axi_gmem2_BID,
        m_axi_gmem2_BUSER,
        m_axi_gmem3_AWVALID,
        m_axi_gmem3_AWREADY,
        m_axi_gmem3_AWADDR,
        m_axi_gmem3_AWID,
        m_axi_gmem3_AWLEN,
        m_axi_gmem3_AWSIZE,
        m_axi_gmem3_AWBURST,
        m_axi_gmem3_AWLOCK,
        m_axi_gmem3_AWCACHE,
        m_axi_gmem3_AWPROT,
        m_axi_gmem3_AWQOS,
        m_axi_gmem3_AWREGION,
        m_axi_gmem3_AWUSER,
        m_axi_gmem3_WVALID,
        m_axi_gmem3_WREADY,
        m_axi_gmem3_WDATA,
        m_axi_gmem3_WSTRB,
        m_axi_gmem3_WLAST,
        m_axi_gmem3_WID,
        m_axi_gmem3_WUSER,
        m_axi_gmem3_ARVALID,
        m_axi_gmem3_ARREADY,
        m_axi_gmem3_ARADDR,
        m_axi_gmem3_ARID,
        m_axi_gmem3_ARLEN,
        m_axi_gmem3_ARSIZE,
        m_axi_gmem3_ARBURST,
        m_axi_gmem3_ARLOCK,
        m_axi_gmem3_ARCACHE,
        m_axi_gmem3_ARPROT,
        m_axi_gmem3_ARQOS,
        m_axi_gmem3_ARREGION,
        m_axi_gmem3_ARUSER,
        m_axi_gmem3_RVALID,
        m_axi_gmem3_RREADY,
        m_axi_gmem3_RDATA,
        m_axi_gmem3_RLAST,
        m_axi_gmem3_RID,
        m_axi_gmem3_RUSER,
        m_axi_gmem3_RRESP,
        m_axi_gmem3_BVALID,
        m_axi_gmem3_BREADY,
        m_axi_gmem3_BRESP,
        m_axi_gmem3_BID,
        m_axi_gmem3_BUSER,
        scalar_array,
        degree,
        ap_start,
        ap_done,
        ap_ready,
        ap_idle
);

parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 7;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM0_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM0_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM0_DATA_WIDTH = 256;
parameter    C_M_AXI_GMEM0_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_USER_VALUE = 0;
parameter    C_M_AXI_GMEM0_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM0_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM1_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM1_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM1_DATA_WIDTH = 256;
parameter    C_M_AXI_GMEM1_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_USER_VALUE = 0;
parameter    C_M_AXI_GMEM1_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM1_CACHE_VALUE = 3;
parameter    C_M_AXI_GMEM2_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM2_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM2_DATA_WIDTH = 256;
parameter    C_M_AXI_GMEM2_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM2_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM2_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM2_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM2_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM2_USER_VALUE = 0;
parameter    C_M_AXI_GMEM2_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM2_CACHE_VALUE = 3;
parameter    C_M_AXI_GMEM3_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM3_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM3_DATA_WIDTH = 256;
parameter    C_M_AXI_GMEM3_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM3_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM3_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM3_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM3_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM3_USER_VALUE = 0;
parameter    C_M_AXI_GMEM3_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM3_CACHE_VALUE = 3;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM0_WSTRB_WIDTH = (256 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM1_WSTRB_WIDTH = (256 / 8);
parameter C_M_AXI_GMEM2_WSTRB_WIDTH = (256 / 8);
parameter C_M_AXI_GMEM3_WSTRB_WIDTH = (256 / 8);

input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
input   ap_clk;
input   ap_rst_n;
output   m_axi_gmem0_AWVALID;
input   m_axi_gmem0_AWREADY;
output  [C_M_AXI_GMEM0_ADDR_WIDTH - 1:0] m_axi_gmem0_AWADDR;
output  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_AWID;
output  [7:0] m_axi_gmem0_AWLEN;
output  [2:0] m_axi_gmem0_AWSIZE;
output  [1:0] m_axi_gmem0_AWBURST;
output  [1:0] m_axi_gmem0_AWLOCK;
output  [3:0] m_axi_gmem0_AWCACHE;
output  [2:0] m_axi_gmem0_AWPROT;
output  [3:0] m_axi_gmem0_AWQOS;
output  [3:0] m_axi_gmem0_AWREGION;
output  [C_M_AXI_GMEM0_AWUSER_WIDTH - 1:0] m_axi_gmem0_AWUSER;
output   m_axi_gmem0_WVALID;
input   m_axi_gmem0_WREADY;
output  [C_M_AXI_GMEM0_DATA_WIDTH - 1:0] m_axi_gmem0_WDATA;
output  [C_M_AXI_GMEM0_WSTRB_WIDTH - 1:0] m_axi_gmem0_WSTRB;
output   m_axi_gmem0_WLAST;
output  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_WID;
output  [C_M_AXI_GMEM0_WUSER_WIDTH - 1:0] m_axi_gmem0_WUSER;
output   m_axi_gmem0_ARVALID;
input   m_axi_gmem0_ARREADY;
output  [C_M_AXI_GMEM0_ADDR_WIDTH - 1:0] m_axi_gmem0_ARADDR;
output  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_ARID;
output  [7:0] m_axi_gmem0_ARLEN;
output  [2:0] m_axi_gmem0_ARSIZE;
output  [1:0] m_axi_gmem0_ARBURST;
output  [1:0] m_axi_gmem0_ARLOCK;
output  [3:0] m_axi_gmem0_ARCACHE;
output  [2:0] m_axi_gmem0_ARPROT;
output  [3:0] m_axi_gmem0_ARQOS;
output  [3:0] m_axi_gmem0_ARREGION;
output  [C_M_AXI_GMEM0_ARUSER_WIDTH - 1:0] m_axi_gmem0_ARUSER;
input   m_axi_gmem0_RVALID;
output   m_axi_gmem0_RREADY;
input  [C_M_AXI_GMEM0_DATA_WIDTH - 1:0] m_axi_gmem0_RDATA;
input   m_axi_gmem0_RLAST;
input  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_RID;
input  [C_M_AXI_GMEM0_RUSER_WIDTH - 1:0] m_axi_gmem0_RUSER;
input  [1:0] m_axi_gmem0_RRESP;
input   m_axi_gmem0_BVALID;
output   m_axi_gmem0_BREADY;
input  [1:0] m_axi_gmem0_BRESP;
input  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_BID;
input  [C_M_AXI_GMEM0_BUSER_WIDTH - 1:0] m_axi_gmem0_BUSER;
output   m_axi_gmem1_AWVALID;
input   m_axi_gmem1_AWREADY;
output  [C_M_AXI_GMEM1_ADDR_WIDTH - 1:0] m_axi_gmem1_AWADDR;
output  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_AWID;
output  [7:0] m_axi_gmem1_AWLEN;
output  [2:0] m_axi_gmem1_AWSIZE;
output  [1:0] m_axi_gmem1_AWBURST;
output  [1:0] m_axi_gmem1_AWLOCK;
output  [3:0] m_axi_gmem1_AWCACHE;
output  [2:0] m_axi_gmem1_AWPROT;
output  [3:0] m_axi_gmem1_AWQOS;
output  [3:0] m_axi_gmem1_AWREGION;
output  [C_M_AXI_GMEM1_AWUSER_WIDTH - 1:0] m_axi_gmem1_AWUSER;
output   m_axi_gmem1_WVALID;
input   m_axi_gmem1_WREADY;
output  [C_M_AXI_GMEM1_DATA_WIDTH - 1:0] m_axi_gmem1_WDATA;
output  [C_M_AXI_GMEM1_WSTRB_WIDTH - 1:0] m_axi_gmem1_WSTRB;
output   m_axi_gmem1_WLAST;
output  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_WID;
output  [C_M_AXI_GMEM1_WUSER_WIDTH - 1:0] m_axi_gmem1_WUSER;
output   m_axi_gmem1_ARVALID;
input   m_axi_gmem1_ARREADY;
output  [C_M_AXI_GMEM1_ADDR_WIDTH - 1:0] m_axi_gmem1_ARADDR;
output  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_ARID;
output  [7:0] m_axi_gmem1_ARLEN;
output  [2:0] m_axi_gmem1_ARSIZE;
output  [1:0] m_axi_gmem1_ARBURST;
output  [1:0] m_axi_gmem1_ARLOCK;
output  [3:0] m_axi_gmem1_ARCACHE;
output  [2:0] m_axi_gmem1_ARPROT;
output  [3:0] m_axi_gmem1_ARQOS;
output  [3:0] m_axi_gmem1_ARREGION;
output  [C_M_AXI_GMEM1_ARUSER_WIDTH - 1:0] m_axi_gmem1_ARUSER;
input   m_axi_gmem1_RVALID;
output   m_axi_gmem1_RREADY;
input  [C_M_AXI_GMEM1_DATA_WIDTH - 1:0] m_axi_gmem1_RDATA;
input   m_axi_gmem1_RLAST;
input  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_RID;
input  [C_M_AXI_GMEM1_RUSER_WIDTH - 1:0] m_axi_gmem1_RUSER;
input  [1:0] m_axi_gmem1_RRESP;
input   m_axi_gmem1_BVALID;
output   m_axi_gmem1_BREADY;
input  [1:0] m_axi_gmem1_BRESP;
input  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_BID;
input  [C_M_AXI_GMEM1_BUSER_WIDTH - 1:0] m_axi_gmem1_BUSER;
output   m_axi_gmem2_AWVALID;
input   m_axi_gmem2_AWREADY;
output  [C_M_AXI_GMEM2_ADDR_WIDTH - 1:0] m_axi_gmem2_AWADDR;
output  [C_M_AXI_GMEM2_ID_WIDTH - 1:0] m_axi_gmem2_AWID;
output  [7:0] m_axi_gmem2_AWLEN;
output  [2:0] m_axi_gmem2_AWSIZE;
output  [1:0] m_axi_gmem2_AWBURST;
output  [1:0] m_axi_gmem2_AWLOCK;
output  [3:0] m_axi_gmem2_AWCACHE;
output  [2:0] m_axi_gmem2_AWPROT;
output  [3:0] m_axi_gmem2_AWQOS;
output  [3:0] m_axi_gmem2_AWREGION;
output  [C_M_AXI_GMEM2_AWUSER_WIDTH - 1:0] m_axi_gmem2_AWUSER;
output   m_axi_gmem2_WVALID;
input   m_axi_gmem2_WREADY;
output  [C_M_AXI_GMEM2_DATA_WIDTH - 1:0] m_axi_gmem2_WDATA;
output  [C_M_AXI_GMEM2_WSTRB_WIDTH - 1:0] m_axi_gmem2_WSTRB;
output   m_axi_gmem2_WLAST;
output  [C_M_AXI_GMEM2_ID_WIDTH - 1:0] m_axi_gmem2_WID;
output  [C_M_AXI_GMEM2_WUSER_WIDTH - 1:0] m_axi_gmem2_WUSER;
output   m_axi_gmem2_ARVALID;
input   m_axi_gmem2_ARREADY;
output  [C_M_AXI_GMEM2_ADDR_WIDTH - 1:0] m_axi_gmem2_ARADDR;
output  [C_M_AXI_GMEM2_ID_WIDTH - 1:0] m_axi_gmem2_ARID;
output  [7:0] m_axi_gmem2_ARLEN;
output  [2:0] m_axi_gmem2_ARSIZE;
output  [1:0] m_axi_gmem2_ARBURST;
output  [1:0] m_axi_gmem2_ARLOCK;
output  [3:0] m_axi_gmem2_ARCACHE;
output  [2:0] m_axi_gmem2_ARPROT;
output  [3:0] m_axi_gmem2_ARQOS;
output  [3:0] m_axi_gmem2_ARREGION;
output  [C_M_AXI_GMEM2_ARUSER_WIDTH - 1:0] m_axi_gmem2_ARUSER;
input   m_axi_gmem2_RVALID;
output   m_axi_gmem2_RREADY;
input  [C_M_AXI_GMEM2_DATA_WIDTH - 1:0] m_axi_gmem2_RDATA;
input   m_axi_gmem2_RLAST;
input  [C_M_AXI_GMEM2_ID_WIDTH - 1:0] m_axi_gmem2_RID;
input  [C_M_AXI_GMEM2_RUSER_WIDTH - 1:0] m_axi_gmem2_RUSER;
input  [1:0] m_axi_gmem2_RRESP;
input   m_axi_gmem2_BVALID;
output   m_axi_gmem2_BREADY;
input  [1:0] m_axi_gmem2_BRESP;
input  [C_M_AXI_GMEM2_ID_WIDTH - 1:0] m_axi_gmem2_BID;
input  [C_M_AXI_GMEM2_BUSER_WIDTH - 1:0] m_axi_gmem2_BUSER;
output   m_axi_gmem3_AWVALID;
input   m_axi_gmem3_AWREADY;
output  [C_M_AXI_GMEM3_ADDR_WIDTH - 1:0] m_axi_gmem3_AWADDR;
output  [C_M_AXI_GMEM3_ID_WIDTH - 1:0] m_axi_gmem3_AWID;
output  [7:0] m_axi_gmem3_AWLEN;
output  [2:0] m_axi_gmem3_AWSIZE;
output  [1:0] m_axi_gmem3_AWBURST;
output  [1:0] m_axi_gmem3_AWLOCK;
output  [3:0] m_axi_gmem3_AWCACHE;
output  [2:0] m_axi_gmem3_AWPROT;
output  [3:0] m_axi_gmem3_AWQOS;
output  [3:0] m_axi_gmem3_AWREGION;
output  [C_M_AXI_GMEM3_AWUSER_WIDTH - 1:0] m_axi_gmem3_AWUSER;
output   m_axi_gmem3_WVALID;
input   m_axi_gmem3_WREADY;
output  [C_M_AXI_GMEM3_DATA_WIDTH - 1:0] m_axi_gmem3_WDATA;
output  [C_M_AXI_GMEM3_WSTRB_WIDTH - 1:0] m_axi_gmem3_WSTRB;
output   m_axi_gmem3_WLAST;
output  [C_M_AXI_GMEM3_ID_WIDTH - 1:0] m_axi_gmem3_WID;
output  [C_M_AXI_GMEM3_WUSER_WIDTH - 1:0] m_axi_gmem3_WUSER;
output   m_axi_gmem3_ARVALID;
input   m_axi_gmem3_ARREADY;
output  [C_M_AXI_GMEM3_ADDR_WIDTH - 1:0] m_axi_gmem3_ARADDR;
output  [C_M_AXI_GMEM3_ID_WIDTH - 1:0] m_axi_gmem3_ARID;
output  [7:0] m_axi_gmem3_ARLEN;
output  [2:0] m_axi_gmem3_ARSIZE;
output  [1:0] m_axi_gmem3_ARBURST;
output  [1:0] m_axi_gmem3_ARLOCK;
output  [3:0] m_axi_gmem3_ARCACHE;
output  [2:0] m_axi_gmem3_ARPROT;
output  [3:0] m_axi_gmem3_ARQOS;
output  [3:0] m_axi_gmem3_ARREGION;
output  [C_M_AXI_GMEM3_ARUSER_WIDTH - 1:0] m_axi_gmem3_ARUSER;
input   m_axi_gmem3_RVALID;
output   m_axi_gmem3_RREADY;
input  [C_M_AXI_GMEM3_DATA_WIDTH - 1:0] m_axi_gmem3_RDATA;
input   m_axi_gmem3_RLAST;
input  [C_M_AXI_GMEM3_ID_WIDTH - 1:0] m_axi_gmem3_RID;
input  [C_M_AXI_GMEM3_RUSER_WIDTH - 1:0] m_axi_gmem3_RUSER;
input  [1:0] m_axi_gmem3_RRESP;
input   m_axi_gmem3_BVALID;
output   m_axi_gmem3_BREADY;
input  [1:0] m_axi_gmem3_BRESP;
input  [C_M_AXI_GMEM3_ID_WIDTH - 1:0] m_axi_gmem3_BID;
input  [C_M_AXI_GMEM3_BUSER_WIDTH - 1:0] m_axi_gmem3_BUSER;
input  [255:0] scalar_array;
input  [31:0] degree;
input   ap_start;
output   ap_done;
output   ap_ready;
output   ap_idle;

 reg    ap_rst_n_inv;
wire   [63:0] x_array;
wire   [63:0] y_array;
wire   [63:0] z_array;
wire   [63:0] t_array;
wire   [63:0] result_x;
wire   [63:0] result_y;
wire   [63:0] result_z;
wire   [63:0] result_t;
wire    gmem0_0_AWREADY;
wire    gmem0_0_WREADY;
wire    gmem0_0_ARREADY;
wire    gmem0_0_RVALID;
wire   [255:0] gmem0_0_RDATA;
wire    gmem0_0_RLAST;
wire   [0:0] gmem0_0_RID;
wire   [8:0] gmem0_0_RFIFONUM;
wire   [0:0] gmem0_0_RUSER;
wire   [1:0] gmem0_0_RRESP;
wire    gmem0_0_BVALID;
wire   [1:0] gmem0_0_BRESP;
wire   [0:0] gmem0_0_BID;
wire   [0:0] gmem0_0_BUSER;
wire    gmem1_0_AWREADY;
wire    gmem1_0_WREADY;
wire    gmem1_0_ARREADY;
wire    gmem1_0_RVALID;
wire   [255:0] gmem1_0_RDATA;
wire    gmem1_0_RLAST;
wire   [0:0] gmem1_0_RID;
wire   [8:0] gmem1_0_RFIFONUM;
wire   [0:0] gmem1_0_RUSER;
wire   [1:0] gmem1_0_RRESP;
wire    gmem1_0_BVALID;
wire   [1:0] gmem1_0_BRESP;
wire   [0:0] gmem1_0_BID;
wire   [0:0] gmem1_0_BUSER;
wire    gmem2_0_AWREADY;
wire    gmem2_0_WREADY;
wire    gmem2_0_ARREADY;
wire    gmem2_0_RVALID;
wire   [255:0] gmem2_0_RDATA;
wire    gmem2_0_RLAST;
wire   [0:0] gmem2_0_RID;
wire   [8:0] gmem2_0_RFIFONUM;
wire   [0:0] gmem2_0_RUSER;
wire   [1:0] gmem2_0_RRESP;
wire    gmem2_0_BVALID;
wire   [1:0] gmem2_0_BRESP;
wire   [0:0] gmem2_0_BID;
wire   [0:0] gmem2_0_BUSER;
wire    gmem3_0_AWREADY;
wire    gmem3_0_WREADY;
wire    gmem3_0_ARREADY;
wire    gmem3_0_RVALID;
wire   [255:0] gmem3_0_RDATA;
wire    gmem3_0_RLAST;
wire   [0:0] gmem3_0_RID;
wire   [8:0] gmem3_0_RFIFONUM;
wire   [0:0] gmem3_0_RUSER;
wire   [1:0] gmem3_0_RRESP;
wire    gmem3_0_BVALID;
wire   [1:0] gmem3_0_BRESP;
wire   [0:0] gmem3_0_BID;
wire   [0:0] gmem3_0_BUSER;
wire    entry_proc_U0_ap_start;
wire    entry_proc_U0_ap_done;
wire    entry_proc_U0_ap_continue;
wire    entry_proc_U0_ap_idle;
wire    entry_proc_U0_ap_ready;
wire    entry_proc_U0_start_out;
wire    entry_proc_U0_start_write;
wire   [63:0] entry_proc_U0_result_x_c_din;
wire    entry_proc_U0_result_x_c_write;
wire   [63:0] entry_proc_U0_result_y_c_din;
wire    entry_proc_U0_result_y_c_write;
wire   [63:0] entry_proc_U0_result_z_c_din;
wire    entry_proc_U0_result_z_c_write;
wire   [63:0] entry_proc_U0_result_t_c_din;
wire    entry_proc_U0_result_t_c_write;
wire    data_loader_U0_ap_start;
wire    data_loader_U0_ap_done;
wire    data_loader_U0_ap_continue;
wire    data_loader_U0_ap_idle;
wire    data_loader_U0_ap_ready;
wire    data_loader_U0_m_axi_gmem0_0_AWVALID;
wire   [63:0] data_loader_U0_m_axi_gmem0_0_AWADDR;
wire   [0:0] data_loader_U0_m_axi_gmem0_0_AWID;
wire   [31:0] data_loader_U0_m_axi_gmem0_0_AWLEN;
wire   [2:0] data_loader_U0_m_axi_gmem0_0_AWSIZE;
wire   [1:0] data_loader_U0_m_axi_gmem0_0_AWBURST;
wire   [1:0] data_loader_U0_m_axi_gmem0_0_AWLOCK;
wire   [3:0] data_loader_U0_m_axi_gmem0_0_AWCACHE;
wire   [2:0] data_loader_U0_m_axi_gmem0_0_AWPROT;
wire   [3:0] data_loader_U0_m_axi_gmem0_0_AWQOS;
wire   [3:0] data_loader_U0_m_axi_gmem0_0_AWREGION;
wire   [0:0] data_loader_U0_m_axi_gmem0_0_AWUSER;
wire    data_loader_U0_m_axi_gmem0_0_WVALID;
wire   [255:0] data_loader_U0_m_axi_gmem0_0_WDATA;
wire   [31:0] data_loader_U0_m_axi_gmem0_0_WSTRB;
wire    data_loader_U0_m_axi_gmem0_0_WLAST;
wire   [0:0] data_loader_U0_m_axi_gmem0_0_WID;
wire   [0:0] data_loader_U0_m_axi_gmem0_0_WUSER;
wire    data_loader_U0_m_axi_gmem0_0_ARVALID;
wire   [63:0] data_loader_U0_m_axi_gmem0_0_ARADDR;
wire   [0:0] data_loader_U0_m_axi_gmem0_0_ARID;
wire   [31:0] data_loader_U0_m_axi_gmem0_0_ARLEN;
wire   [2:0] data_loader_U0_m_axi_gmem0_0_ARSIZE;
wire   [1:0] data_loader_U0_m_axi_gmem0_0_ARBURST;
wire   [1:0] data_loader_U0_m_axi_gmem0_0_ARLOCK;
wire   [3:0] data_loader_U0_m_axi_gmem0_0_ARCACHE;
wire   [2:0] data_loader_U0_m_axi_gmem0_0_ARPROT;
wire   [3:0] data_loader_U0_m_axi_gmem0_0_ARQOS;
wire   [3:0] data_loader_U0_m_axi_gmem0_0_ARREGION;
wire   [0:0] data_loader_U0_m_axi_gmem0_0_ARUSER;
wire    data_loader_U0_m_axi_gmem0_0_RREADY;
wire    data_loader_U0_m_axi_gmem0_0_BREADY;
wire    data_loader_U0_m_axi_gmem1_0_AWVALID;
wire   [63:0] data_loader_U0_m_axi_gmem1_0_AWADDR;
wire   [0:0] data_loader_U0_m_axi_gmem1_0_AWID;
wire   [31:0] data_loader_U0_m_axi_gmem1_0_AWLEN;
wire   [2:0] data_loader_U0_m_axi_gmem1_0_AWSIZE;
wire   [1:0] data_loader_U0_m_axi_gmem1_0_AWBURST;
wire   [1:0] data_loader_U0_m_axi_gmem1_0_AWLOCK;
wire   [3:0] data_loader_U0_m_axi_gmem1_0_AWCACHE;
wire   [2:0] data_loader_U0_m_axi_gmem1_0_AWPROT;
wire   [3:0] data_loader_U0_m_axi_gmem1_0_AWQOS;
wire   [3:0] data_loader_U0_m_axi_gmem1_0_AWREGION;
wire   [0:0] data_loader_U0_m_axi_gmem1_0_AWUSER;
wire    data_loader_U0_m_axi_gmem1_0_WVALID;
wire   [255:0] data_loader_U0_m_axi_gmem1_0_WDATA;
wire   [31:0] data_loader_U0_m_axi_gmem1_0_WSTRB;
wire    data_loader_U0_m_axi_gmem1_0_WLAST;
wire   [0:0] data_loader_U0_m_axi_gmem1_0_WID;
wire   [0:0] data_loader_U0_m_axi_gmem1_0_WUSER;
wire    data_loader_U0_m_axi_gmem1_0_ARVALID;
wire   [63:0] data_loader_U0_m_axi_gmem1_0_ARADDR;
wire   [0:0] data_loader_U0_m_axi_gmem1_0_ARID;
wire   [31:0] data_loader_U0_m_axi_gmem1_0_ARLEN;
wire   [2:0] data_loader_U0_m_axi_gmem1_0_ARSIZE;
wire   [1:0] data_loader_U0_m_axi_gmem1_0_ARBURST;
wire   [1:0] data_loader_U0_m_axi_gmem1_0_ARLOCK;
wire   [3:0] data_loader_U0_m_axi_gmem1_0_ARCACHE;
wire   [2:0] data_loader_U0_m_axi_gmem1_0_ARPROT;
wire   [3:0] data_loader_U0_m_axi_gmem1_0_ARQOS;
wire   [3:0] data_loader_U0_m_axi_gmem1_0_ARREGION;
wire   [0:0] data_loader_U0_m_axi_gmem1_0_ARUSER;
wire    data_loader_U0_m_axi_gmem1_0_RREADY;
wire    data_loader_U0_m_axi_gmem1_0_BREADY;
wire    data_loader_U0_m_axi_gmem2_0_AWVALID;
wire   [63:0] data_loader_U0_m_axi_gmem2_0_AWADDR;
wire   [0:0] data_loader_U0_m_axi_gmem2_0_AWID;
wire   [31:0] data_loader_U0_m_axi_gmem2_0_AWLEN;
wire   [2:0] data_loader_U0_m_axi_gmem2_0_AWSIZE;
wire   [1:0] data_loader_U0_m_axi_gmem2_0_AWBURST;
wire   [1:0] data_loader_U0_m_axi_gmem2_0_AWLOCK;
wire   [3:0] data_loader_U0_m_axi_gmem2_0_AWCACHE;
wire   [2:0] data_loader_U0_m_axi_gmem2_0_AWPROT;
wire   [3:0] data_loader_U0_m_axi_gmem2_0_AWQOS;
wire   [3:0] data_loader_U0_m_axi_gmem2_0_AWREGION;
wire   [0:0] data_loader_U0_m_axi_gmem2_0_AWUSER;
wire    data_loader_U0_m_axi_gmem2_0_WVALID;
wire   [255:0] data_loader_U0_m_axi_gmem2_0_WDATA;
wire   [31:0] data_loader_U0_m_axi_gmem2_0_WSTRB;
wire    data_loader_U0_m_axi_gmem2_0_WLAST;
wire   [0:0] data_loader_U0_m_axi_gmem2_0_WID;
wire   [0:0] data_loader_U0_m_axi_gmem2_0_WUSER;
wire    data_loader_U0_m_axi_gmem2_0_ARVALID;
wire   [63:0] data_loader_U0_m_axi_gmem2_0_ARADDR;
wire   [0:0] data_loader_U0_m_axi_gmem2_0_ARID;
wire   [31:0] data_loader_U0_m_axi_gmem2_0_ARLEN;
wire   [2:0] data_loader_U0_m_axi_gmem2_0_ARSIZE;
wire   [1:0] data_loader_U0_m_axi_gmem2_0_ARBURST;
wire   [1:0] data_loader_U0_m_axi_gmem2_0_ARLOCK;
wire   [3:0] data_loader_U0_m_axi_gmem2_0_ARCACHE;
wire   [2:0] data_loader_U0_m_axi_gmem2_0_ARPROT;
wire   [3:0] data_loader_U0_m_axi_gmem2_0_ARQOS;
wire   [3:0] data_loader_U0_m_axi_gmem2_0_ARREGION;
wire   [0:0] data_loader_U0_m_axi_gmem2_0_ARUSER;
wire    data_loader_U0_m_axi_gmem2_0_RREADY;
wire    data_loader_U0_m_axi_gmem2_0_BREADY;
wire    data_loader_U0_m_axi_gmem3_0_AWVALID;
wire   [63:0] data_loader_U0_m_axi_gmem3_0_AWADDR;
wire   [0:0] data_loader_U0_m_axi_gmem3_0_AWID;
wire   [31:0] data_loader_U0_m_axi_gmem3_0_AWLEN;
wire   [2:0] data_loader_U0_m_axi_gmem3_0_AWSIZE;
wire   [1:0] data_loader_U0_m_axi_gmem3_0_AWBURST;
wire   [1:0] data_loader_U0_m_axi_gmem3_0_AWLOCK;
wire   [3:0] data_loader_U0_m_axi_gmem3_0_AWCACHE;
wire   [2:0] data_loader_U0_m_axi_gmem3_0_AWPROT;
wire   [3:0] data_loader_U0_m_axi_gmem3_0_AWQOS;
wire   [3:0] data_loader_U0_m_axi_gmem3_0_AWREGION;
wire   [0:0] data_loader_U0_m_axi_gmem3_0_AWUSER;
wire    data_loader_U0_m_axi_gmem3_0_WVALID;
wire   [255:0] data_loader_U0_m_axi_gmem3_0_WDATA;
wire   [31:0] data_loader_U0_m_axi_gmem3_0_WSTRB;
wire    data_loader_U0_m_axi_gmem3_0_WLAST;
wire   [0:0] data_loader_U0_m_axi_gmem3_0_WID;
wire   [0:0] data_loader_U0_m_axi_gmem3_0_WUSER;
wire    data_loader_U0_m_axi_gmem3_0_ARVALID;
wire   [63:0] data_loader_U0_m_axi_gmem3_0_ARADDR;
wire   [0:0] data_loader_U0_m_axi_gmem3_0_ARID;
wire   [31:0] data_loader_U0_m_axi_gmem3_0_ARLEN;
wire   [2:0] data_loader_U0_m_axi_gmem3_0_ARSIZE;
wire   [1:0] data_loader_U0_m_axi_gmem3_0_ARBURST;
wire   [1:0] data_loader_U0_m_axi_gmem3_0_ARLOCK;
wire   [3:0] data_loader_U0_m_axi_gmem3_0_ARCACHE;
wire   [2:0] data_loader_U0_m_axi_gmem3_0_ARPROT;
wire   [3:0] data_loader_U0_m_axi_gmem3_0_ARQOS;
wire   [3:0] data_loader_U0_m_axi_gmem3_0_ARREGION;
wire   [0:0] data_loader_U0_m_axi_gmem3_0_ARUSER;
wire    data_loader_U0_m_axi_gmem3_0_RREADY;
wire    data_loader_U0_m_axi_gmem3_0_BREADY;
wire   [255:0] data_loader_U0_x_point_stream_din;
wire    data_loader_U0_x_point_stream_write;
wire   [255:0] data_loader_U0_y_point_stream_din;
wire    data_loader_U0_y_point_stream_write;
wire   [255:0] data_loader_U0_z_point_stream_din;
wire    data_loader_U0_z_point_stream_write;
wire   [255:0] data_loader_U0_t_point_stream_din;
wire    data_loader_U0_t_point_stream_write;
wire   [255:0] data_loader_U0_scalar_point_stream_din;
wire    data_loader_U0_scalar_point_stream_write;
wire    data_loader_U0_start_out;
wire    data_loader_U0_start_write;
wire    pippenger_control_U0_ap_start;
wire    pippenger_control_U0_ap_done;
wire    pippenger_control_U0_ap_continue;
wire    pippenger_control_U0_ap_idle;
wire    pippenger_control_U0_ap_ready;
wire    pippenger_control_U0_x_point_stream_read;
wire    pippenger_control_U0_y_point_stream_read;
wire    pippenger_control_U0_z_point_stream_read;
wire    pippenger_control_U0_t_point_stream_read;
wire    pippenger_control_U0_scalar_point_stream_read;
wire   [1023:0] pippenger_control_U0_point_result_stream_din;
wire    pippenger_control_U0_point_result_stream_write;
wire    WriteBack_U0_ap_start;
wire    WriteBack_U0_ap_done;
wire    WriteBack_U0_ap_continue;
wire    WriteBack_U0_ap_idle;
wire    WriteBack_U0_ap_ready;
wire    WriteBack_U0_result_t_read;
wire    WriteBack_U0_result_z_read;
wire    WriteBack_U0_result_y_read;
wire    WriteBack_U0_result_x_read;
wire    WriteBack_U0_m_axi_gmem0_0_AWVALID;
wire   [63:0] WriteBack_U0_m_axi_gmem0_0_AWADDR;
wire   [0:0] WriteBack_U0_m_axi_gmem0_0_AWID;
wire   [31:0] WriteBack_U0_m_axi_gmem0_0_AWLEN;
wire   [2:0] WriteBack_U0_m_axi_gmem0_0_AWSIZE;
wire   [1:0] WriteBack_U0_m_axi_gmem0_0_AWBURST;
wire   [1:0] WriteBack_U0_m_axi_gmem0_0_AWLOCK;
wire   [3:0] WriteBack_U0_m_axi_gmem0_0_AWCACHE;
wire   [2:0] WriteBack_U0_m_axi_gmem0_0_AWPROT;
wire   [3:0] WriteBack_U0_m_axi_gmem0_0_AWQOS;
wire   [3:0] WriteBack_U0_m_axi_gmem0_0_AWREGION;
wire   [0:0] WriteBack_U0_m_axi_gmem0_0_AWUSER;
wire    WriteBack_U0_m_axi_gmem0_0_WVALID;
wire   [255:0] WriteBack_U0_m_axi_gmem0_0_WDATA;
wire   [31:0] WriteBack_U0_m_axi_gmem0_0_WSTRB;
wire    WriteBack_U0_m_axi_gmem0_0_WLAST;
wire   [0:0] WriteBack_U0_m_axi_gmem0_0_WID;
wire   [0:0] WriteBack_U0_m_axi_gmem0_0_WUSER;
wire    WriteBack_U0_m_axi_gmem0_0_ARVALID;
wire   [63:0] WriteBack_U0_m_axi_gmem0_0_ARADDR;
wire   [0:0] WriteBack_U0_m_axi_gmem0_0_ARID;
wire   [31:0] WriteBack_U0_m_axi_gmem0_0_ARLEN;
wire   [2:0] WriteBack_U0_m_axi_gmem0_0_ARSIZE;
wire   [1:0] WriteBack_U0_m_axi_gmem0_0_ARBURST;
wire   [1:0] WriteBack_U0_m_axi_gmem0_0_ARLOCK;
wire   [3:0] WriteBack_U0_m_axi_gmem0_0_ARCACHE;
wire   [2:0] WriteBack_U0_m_axi_gmem0_0_ARPROT;
wire   [3:0] WriteBack_U0_m_axi_gmem0_0_ARQOS;
wire   [3:0] WriteBack_U0_m_axi_gmem0_0_ARREGION;
wire   [0:0] WriteBack_U0_m_axi_gmem0_0_ARUSER;
wire    WriteBack_U0_m_axi_gmem0_0_RREADY;
wire    WriteBack_U0_m_axi_gmem0_0_BREADY;
wire    WriteBack_U0_m_axi_gmem1_0_AWVALID;
wire   [63:0] WriteBack_U0_m_axi_gmem1_0_AWADDR;
wire   [0:0] WriteBack_U0_m_axi_gmem1_0_AWID;
wire   [31:0] WriteBack_U0_m_axi_gmem1_0_AWLEN;
wire   [2:0] WriteBack_U0_m_axi_gmem1_0_AWSIZE;
wire   [1:0] WriteBack_U0_m_axi_gmem1_0_AWBURST;
wire   [1:0] WriteBack_U0_m_axi_gmem1_0_AWLOCK;
wire   [3:0] WriteBack_U0_m_axi_gmem1_0_AWCACHE;
wire   [2:0] WriteBack_U0_m_axi_gmem1_0_AWPROT;
wire   [3:0] WriteBack_U0_m_axi_gmem1_0_AWQOS;
wire   [3:0] WriteBack_U0_m_axi_gmem1_0_AWREGION;
wire   [0:0] WriteBack_U0_m_axi_gmem1_0_AWUSER;
wire    WriteBack_U0_m_axi_gmem1_0_WVALID;
wire   [255:0] WriteBack_U0_m_axi_gmem1_0_WDATA;
wire   [31:0] WriteBack_U0_m_axi_gmem1_0_WSTRB;
wire    WriteBack_U0_m_axi_gmem1_0_WLAST;
wire   [0:0] WriteBack_U0_m_axi_gmem1_0_WID;
wire   [0:0] WriteBack_U0_m_axi_gmem1_0_WUSER;
wire    WriteBack_U0_m_axi_gmem1_0_ARVALID;
wire   [63:0] WriteBack_U0_m_axi_gmem1_0_ARADDR;
wire   [0:0] WriteBack_U0_m_axi_gmem1_0_ARID;
wire   [31:0] WriteBack_U0_m_axi_gmem1_0_ARLEN;
wire   [2:0] WriteBack_U0_m_axi_gmem1_0_ARSIZE;
wire   [1:0] WriteBack_U0_m_axi_gmem1_0_ARBURST;
wire   [1:0] WriteBack_U0_m_axi_gmem1_0_ARLOCK;
wire   [3:0] WriteBack_U0_m_axi_gmem1_0_ARCACHE;
wire   [2:0] WriteBack_U0_m_axi_gmem1_0_ARPROT;
wire   [3:0] WriteBack_U0_m_axi_gmem1_0_ARQOS;
wire   [3:0] WriteBack_U0_m_axi_gmem1_0_ARREGION;
wire   [0:0] WriteBack_U0_m_axi_gmem1_0_ARUSER;
wire    WriteBack_U0_m_axi_gmem1_0_RREADY;
wire    WriteBack_U0_m_axi_gmem1_0_BREADY;
wire    WriteBack_U0_m_axi_gmem2_0_AWVALID;
wire   [63:0] WriteBack_U0_m_axi_gmem2_0_AWADDR;
wire   [0:0] WriteBack_U0_m_axi_gmem2_0_AWID;
wire   [31:0] WriteBack_U0_m_axi_gmem2_0_AWLEN;
wire   [2:0] WriteBack_U0_m_axi_gmem2_0_AWSIZE;
wire   [1:0] WriteBack_U0_m_axi_gmem2_0_AWBURST;
wire   [1:0] WriteBack_U0_m_axi_gmem2_0_AWLOCK;
wire   [3:0] WriteBack_U0_m_axi_gmem2_0_AWCACHE;
wire   [2:0] WriteBack_U0_m_axi_gmem2_0_AWPROT;
wire   [3:0] WriteBack_U0_m_axi_gmem2_0_AWQOS;
wire   [3:0] WriteBack_U0_m_axi_gmem2_0_AWREGION;
wire   [0:0] WriteBack_U0_m_axi_gmem2_0_AWUSER;
wire    WriteBack_U0_m_axi_gmem2_0_WVALID;
wire   [255:0] WriteBack_U0_m_axi_gmem2_0_WDATA;
wire   [31:0] WriteBack_U0_m_axi_gmem2_0_WSTRB;
wire    WriteBack_U0_m_axi_gmem2_0_WLAST;
wire   [0:0] WriteBack_U0_m_axi_gmem2_0_WID;
wire   [0:0] WriteBack_U0_m_axi_gmem2_0_WUSER;
wire    WriteBack_U0_m_axi_gmem2_0_ARVALID;
wire   [63:0] WriteBack_U0_m_axi_gmem2_0_ARADDR;
wire   [0:0] WriteBack_U0_m_axi_gmem2_0_ARID;
wire   [31:0] WriteBack_U0_m_axi_gmem2_0_ARLEN;
wire   [2:0] WriteBack_U0_m_axi_gmem2_0_ARSIZE;
wire   [1:0] WriteBack_U0_m_axi_gmem2_0_ARBURST;
wire   [1:0] WriteBack_U0_m_axi_gmem2_0_ARLOCK;
wire   [3:0] WriteBack_U0_m_axi_gmem2_0_ARCACHE;
wire   [2:0] WriteBack_U0_m_axi_gmem2_0_ARPROT;
wire   [3:0] WriteBack_U0_m_axi_gmem2_0_ARQOS;
wire   [3:0] WriteBack_U0_m_axi_gmem2_0_ARREGION;
wire   [0:0] WriteBack_U0_m_axi_gmem2_0_ARUSER;
wire    WriteBack_U0_m_axi_gmem2_0_RREADY;
wire    WriteBack_U0_m_axi_gmem2_0_BREADY;
wire    WriteBack_U0_m_axi_gmem3_0_AWVALID;
wire   [63:0] WriteBack_U0_m_axi_gmem3_0_AWADDR;
wire   [0:0] WriteBack_U0_m_axi_gmem3_0_AWID;
wire   [31:0] WriteBack_U0_m_axi_gmem3_0_AWLEN;
wire   [2:0] WriteBack_U0_m_axi_gmem3_0_AWSIZE;
wire   [1:0] WriteBack_U0_m_axi_gmem3_0_AWBURST;
wire   [1:0] WriteBack_U0_m_axi_gmem3_0_AWLOCK;
wire   [3:0] WriteBack_U0_m_axi_gmem3_0_AWCACHE;
wire   [2:0] WriteBack_U0_m_axi_gmem3_0_AWPROT;
wire   [3:0] WriteBack_U0_m_axi_gmem3_0_AWQOS;
wire   [3:0] WriteBack_U0_m_axi_gmem3_0_AWREGION;
wire   [0:0] WriteBack_U0_m_axi_gmem3_0_AWUSER;
wire    WriteBack_U0_m_axi_gmem3_0_WVALID;
wire   [255:0] WriteBack_U0_m_axi_gmem3_0_WDATA;
wire   [31:0] WriteBack_U0_m_axi_gmem3_0_WSTRB;
wire    WriteBack_U0_m_axi_gmem3_0_WLAST;
wire   [0:0] WriteBack_U0_m_axi_gmem3_0_WID;
wire   [0:0] WriteBack_U0_m_axi_gmem3_0_WUSER;
wire    WriteBack_U0_m_axi_gmem3_0_ARVALID;
wire   [63:0] WriteBack_U0_m_axi_gmem3_0_ARADDR;
wire   [0:0] WriteBack_U0_m_axi_gmem3_0_ARID;
wire   [31:0] WriteBack_U0_m_axi_gmem3_0_ARLEN;
wire   [2:0] WriteBack_U0_m_axi_gmem3_0_ARSIZE;
wire   [1:0] WriteBack_U0_m_axi_gmem3_0_ARBURST;
wire   [1:0] WriteBack_U0_m_axi_gmem3_0_ARLOCK;
wire   [3:0] WriteBack_U0_m_axi_gmem3_0_ARCACHE;
wire   [2:0] WriteBack_U0_m_axi_gmem3_0_ARPROT;
wire   [3:0] WriteBack_U0_m_axi_gmem3_0_ARQOS;
wire   [3:0] WriteBack_U0_m_axi_gmem3_0_ARREGION;
wire   [0:0] WriteBack_U0_m_axi_gmem3_0_ARUSER;
wire    WriteBack_U0_m_axi_gmem3_0_RREADY;
wire    WriteBack_U0_m_axi_gmem3_0_BREADY;
wire    WriteBack_U0_point_result_stream_read;
wire    result_x_c_full_n;
wire   [63:0] result_x_c_dout;
wire    result_x_c_empty_n;
wire   [2:0] result_x_c_num_data_valid;
wire   [2:0] result_x_c_fifo_cap;
wire    result_y_c_full_n;
wire   [63:0] result_y_c_dout;
wire    result_y_c_empty_n;
wire   [2:0] result_y_c_num_data_valid;
wire   [2:0] result_y_c_fifo_cap;
wire    result_z_c_full_n;
wire   [63:0] result_z_c_dout;
wire    result_z_c_empty_n;
wire   [2:0] result_z_c_num_data_valid;
wire   [2:0] result_z_c_fifo_cap;
wire    result_t_c_full_n;
wire   [63:0] result_t_c_dout;
wire    result_t_c_empty_n;
wire   [2:0] result_t_c_num_data_valid;
wire   [2:0] result_t_c_fifo_cap;
wire    x_point_stream_full_n;
wire   [255:0] x_point_stream_dout;
wire    x_point_stream_empty_n;
wire   [6:0] x_point_stream_num_data_valid;
wire   [6:0] x_point_stream_fifo_cap;
wire    y_point_stream_full_n;
wire   [255:0] y_point_stream_dout;
wire    y_point_stream_empty_n;
wire   [6:0] y_point_stream_num_data_valid;
wire   [6:0] y_point_stream_fifo_cap;
wire    z_point_stream_full_n;
wire   [255:0] z_point_stream_dout;
wire    z_point_stream_empty_n;
wire   [6:0] z_point_stream_num_data_valid;
wire   [6:0] z_point_stream_fifo_cap;
wire    t_point_stream_full_n;
wire   [255:0] t_point_stream_dout;
wire    t_point_stream_empty_n;
wire   [2:0] t_point_stream_num_data_valid;
wire   [2:0] t_point_stream_fifo_cap;
wire    scalar_point_stream_full_n;
wire   [255:0] scalar_point_stream_dout;
wire    scalar_point_stream_empty_n;
wire   [6:0] scalar_point_stream_num_data_valid;
wire   [6:0] scalar_point_stream_fifo_cap;
wire    point_result_stream_full_n;
wire   [1023:0] point_result_stream_dout;
wire    point_result_stream_empty_n;
wire   [6:0] point_result_stream_num_data_valid;
wire   [6:0] point_result_stream_fifo_cap;
wire    ap_sync_ready;
reg    ap_sync_reg_entry_proc_U0_ap_ready;
wire    ap_sync_entry_proc_U0_ap_ready;
reg    ap_sync_reg_data_loader_U0_ap_ready;
wire    ap_sync_data_loader_U0_ap_ready;
wire   [0:0] start_for_WriteBack_U0_din;
wire    start_for_WriteBack_U0_full_n;
wire   [0:0] start_for_WriteBack_U0_dout;
wire    start_for_WriteBack_U0_empty_n;
wire   [0:0] start_for_pippenger_control_U0_din;
wire    start_for_pippenger_control_U0_full_n;
wire   [0:0] start_for_pippenger_control_U0_dout;
wire    start_for_pippenger_control_U0_empty_n;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_sync_reg_entry_proc_U0_ap_ready = 1'b0;
#0 ap_sync_reg_data_loader_U0_ap_ready = 1'b0;
end

msm_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .x_array(x_array),
    .y_array(y_array),
    .z_array(z_array),
    .t_array(t_array),
    .result_x(result_x),
    .result_y(result_y),
    .result_z(result_z),
    .result_t(result_t)
);

msm_gmem0_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 7 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM0_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM0_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM0_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM0_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM0_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM0_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM0_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM0_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM0_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM0_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM0_CACHE_VALUE ),
    .CH0_USER_RFIFONUM_WIDTH( 9 ),
    .CH0_USER_DW( 256 ),
    .CH0_USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ))
gmem0_m_axi_U(
    .AWVALID(m_axi_gmem0_AWVALID),
    .AWREADY(m_axi_gmem0_AWREADY),
    .AWADDR(m_axi_gmem0_AWADDR),
    .AWID(m_axi_gmem0_AWID),
    .AWLEN(m_axi_gmem0_AWLEN),
    .AWSIZE(m_axi_gmem0_AWSIZE),
    .AWBURST(m_axi_gmem0_AWBURST),
    .AWLOCK(m_axi_gmem0_AWLOCK),
    .AWCACHE(m_axi_gmem0_AWCACHE),
    .AWPROT(m_axi_gmem0_AWPROT),
    .AWQOS(m_axi_gmem0_AWQOS),
    .AWREGION(m_axi_gmem0_AWREGION),
    .AWUSER(m_axi_gmem0_AWUSER),
    .WVALID(m_axi_gmem0_WVALID),
    .WREADY(m_axi_gmem0_WREADY),
    .WDATA(m_axi_gmem0_WDATA),
    .WSTRB(m_axi_gmem0_WSTRB),
    .WLAST(m_axi_gmem0_WLAST),
    .WID(m_axi_gmem0_WID),
    .WUSER(m_axi_gmem0_WUSER),
    .ARVALID(m_axi_gmem0_ARVALID),
    .ARREADY(m_axi_gmem0_ARREADY),
    .ARADDR(m_axi_gmem0_ARADDR),
    .ARID(m_axi_gmem0_ARID),
    .ARLEN(m_axi_gmem0_ARLEN),
    .ARSIZE(m_axi_gmem0_ARSIZE),
    .ARBURST(m_axi_gmem0_ARBURST),
    .ARLOCK(m_axi_gmem0_ARLOCK),
    .ARCACHE(m_axi_gmem0_ARCACHE),
    .ARPROT(m_axi_gmem0_ARPROT),
    .ARQOS(m_axi_gmem0_ARQOS),
    .ARREGION(m_axi_gmem0_ARREGION),
    .ARUSER(m_axi_gmem0_ARUSER),
    .RVALID(m_axi_gmem0_RVALID),
    .RREADY(m_axi_gmem0_RREADY),
    .RDATA(m_axi_gmem0_RDATA),
    .RLAST(m_axi_gmem0_RLAST),
    .RID(m_axi_gmem0_RID),
    .RUSER(m_axi_gmem0_RUSER),
    .RRESP(m_axi_gmem0_RRESP),
    .BVALID(m_axi_gmem0_BVALID),
    .BREADY(m_axi_gmem0_BREADY),
    .BRESP(m_axi_gmem0_BRESP),
    .BID(m_axi_gmem0_BID),
    .BUSER(m_axi_gmem0_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_CH0_ARVALID(data_loader_U0_m_axi_gmem0_0_ARVALID),
    .I_CH0_ARREADY(gmem0_0_ARREADY),
    .I_CH0_ARADDR(data_loader_U0_m_axi_gmem0_0_ARADDR),
    .I_CH0_ARLEN(data_loader_U0_m_axi_gmem0_0_ARLEN),
    .I_CH0_RVALID(gmem0_0_RVALID),
    .I_CH0_RREADY(data_loader_U0_m_axi_gmem0_0_RREADY),
    .I_CH0_RDATA(gmem0_0_RDATA),
    .I_CH0_RFIFONUM(gmem0_0_RFIFONUM),
    .I_CH0_AWVALID(WriteBack_U0_m_axi_gmem0_0_AWVALID),
    .I_CH0_AWREADY(gmem0_0_AWREADY),
    .I_CH0_AWADDR(WriteBack_U0_m_axi_gmem0_0_AWADDR),
    .I_CH0_AWLEN(WriteBack_U0_m_axi_gmem0_0_AWLEN),
    .I_CH0_WVALID(WriteBack_U0_m_axi_gmem0_0_WVALID),
    .I_CH0_WREADY(gmem0_0_WREADY),
    .I_CH0_WDATA(WriteBack_U0_m_axi_gmem0_0_WDATA),
    .I_CH0_WSTRB(WriteBack_U0_m_axi_gmem0_0_WSTRB),
    .I_CH0_BVALID(gmem0_0_BVALID),
    .I_CH0_BREADY(WriteBack_U0_m_axi_gmem0_0_BREADY)
);

msm_gmem1_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 7 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM1_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM1_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM1_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM1_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM1_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM1_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM1_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM1_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM1_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM1_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM1_CACHE_VALUE ),
    .CH0_USER_RFIFONUM_WIDTH( 9 ),
    .CH0_USER_DW( 256 ),
    .CH0_USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ))
gmem1_m_axi_U(
    .AWVALID(m_axi_gmem1_AWVALID),
    .AWREADY(m_axi_gmem1_AWREADY),
    .AWADDR(m_axi_gmem1_AWADDR),
    .AWID(m_axi_gmem1_AWID),
    .AWLEN(m_axi_gmem1_AWLEN),
    .AWSIZE(m_axi_gmem1_AWSIZE),
    .AWBURST(m_axi_gmem1_AWBURST),
    .AWLOCK(m_axi_gmem1_AWLOCK),
    .AWCACHE(m_axi_gmem1_AWCACHE),
    .AWPROT(m_axi_gmem1_AWPROT),
    .AWQOS(m_axi_gmem1_AWQOS),
    .AWREGION(m_axi_gmem1_AWREGION),
    .AWUSER(m_axi_gmem1_AWUSER),
    .WVALID(m_axi_gmem1_WVALID),
    .WREADY(m_axi_gmem1_WREADY),
    .WDATA(m_axi_gmem1_WDATA),
    .WSTRB(m_axi_gmem1_WSTRB),
    .WLAST(m_axi_gmem1_WLAST),
    .WID(m_axi_gmem1_WID),
    .WUSER(m_axi_gmem1_WUSER),
    .ARVALID(m_axi_gmem1_ARVALID),
    .ARREADY(m_axi_gmem1_ARREADY),
    .ARADDR(m_axi_gmem1_ARADDR),
    .ARID(m_axi_gmem1_ARID),
    .ARLEN(m_axi_gmem1_ARLEN),
    .ARSIZE(m_axi_gmem1_ARSIZE),
    .ARBURST(m_axi_gmem1_ARBURST),
    .ARLOCK(m_axi_gmem1_ARLOCK),
    .ARCACHE(m_axi_gmem1_ARCACHE),
    .ARPROT(m_axi_gmem1_ARPROT),
    .ARQOS(m_axi_gmem1_ARQOS),
    .ARREGION(m_axi_gmem1_ARREGION),
    .ARUSER(m_axi_gmem1_ARUSER),
    .RVALID(m_axi_gmem1_RVALID),
    .RREADY(m_axi_gmem1_RREADY),
    .RDATA(m_axi_gmem1_RDATA),
    .RLAST(m_axi_gmem1_RLAST),
    .RID(m_axi_gmem1_RID),
    .RUSER(m_axi_gmem1_RUSER),
    .RRESP(m_axi_gmem1_RRESP),
    .BVALID(m_axi_gmem1_BVALID),
    .BREADY(m_axi_gmem1_BREADY),
    .BRESP(m_axi_gmem1_BRESP),
    .BID(m_axi_gmem1_BID),
    .BUSER(m_axi_gmem1_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_CH0_ARVALID(data_loader_U0_m_axi_gmem1_0_ARVALID),
    .I_CH0_ARREADY(gmem1_0_ARREADY),
    .I_CH0_ARADDR(data_loader_U0_m_axi_gmem1_0_ARADDR),
    .I_CH0_ARLEN(data_loader_U0_m_axi_gmem1_0_ARLEN),
    .I_CH0_RVALID(gmem1_0_RVALID),
    .I_CH0_RREADY(data_loader_U0_m_axi_gmem1_0_RREADY),
    .I_CH0_RDATA(gmem1_0_RDATA),
    .I_CH0_RFIFONUM(gmem1_0_RFIFONUM),
    .I_CH0_AWVALID(WriteBack_U0_m_axi_gmem1_0_AWVALID),
    .I_CH0_AWREADY(gmem1_0_AWREADY),
    .I_CH0_AWADDR(WriteBack_U0_m_axi_gmem1_0_AWADDR),
    .I_CH0_AWLEN(WriteBack_U0_m_axi_gmem1_0_AWLEN),
    .I_CH0_WVALID(WriteBack_U0_m_axi_gmem1_0_WVALID),
    .I_CH0_WREADY(gmem1_0_WREADY),
    .I_CH0_WDATA(WriteBack_U0_m_axi_gmem1_0_WDATA),
    .I_CH0_WSTRB(WriteBack_U0_m_axi_gmem1_0_WSTRB),
    .I_CH0_BVALID(gmem1_0_BVALID),
    .I_CH0_BREADY(WriteBack_U0_m_axi_gmem1_0_BREADY)
);

msm_gmem2_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 7 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM2_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM2_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM2_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM2_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM2_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM2_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM2_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM2_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM2_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM2_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM2_CACHE_VALUE ),
    .CH0_USER_RFIFONUM_WIDTH( 9 ),
    .CH0_USER_DW( 256 ),
    .CH0_USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ))
gmem2_m_axi_U(
    .AWVALID(m_axi_gmem2_AWVALID),
    .AWREADY(m_axi_gmem2_AWREADY),
    .AWADDR(m_axi_gmem2_AWADDR),
    .AWID(m_axi_gmem2_AWID),
    .AWLEN(m_axi_gmem2_AWLEN),
    .AWSIZE(m_axi_gmem2_AWSIZE),
    .AWBURST(m_axi_gmem2_AWBURST),
    .AWLOCK(m_axi_gmem2_AWLOCK),
    .AWCACHE(m_axi_gmem2_AWCACHE),
    .AWPROT(m_axi_gmem2_AWPROT),
    .AWQOS(m_axi_gmem2_AWQOS),
    .AWREGION(m_axi_gmem2_AWREGION),
    .AWUSER(m_axi_gmem2_AWUSER),
    .WVALID(m_axi_gmem2_WVALID),
    .WREADY(m_axi_gmem2_WREADY),
    .WDATA(m_axi_gmem2_WDATA),
    .WSTRB(m_axi_gmem2_WSTRB),
    .WLAST(m_axi_gmem2_WLAST),
    .WID(m_axi_gmem2_WID),
    .WUSER(m_axi_gmem2_WUSER),
    .ARVALID(m_axi_gmem2_ARVALID),
    .ARREADY(m_axi_gmem2_ARREADY),
    .ARADDR(m_axi_gmem2_ARADDR),
    .ARID(m_axi_gmem2_ARID),
    .ARLEN(m_axi_gmem2_ARLEN),
    .ARSIZE(m_axi_gmem2_ARSIZE),
    .ARBURST(m_axi_gmem2_ARBURST),
    .ARLOCK(m_axi_gmem2_ARLOCK),
    .ARCACHE(m_axi_gmem2_ARCACHE),
    .ARPROT(m_axi_gmem2_ARPROT),
    .ARQOS(m_axi_gmem2_ARQOS),
    .ARREGION(m_axi_gmem2_ARREGION),
    .ARUSER(m_axi_gmem2_ARUSER),
    .RVALID(m_axi_gmem2_RVALID),
    .RREADY(m_axi_gmem2_RREADY),
    .RDATA(m_axi_gmem2_RDATA),
    .RLAST(m_axi_gmem2_RLAST),
    .RID(m_axi_gmem2_RID),
    .RUSER(m_axi_gmem2_RUSER),
    .RRESP(m_axi_gmem2_RRESP),
    .BVALID(m_axi_gmem2_BVALID),
    .BREADY(m_axi_gmem2_BREADY),
    .BRESP(m_axi_gmem2_BRESP),
    .BID(m_axi_gmem2_BID),
    .BUSER(m_axi_gmem2_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_CH0_ARVALID(data_loader_U0_m_axi_gmem2_0_ARVALID),
    .I_CH0_ARREADY(gmem2_0_ARREADY),
    .I_CH0_ARADDR(data_loader_U0_m_axi_gmem2_0_ARADDR),
    .I_CH0_ARLEN(data_loader_U0_m_axi_gmem2_0_ARLEN),
    .I_CH0_RVALID(gmem2_0_RVALID),
    .I_CH0_RREADY(data_loader_U0_m_axi_gmem2_0_RREADY),
    .I_CH0_RDATA(gmem2_0_RDATA),
    .I_CH0_RFIFONUM(gmem2_0_RFIFONUM),
    .I_CH0_AWVALID(WriteBack_U0_m_axi_gmem2_0_AWVALID),
    .I_CH0_AWREADY(gmem2_0_AWREADY),
    .I_CH0_AWADDR(WriteBack_U0_m_axi_gmem2_0_AWADDR),
    .I_CH0_AWLEN(WriteBack_U0_m_axi_gmem2_0_AWLEN),
    .I_CH0_WVALID(WriteBack_U0_m_axi_gmem2_0_WVALID),
    .I_CH0_WREADY(gmem2_0_WREADY),
    .I_CH0_WDATA(WriteBack_U0_m_axi_gmem2_0_WDATA),
    .I_CH0_WSTRB(WriteBack_U0_m_axi_gmem2_0_WSTRB),
    .I_CH0_BVALID(gmem2_0_BVALID),
    .I_CH0_BREADY(WriteBack_U0_m_axi_gmem2_0_BREADY)
);

msm_gmem3_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 7 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM3_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM3_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM3_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM3_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM3_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM3_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM3_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM3_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM3_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM3_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM3_CACHE_VALUE ),
    .CH0_USER_RFIFONUM_WIDTH( 9 ),
    .CH0_USER_DW( 256 ),
    .CH0_USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ))
gmem3_m_axi_U(
    .AWVALID(m_axi_gmem3_AWVALID),
    .AWREADY(m_axi_gmem3_AWREADY),
    .AWADDR(m_axi_gmem3_AWADDR),
    .AWID(m_axi_gmem3_AWID),
    .AWLEN(m_axi_gmem3_AWLEN),
    .AWSIZE(m_axi_gmem3_AWSIZE),
    .AWBURST(m_axi_gmem3_AWBURST),
    .AWLOCK(m_axi_gmem3_AWLOCK),
    .AWCACHE(m_axi_gmem3_AWCACHE),
    .AWPROT(m_axi_gmem3_AWPROT),
    .AWQOS(m_axi_gmem3_AWQOS),
    .AWREGION(m_axi_gmem3_AWREGION),
    .AWUSER(m_axi_gmem3_AWUSER),
    .WVALID(m_axi_gmem3_WVALID),
    .WREADY(m_axi_gmem3_WREADY),
    .WDATA(m_axi_gmem3_WDATA),
    .WSTRB(m_axi_gmem3_WSTRB),
    .WLAST(m_axi_gmem3_WLAST),
    .WID(m_axi_gmem3_WID),
    .WUSER(m_axi_gmem3_WUSER),
    .ARVALID(m_axi_gmem3_ARVALID),
    .ARREADY(m_axi_gmem3_ARREADY),
    .ARADDR(m_axi_gmem3_ARADDR),
    .ARID(m_axi_gmem3_ARID),
    .ARLEN(m_axi_gmem3_ARLEN),
    .ARSIZE(m_axi_gmem3_ARSIZE),
    .ARBURST(m_axi_gmem3_ARBURST),
    .ARLOCK(m_axi_gmem3_ARLOCK),
    .ARCACHE(m_axi_gmem3_ARCACHE),
    .ARPROT(m_axi_gmem3_ARPROT),
    .ARQOS(m_axi_gmem3_ARQOS),
    .ARREGION(m_axi_gmem3_ARREGION),
    .ARUSER(m_axi_gmem3_ARUSER),
    .RVALID(m_axi_gmem3_RVALID),
    .RREADY(m_axi_gmem3_RREADY),
    .RDATA(m_axi_gmem3_RDATA),
    .RLAST(m_axi_gmem3_RLAST),
    .RID(m_axi_gmem3_RID),
    .RUSER(m_axi_gmem3_RUSER),
    .RRESP(m_axi_gmem3_RRESP),
    .BVALID(m_axi_gmem3_BVALID),
    .BREADY(m_axi_gmem3_BREADY),
    .BRESP(m_axi_gmem3_BRESP),
    .BID(m_axi_gmem3_BID),
    .BUSER(m_axi_gmem3_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_CH0_ARVALID(data_loader_U0_m_axi_gmem3_0_ARVALID),
    .I_CH0_ARREADY(gmem3_0_ARREADY),
    .I_CH0_ARADDR(data_loader_U0_m_axi_gmem3_0_ARADDR),
    .I_CH0_ARLEN(data_loader_U0_m_axi_gmem3_0_ARLEN),
    .I_CH0_RVALID(gmem3_0_RVALID),
    .I_CH0_RREADY(data_loader_U0_m_axi_gmem3_0_RREADY),
    .I_CH0_RDATA(gmem3_0_RDATA),
    .I_CH0_RFIFONUM(gmem3_0_RFIFONUM),
    .I_CH0_AWVALID(WriteBack_U0_m_axi_gmem3_0_AWVALID),
    .I_CH0_AWREADY(gmem3_0_AWREADY),
    .I_CH0_AWADDR(WriteBack_U0_m_axi_gmem3_0_AWADDR),
    .I_CH0_AWLEN(WriteBack_U0_m_axi_gmem3_0_AWLEN),
    .I_CH0_WVALID(WriteBack_U0_m_axi_gmem3_0_WVALID),
    .I_CH0_WREADY(gmem3_0_WREADY),
    .I_CH0_WDATA(WriteBack_U0_m_axi_gmem3_0_WDATA),
    .I_CH0_WSTRB(WriteBack_U0_m_axi_gmem3_0_WSTRB),
    .I_CH0_BVALID(gmem3_0_BVALID),
    .I_CH0_BREADY(WriteBack_U0_m_axi_gmem3_0_BREADY)
);

msm_entry_proc entry_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(entry_proc_U0_ap_start),
    .start_full_n(start_for_WriteBack_U0_full_n),
    .ap_done(entry_proc_U0_ap_done),
    .ap_continue(entry_proc_U0_ap_continue),
    .ap_idle(entry_proc_U0_ap_idle),
    .ap_ready(entry_proc_U0_ap_ready),
    .start_out(entry_proc_U0_start_out),
    .start_write(entry_proc_U0_start_write),
    .result_x(result_x),
    .result_x_c_din(entry_proc_U0_result_x_c_din),
    .result_x_c_full_n(result_x_c_full_n),
    .result_x_c_write(entry_proc_U0_result_x_c_write),
    .result_x_c_num_data_valid(result_x_c_num_data_valid),
    .result_x_c_fifo_cap(result_x_c_fifo_cap),
    .result_y(result_y),
    .result_y_c_din(entry_proc_U0_result_y_c_din),
    .result_y_c_full_n(result_y_c_full_n),
    .result_y_c_write(entry_proc_U0_result_y_c_write),
    .result_y_c_num_data_valid(result_y_c_num_data_valid),
    .result_y_c_fifo_cap(result_y_c_fifo_cap),
    .result_z(result_z),
    .result_z_c_din(entry_proc_U0_result_z_c_din),
    .result_z_c_full_n(result_z_c_full_n),
    .result_z_c_write(entry_proc_U0_result_z_c_write),
    .result_z_c_num_data_valid(result_z_c_num_data_valid),
    .result_z_c_fifo_cap(result_z_c_fifo_cap),
    .result_t(result_t),
    .result_t_c_din(entry_proc_U0_result_t_c_din),
    .result_t_c_full_n(result_t_c_full_n),
    .result_t_c_write(entry_proc_U0_result_t_c_write),
    .result_t_c_num_data_valid(result_t_c_num_data_valid),
    .result_t_c_fifo_cap(result_t_c_fifo_cap)
);

msm_data_loader data_loader_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(data_loader_U0_ap_start),
    .start_full_n(start_for_pippenger_control_U0_full_n),
    .ap_done(data_loader_U0_ap_done),
    .ap_continue(data_loader_U0_ap_continue),
    .ap_idle(data_loader_U0_ap_idle),
    .ap_ready(data_loader_U0_ap_ready),
    .m_axi_gmem0_0_AWVALID(data_loader_U0_m_axi_gmem0_0_AWVALID),
    .m_axi_gmem0_0_AWREADY(1'b0),
    .m_axi_gmem0_0_AWADDR(data_loader_U0_m_axi_gmem0_0_AWADDR),
    .m_axi_gmem0_0_AWID(data_loader_U0_m_axi_gmem0_0_AWID),
    .m_axi_gmem0_0_AWLEN(data_loader_U0_m_axi_gmem0_0_AWLEN),
    .m_axi_gmem0_0_AWSIZE(data_loader_U0_m_axi_gmem0_0_AWSIZE),
    .m_axi_gmem0_0_AWBURST(data_loader_U0_m_axi_gmem0_0_AWBURST),
    .m_axi_gmem0_0_AWLOCK(data_loader_U0_m_axi_gmem0_0_AWLOCK),
    .m_axi_gmem0_0_AWCACHE(data_loader_U0_m_axi_gmem0_0_AWCACHE),
    .m_axi_gmem0_0_AWPROT(data_loader_U0_m_axi_gmem0_0_AWPROT),
    .m_axi_gmem0_0_AWQOS(data_loader_U0_m_axi_gmem0_0_AWQOS),
    .m_axi_gmem0_0_AWREGION(data_loader_U0_m_axi_gmem0_0_AWREGION),
    .m_axi_gmem0_0_AWUSER(data_loader_U0_m_axi_gmem0_0_AWUSER),
    .m_axi_gmem0_0_WVALID(data_loader_U0_m_axi_gmem0_0_WVALID),
    .m_axi_gmem0_0_WREADY(1'b0),
    .m_axi_gmem0_0_WDATA(data_loader_U0_m_axi_gmem0_0_WDATA),
    .m_axi_gmem0_0_WSTRB(data_loader_U0_m_axi_gmem0_0_WSTRB),
    .m_axi_gmem0_0_WLAST(data_loader_U0_m_axi_gmem0_0_WLAST),
    .m_axi_gmem0_0_WID(data_loader_U0_m_axi_gmem0_0_WID),
    .m_axi_gmem0_0_WUSER(data_loader_U0_m_axi_gmem0_0_WUSER),
    .m_axi_gmem0_0_ARVALID(data_loader_U0_m_axi_gmem0_0_ARVALID),
    .m_axi_gmem0_0_ARREADY(gmem0_0_ARREADY),
    .m_axi_gmem0_0_ARADDR(data_loader_U0_m_axi_gmem0_0_ARADDR),
    .m_axi_gmem0_0_ARID(data_loader_U0_m_axi_gmem0_0_ARID),
    .m_axi_gmem0_0_ARLEN(data_loader_U0_m_axi_gmem0_0_ARLEN),
    .m_axi_gmem0_0_ARSIZE(data_loader_U0_m_axi_gmem0_0_ARSIZE),
    .m_axi_gmem0_0_ARBURST(data_loader_U0_m_axi_gmem0_0_ARBURST),
    .m_axi_gmem0_0_ARLOCK(data_loader_U0_m_axi_gmem0_0_ARLOCK),
    .m_axi_gmem0_0_ARCACHE(data_loader_U0_m_axi_gmem0_0_ARCACHE),
    .m_axi_gmem0_0_ARPROT(data_loader_U0_m_axi_gmem0_0_ARPROT),
    .m_axi_gmem0_0_ARQOS(data_loader_U0_m_axi_gmem0_0_ARQOS),
    .m_axi_gmem0_0_ARREGION(data_loader_U0_m_axi_gmem0_0_ARREGION),
    .m_axi_gmem0_0_ARUSER(data_loader_U0_m_axi_gmem0_0_ARUSER),
    .m_axi_gmem0_0_RVALID(gmem0_0_RVALID),
    .m_axi_gmem0_0_RREADY(data_loader_U0_m_axi_gmem0_0_RREADY),
    .m_axi_gmem0_0_RDATA(gmem0_0_RDATA),
    .m_axi_gmem0_0_RLAST(gmem0_0_RLAST),
    .m_axi_gmem0_0_RID(gmem0_0_RID),
    .m_axi_gmem0_0_RFIFONUM(gmem0_0_RFIFONUM),
    .m_axi_gmem0_0_RUSER(gmem0_0_RUSER),
    .m_axi_gmem0_0_RRESP(gmem0_0_RRESP),
    .m_axi_gmem0_0_BVALID(1'b0),
    .m_axi_gmem0_0_BREADY(data_loader_U0_m_axi_gmem0_0_BREADY),
    .m_axi_gmem0_0_BRESP(2'd0),
    .m_axi_gmem0_0_BID(1'd0),
    .m_axi_gmem0_0_BUSER(1'd0),
    .m_axi_gmem1_0_AWVALID(data_loader_U0_m_axi_gmem1_0_AWVALID),
    .m_axi_gmem1_0_AWREADY(1'b0),
    .m_axi_gmem1_0_AWADDR(data_loader_U0_m_axi_gmem1_0_AWADDR),
    .m_axi_gmem1_0_AWID(data_loader_U0_m_axi_gmem1_0_AWID),
    .m_axi_gmem1_0_AWLEN(data_loader_U0_m_axi_gmem1_0_AWLEN),
    .m_axi_gmem1_0_AWSIZE(data_loader_U0_m_axi_gmem1_0_AWSIZE),
    .m_axi_gmem1_0_AWBURST(data_loader_U0_m_axi_gmem1_0_AWBURST),
    .m_axi_gmem1_0_AWLOCK(data_loader_U0_m_axi_gmem1_0_AWLOCK),
    .m_axi_gmem1_0_AWCACHE(data_loader_U0_m_axi_gmem1_0_AWCACHE),
    .m_axi_gmem1_0_AWPROT(data_loader_U0_m_axi_gmem1_0_AWPROT),
    .m_axi_gmem1_0_AWQOS(data_loader_U0_m_axi_gmem1_0_AWQOS),
    .m_axi_gmem1_0_AWREGION(data_loader_U0_m_axi_gmem1_0_AWREGION),
    .m_axi_gmem1_0_AWUSER(data_loader_U0_m_axi_gmem1_0_AWUSER),
    .m_axi_gmem1_0_WVALID(data_loader_U0_m_axi_gmem1_0_WVALID),
    .m_axi_gmem1_0_WREADY(1'b0),
    .m_axi_gmem1_0_WDATA(data_loader_U0_m_axi_gmem1_0_WDATA),
    .m_axi_gmem1_0_WSTRB(data_loader_U0_m_axi_gmem1_0_WSTRB),
    .m_axi_gmem1_0_WLAST(data_loader_U0_m_axi_gmem1_0_WLAST),
    .m_axi_gmem1_0_WID(data_loader_U0_m_axi_gmem1_0_WID),
    .m_axi_gmem1_0_WUSER(data_loader_U0_m_axi_gmem1_0_WUSER),
    .m_axi_gmem1_0_ARVALID(data_loader_U0_m_axi_gmem1_0_ARVALID),
    .m_axi_gmem1_0_ARREADY(gmem1_0_ARREADY),
    .m_axi_gmem1_0_ARADDR(data_loader_U0_m_axi_gmem1_0_ARADDR),
    .m_axi_gmem1_0_ARID(data_loader_U0_m_axi_gmem1_0_ARID),
    .m_axi_gmem1_0_ARLEN(data_loader_U0_m_axi_gmem1_0_ARLEN),
    .m_axi_gmem1_0_ARSIZE(data_loader_U0_m_axi_gmem1_0_ARSIZE),
    .m_axi_gmem1_0_ARBURST(data_loader_U0_m_axi_gmem1_0_ARBURST),
    .m_axi_gmem1_0_ARLOCK(data_loader_U0_m_axi_gmem1_0_ARLOCK),
    .m_axi_gmem1_0_ARCACHE(data_loader_U0_m_axi_gmem1_0_ARCACHE),
    .m_axi_gmem1_0_ARPROT(data_loader_U0_m_axi_gmem1_0_ARPROT),
    .m_axi_gmem1_0_ARQOS(data_loader_U0_m_axi_gmem1_0_ARQOS),
    .m_axi_gmem1_0_ARREGION(data_loader_U0_m_axi_gmem1_0_ARREGION),
    .m_axi_gmem1_0_ARUSER(data_loader_U0_m_axi_gmem1_0_ARUSER),
    .m_axi_gmem1_0_RVALID(gmem1_0_RVALID),
    .m_axi_gmem1_0_RREADY(data_loader_U0_m_axi_gmem1_0_RREADY),
    .m_axi_gmem1_0_RDATA(gmem1_0_RDATA),
    .m_axi_gmem1_0_RLAST(gmem1_0_RLAST),
    .m_axi_gmem1_0_RID(gmem1_0_RID),
    .m_axi_gmem1_0_RFIFONUM(gmem1_0_RFIFONUM),
    .m_axi_gmem1_0_RUSER(gmem1_0_RUSER),
    .m_axi_gmem1_0_RRESP(gmem1_0_RRESP),
    .m_axi_gmem1_0_BVALID(1'b0),
    .m_axi_gmem1_0_BREADY(data_loader_U0_m_axi_gmem1_0_BREADY),
    .m_axi_gmem1_0_BRESP(2'd0),
    .m_axi_gmem1_0_BID(1'd0),
    .m_axi_gmem1_0_BUSER(1'd0),
    .m_axi_gmem2_0_AWVALID(data_loader_U0_m_axi_gmem2_0_AWVALID),
    .m_axi_gmem2_0_AWREADY(1'b0),
    .m_axi_gmem2_0_AWADDR(data_loader_U0_m_axi_gmem2_0_AWADDR),
    .m_axi_gmem2_0_AWID(data_loader_U0_m_axi_gmem2_0_AWID),
    .m_axi_gmem2_0_AWLEN(data_loader_U0_m_axi_gmem2_0_AWLEN),
    .m_axi_gmem2_0_AWSIZE(data_loader_U0_m_axi_gmem2_0_AWSIZE),
    .m_axi_gmem2_0_AWBURST(data_loader_U0_m_axi_gmem2_0_AWBURST),
    .m_axi_gmem2_0_AWLOCK(data_loader_U0_m_axi_gmem2_0_AWLOCK),
    .m_axi_gmem2_0_AWCACHE(data_loader_U0_m_axi_gmem2_0_AWCACHE),
    .m_axi_gmem2_0_AWPROT(data_loader_U0_m_axi_gmem2_0_AWPROT),
    .m_axi_gmem2_0_AWQOS(data_loader_U0_m_axi_gmem2_0_AWQOS),
    .m_axi_gmem2_0_AWREGION(data_loader_U0_m_axi_gmem2_0_AWREGION),
    .m_axi_gmem2_0_AWUSER(data_loader_U0_m_axi_gmem2_0_AWUSER),
    .m_axi_gmem2_0_WVALID(data_loader_U0_m_axi_gmem2_0_WVALID),
    .m_axi_gmem2_0_WREADY(1'b0),
    .m_axi_gmem2_0_WDATA(data_loader_U0_m_axi_gmem2_0_WDATA),
    .m_axi_gmem2_0_WSTRB(data_loader_U0_m_axi_gmem2_0_WSTRB),
    .m_axi_gmem2_0_WLAST(data_loader_U0_m_axi_gmem2_0_WLAST),
    .m_axi_gmem2_0_WID(data_loader_U0_m_axi_gmem2_0_WID),
    .m_axi_gmem2_0_WUSER(data_loader_U0_m_axi_gmem2_0_WUSER),
    .m_axi_gmem2_0_ARVALID(data_loader_U0_m_axi_gmem2_0_ARVALID),
    .m_axi_gmem2_0_ARREADY(gmem2_0_ARREADY),
    .m_axi_gmem2_0_ARADDR(data_loader_U0_m_axi_gmem2_0_ARADDR),
    .m_axi_gmem2_0_ARID(data_loader_U0_m_axi_gmem2_0_ARID),
    .m_axi_gmem2_0_ARLEN(data_loader_U0_m_axi_gmem2_0_ARLEN),
    .m_axi_gmem2_0_ARSIZE(data_loader_U0_m_axi_gmem2_0_ARSIZE),
    .m_axi_gmem2_0_ARBURST(data_loader_U0_m_axi_gmem2_0_ARBURST),
    .m_axi_gmem2_0_ARLOCK(data_loader_U0_m_axi_gmem2_0_ARLOCK),
    .m_axi_gmem2_0_ARCACHE(data_loader_U0_m_axi_gmem2_0_ARCACHE),
    .m_axi_gmem2_0_ARPROT(data_loader_U0_m_axi_gmem2_0_ARPROT),
    .m_axi_gmem2_0_ARQOS(data_loader_U0_m_axi_gmem2_0_ARQOS),
    .m_axi_gmem2_0_ARREGION(data_loader_U0_m_axi_gmem2_0_ARREGION),
    .m_axi_gmem2_0_ARUSER(data_loader_U0_m_axi_gmem2_0_ARUSER),
    .m_axi_gmem2_0_RVALID(gmem2_0_RVALID),
    .m_axi_gmem2_0_RREADY(data_loader_U0_m_axi_gmem2_0_RREADY),
    .m_axi_gmem2_0_RDATA(gmem2_0_RDATA),
    .m_axi_gmem2_0_RLAST(gmem2_0_RLAST),
    .m_axi_gmem2_0_RID(gmem2_0_RID),
    .m_axi_gmem2_0_RFIFONUM(gmem2_0_RFIFONUM),
    .m_axi_gmem2_0_RUSER(gmem2_0_RUSER),
    .m_axi_gmem2_0_RRESP(gmem2_0_RRESP),
    .m_axi_gmem2_0_BVALID(1'b0),
    .m_axi_gmem2_0_BREADY(data_loader_U0_m_axi_gmem2_0_BREADY),
    .m_axi_gmem2_0_BRESP(2'd0),
    .m_axi_gmem2_0_BID(1'd0),
    .m_axi_gmem2_0_BUSER(1'd0),
    .m_axi_gmem3_0_AWVALID(data_loader_U0_m_axi_gmem3_0_AWVALID),
    .m_axi_gmem3_0_AWREADY(1'b0),
    .m_axi_gmem3_0_AWADDR(data_loader_U0_m_axi_gmem3_0_AWADDR),
    .m_axi_gmem3_0_AWID(data_loader_U0_m_axi_gmem3_0_AWID),
    .m_axi_gmem3_0_AWLEN(data_loader_U0_m_axi_gmem3_0_AWLEN),
    .m_axi_gmem3_0_AWSIZE(data_loader_U0_m_axi_gmem3_0_AWSIZE),
    .m_axi_gmem3_0_AWBURST(data_loader_U0_m_axi_gmem3_0_AWBURST),
    .m_axi_gmem3_0_AWLOCK(data_loader_U0_m_axi_gmem3_0_AWLOCK),
    .m_axi_gmem3_0_AWCACHE(data_loader_U0_m_axi_gmem3_0_AWCACHE),
    .m_axi_gmem3_0_AWPROT(data_loader_U0_m_axi_gmem3_0_AWPROT),
    .m_axi_gmem3_0_AWQOS(data_loader_U0_m_axi_gmem3_0_AWQOS),
    .m_axi_gmem3_0_AWREGION(data_loader_U0_m_axi_gmem3_0_AWREGION),
    .m_axi_gmem3_0_AWUSER(data_loader_U0_m_axi_gmem3_0_AWUSER),
    .m_axi_gmem3_0_WVALID(data_loader_U0_m_axi_gmem3_0_WVALID),
    .m_axi_gmem3_0_WREADY(1'b0),
    .m_axi_gmem3_0_WDATA(data_loader_U0_m_axi_gmem3_0_WDATA),
    .m_axi_gmem3_0_WSTRB(data_loader_U0_m_axi_gmem3_0_WSTRB),
    .m_axi_gmem3_0_WLAST(data_loader_U0_m_axi_gmem3_0_WLAST),
    .m_axi_gmem3_0_WID(data_loader_U0_m_axi_gmem3_0_WID),
    .m_axi_gmem3_0_WUSER(data_loader_U0_m_axi_gmem3_0_WUSER),
    .m_axi_gmem3_0_ARVALID(data_loader_U0_m_axi_gmem3_0_ARVALID),
    .m_axi_gmem3_0_ARREADY(gmem3_0_ARREADY),
    .m_axi_gmem3_0_ARADDR(data_loader_U0_m_axi_gmem3_0_ARADDR),
    .m_axi_gmem3_0_ARID(data_loader_U0_m_axi_gmem3_0_ARID),
    .m_axi_gmem3_0_ARLEN(data_loader_U0_m_axi_gmem3_0_ARLEN),
    .m_axi_gmem3_0_ARSIZE(data_loader_U0_m_axi_gmem3_0_ARSIZE),
    .m_axi_gmem3_0_ARBURST(data_loader_U0_m_axi_gmem3_0_ARBURST),
    .m_axi_gmem3_0_ARLOCK(data_loader_U0_m_axi_gmem3_0_ARLOCK),
    .m_axi_gmem3_0_ARCACHE(data_loader_U0_m_axi_gmem3_0_ARCACHE),
    .m_axi_gmem3_0_ARPROT(data_loader_U0_m_axi_gmem3_0_ARPROT),
    .m_axi_gmem3_0_ARQOS(data_loader_U0_m_axi_gmem3_0_ARQOS),
    .m_axi_gmem3_0_ARREGION(data_loader_U0_m_axi_gmem3_0_ARREGION),
    .m_axi_gmem3_0_ARUSER(data_loader_U0_m_axi_gmem3_0_ARUSER),
    .m_axi_gmem3_0_RVALID(gmem3_0_RVALID),
    .m_axi_gmem3_0_RREADY(data_loader_U0_m_axi_gmem3_0_RREADY),
    .m_axi_gmem3_0_RDATA(gmem3_0_RDATA),
    .m_axi_gmem3_0_RLAST(gmem3_0_RLAST),
    .m_axi_gmem3_0_RID(gmem3_0_RID),
    .m_axi_gmem3_0_RFIFONUM(gmem3_0_RFIFONUM),
    .m_axi_gmem3_0_RUSER(gmem3_0_RUSER),
    .m_axi_gmem3_0_RRESP(gmem3_0_RRESP),
    .m_axi_gmem3_0_BVALID(1'b0),
    .m_axi_gmem3_0_BREADY(data_loader_U0_m_axi_gmem3_0_BREADY),
    .m_axi_gmem3_0_BRESP(2'd0),
    .m_axi_gmem3_0_BID(1'd0),
    .m_axi_gmem3_0_BUSER(1'd0),
    .x_point_stream_din(data_loader_U0_x_point_stream_din),
    .x_point_stream_full_n(x_point_stream_full_n),
    .x_point_stream_write(data_loader_U0_x_point_stream_write),
    .x_point_stream_num_data_valid(x_point_stream_num_data_valid),
    .x_point_stream_fifo_cap(x_point_stream_fifo_cap),
    .y_point_stream_din(data_loader_U0_y_point_stream_din),
    .y_point_stream_full_n(y_point_stream_full_n),
    .y_point_stream_write(data_loader_U0_y_point_stream_write),
    .y_point_stream_num_data_valid(y_point_stream_num_data_valid),
    .y_point_stream_fifo_cap(y_point_stream_fifo_cap),
    .z_point_stream_din(data_loader_U0_z_point_stream_din),
    .z_point_stream_full_n(z_point_stream_full_n),
    .z_point_stream_write(data_loader_U0_z_point_stream_write),
    .z_point_stream_num_data_valid(z_point_stream_num_data_valid),
    .z_point_stream_fifo_cap(z_point_stream_fifo_cap),
    .t_point_stream_din(data_loader_U0_t_point_stream_din),
    .t_point_stream_full_n(t_point_stream_full_n),
    .t_point_stream_write(data_loader_U0_t_point_stream_write),
    .t_point_stream_num_data_valid(t_point_stream_num_data_valid),
    .t_point_stream_fifo_cap(t_point_stream_fifo_cap),
    .scalar_point_stream_din(data_loader_U0_scalar_point_stream_din),
    .scalar_point_stream_full_n(scalar_point_stream_full_n),
    .scalar_point_stream_write(data_loader_U0_scalar_point_stream_write),
    .scalar_point_stream_num_data_valid(scalar_point_stream_num_data_valid),
    .scalar_point_stream_fifo_cap(scalar_point_stream_fifo_cap),
    .start_out(data_loader_U0_start_out),
    .start_write(data_loader_U0_start_write),
    .x_array(x_array),
    .y_array(y_array),
    .z_array(z_array),
    .t_array(t_array),
    .scalar_array(scalar_array),
    .degree(degree)
);

msm_pippenger_control pippenger_control_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(pippenger_control_U0_ap_start),
    .ap_done(pippenger_control_U0_ap_done),
    .ap_continue(pippenger_control_U0_ap_continue),
    .ap_idle(pippenger_control_U0_ap_idle),
    .ap_ready(pippenger_control_U0_ap_ready),
    .x_point_stream_dout(x_point_stream_dout),
    .x_point_stream_empty_n(x_point_stream_empty_n),
    .x_point_stream_read(pippenger_control_U0_x_point_stream_read),
    .x_point_stream_num_data_valid(x_point_stream_num_data_valid),
    .x_point_stream_fifo_cap(x_point_stream_fifo_cap),
    .y_point_stream_dout(y_point_stream_dout),
    .y_point_stream_empty_n(y_point_stream_empty_n),
    .y_point_stream_read(pippenger_control_U0_y_point_stream_read),
    .y_point_stream_num_data_valid(y_point_stream_num_data_valid),
    .y_point_stream_fifo_cap(y_point_stream_fifo_cap),
    .z_point_stream_dout(z_point_stream_dout),
    .z_point_stream_empty_n(z_point_stream_empty_n),
    .z_point_stream_read(pippenger_control_U0_z_point_stream_read),
    .z_point_stream_num_data_valid(z_point_stream_num_data_valid),
    .z_point_stream_fifo_cap(z_point_stream_fifo_cap),
    .t_point_stream_dout(t_point_stream_dout),
    .t_point_stream_empty_n(t_point_stream_empty_n),
    .t_point_stream_read(pippenger_control_U0_t_point_stream_read),
    .t_point_stream_num_data_valid(t_point_stream_num_data_valid),
    .t_point_stream_fifo_cap(t_point_stream_fifo_cap),
    .scalar_point_stream_dout(scalar_point_stream_dout),
    .scalar_point_stream_empty_n(scalar_point_stream_empty_n),
    .scalar_point_stream_read(pippenger_control_U0_scalar_point_stream_read),
    .scalar_point_stream_num_data_valid(scalar_point_stream_num_data_valid),
    .scalar_point_stream_fifo_cap(scalar_point_stream_fifo_cap),
    .point_result_stream_din(pippenger_control_U0_point_result_stream_din),
    .point_result_stream_full_n(point_result_stream_full_n),
    .point_result_stream_write(pippenger_control_U0_point_result_stream_write),
    .point_result_stream_num_data_valid(point_result_stream_num_data_valid),
    .point_result_stream_fifo_cap(point_result_stream_fifo_cap)
);

msm_WriteBack WriteBack_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(WriteBack_U0_ap_start),
    .ap_done(WriteBack_U0_ap_done),
    .ap_continue(WriteBack_U0_ap_continue),
    .ap_idle(WriteBack_U0_ap_idle),
    .ap_ready(WriteBack_U0_ap_ready),
    .result_t_dout(result_t_c_dout),
    .result_t_empty_n(result_t_c_empty_n),
    .result_t_read(WriteBack_U0_result_t_read),
    .result_t_num_data_valid(result_t_c_num_data_valid),
    .result_t_fifo_cap(result_t_c_fifo_cap),
    .result_z_dout(result_z_c_dout),
    .result_z_empty_n(result_z_c_empty_n),
    .result_z_read(WriteBack_U0_result_z_read),
    .result_z_num_data_valid(result_z_c_num_data_valid),
    .result_z_fifo_cap(result_z_c_fifo_cap),
    .result_y_dout(result_y_c_dout),
    .result_y_empty_n(result_y_c_empty_n),
    .result_y_read(WriteBack_U0_result_y_read),
    .result_y_num_data_valid(result_y_c_num_data_valid),
    .result_y_fifo_cap(result_y_c_fifo_cap),
    .result_x_dout(result_x_c_dout),
    .result_x_empty_n(result_x_c_empty_n),
    .result_x_read(WriteBack_U0_result_x_read),
    .result_x_num_data_valid(result_x_c_num_data_valid),
    .result_x_fifo_cap(result_x_c_fifo_cap),
    .m_axi_gmem0_0_AWVALID(WriteBack_U0_m_axi_gmem0_0_AWVALID),
    .m_axi_gmem0_0_AWREADY(gmem0_0_AWREADY),
    .m_axi_gmem0_0_AWADDR(WriteBack_U0_m_axi_gmem0_0_AWADDR),
    .m_axi_gmem0_0_AWID(WriteBack_U0_m_axi_gmem0_0_AWID),
    .m_axi_gmem0_0_AWLEN(WriteBack_U0_m_axi_gmem0_0_AWLEN),
    .m_axi_gmem0_0_AWSIZE(WriteBack_U0_m_axi_gmem0_0_AWSIZE),
    .m_axi_gmem0_0_AWBURST(WriteBack_U0_m_axi_gmem0_0_AWBURST),
    .m_axi_gmem0_0_AWLOCK(WriteBack_U0_m_axi_gmem0_0_AWLOCK),
    .m_axi_gmem0_0_AWCACHE(WriteBack_U0_m_axi_gmem0_0_AWCACHE),
    .m_axi_gmem0_0_AWPROT(WriteBack_U0_m_axi_gmem0_0_AWPROT),
    .m_axi_gmem0_0_AWQOS(WriteBack_U0_m_axi_gmem0_0_AWQOS),
    .m_axi_gmem0_0_AWREGION(WriteBack_U0_m_axi_gmem0_0_AWREGION),
    .m_axi_gmem0_0_AWUSER(WriteBack_U0_m_axi_gmem0_0_AWUSER),
    .m_axi_gmem0_0_WVALID(WriteBack_U0_m_axi_gmem0_0_WVALID),
    .m_axi_gmem0_0_WREADY(gmem0_0_WREADY),
    .m_axi_gmem0_0_WDATA(WriteBack_U0_m_axi_gmem0_0_WDATA),
    .m_axi_gmem0_0_WSTRB(WriteBack_U0_m_axi_gmem0_0_WSTRB),
    .m_axi_gmem0_0_WLAST(WriteBack_U0_m_axi_gmem0_0_WLAST),
    .m_axi_gmem0_0_WID(WriteBack_U0_m_axi_gmem0_0_WID),
    .m_axi_gmem0_0_WUSER(WriteBack_U0_m_axi_gmem0_0_WUSER),
    .m_axi_gmem0_0_ARVALID(WriteBack_U0_m_axi_gmem0_0_ARVALID),
    .m_axi_gmem0_0_ARREADY(1'b0),
    .m_axi_gmem0_0_ARADDR(WriteBack_U0_m_axi_gmem0_0_ARADDR),
    .m_axi_gmem0_0_ARID(WriteBack_U0_m_axi_gmem0_0_ARID),
    .m_axi_gmem0_0_ARLEN(WriteBack_U0_m_axi_gmem0_0_ARLEN),
    .m_axi_gmem0_0_ARSIZE(WriteBack_U0_m_axi_gmem0_0_ARSIZE),
    .m_axi_gmem0_0_ARBURST(WriteBack_U0_m_axi_gmem0_0_ARBURST),
    .m_axi_gmem0_0_ARLOCK(WriteBack_U0_m_axi_gmem0_0_ARLOCK),
    .m_axi_gmem0_0_ARCACHE(WriteBack_U0_m_axi_gmem0_0_ARCACHE),
    .m_axi_gmem0_0_ARPROT(WriteBack_U0_m_axi_gmem0_0_ARPROT),
    .m_axi_gmem0_0_ARQOS(WriteBack_U0_m_axi_gmem0_0_ARQOS),
    .m_axi_gmem0_0_ARREGION(WriteBack_U0_m_axi_gmem0_0_ARREGION),
    .m_axi_gmem0_0_ARUSER(WriteBack_U0_m_axi_gmem0_0_ARUSER),
    .m_axi_gmem0_0_RVALID(1'b0),
    .m_axi_gmem0_0_RREADY(WriteBack_U0_m_axi_gmem0_0_RREADY),
    .m_axi_gmem0_0_RDATA(256'd0),
    .m_axi_gmem0_0_RLAST(1'b0),
    .m_axi_gmem0_0_RID(1'd0),
    .m_axi_gmem0_0_RFIFONUM(9'd0),
    .m_axi_gmem0_0_RUSER(1'd0),
    .m_axi_gmem0_0_RRESP(2'd0),
    .m_axi_gmem0_0_BVALID(gmem0_0_BVALID),
    .m_axi_gmem0_0_BREADY(WriteBack_U0_m_axi_gmem0_0_BREADY),
    .m_axi_gmem0_0_BRESP(gmem0_0_BRESP),
    .m_axi_gmem0_0_BID(gmem0_0_BID),
    .m_axi_gmem0_0_BUSER(gmem0_0_BUSER),
    .m_axi_gmem1_0_AWVALID(WriteBack_U0_m_axi_gmem1_0_AWVALID),
    .m_axi_gmem1_0_AWREADY(gmem1_0_AWREADY),
    .m_axi_gmem1_0_AWADDR(WriteBack_U0_m_axi_gmem1_0_AWADDR),
    .m_axi_gmem1_0_AWID(WriteBack_U0_m_axi_gmem1_0_AWID),
    .m_axi_gmem1_0_AWLEN(WriteBack_U0_m_axi_gmem1_0_AWLEN),
    .m_axi_gmem1_0_AWSIZE(WriteBack_U0_m_axi_gmem1_0_AWSIZE),
    .m_axi_gmem1_0_AWBURST(WriteBack_U0_m_axi_gmem1_0_AWBURST),
    .m_axi_gmem1_0_AWLOCK(WriteBack_U0_m_axi_gmem1_0_AWLOCK),
    .m_axi_gmem1_0_AWCACHE(WriteBack_U0_m_axi_gmem1_0_AWCACHE),
    .m_axi_gmem1_0_AWPROT(WriteBack_U0_m_axi_gmem1_0_AWPROT),
    .m_axi_gmem1_0_AWQOS(WriteBack_U0_m_axi_gmem1_0_AWQOS),
    .m_axi_gmem1_0_AWREGION(WriteBack_U0_m_axi_gmem1_0_AWREGION),
    .m_axi_gmem1_0_AWUSER(WriteBack_U0_m_axi_gmem1_0_AWUSER),
    .m_axi_gmem1_0_WVALID(WriteBack_U0_m_axi_gmem1_0_WVALID),
    .m_axi_gmem1_0_WREADY(gmem1_0_WREADY),
    .m_axi_gmem1_0_WDATA(WriteBack_U0_m_axi_gmem1_0_WDATA),
    .m_axi_gmem1_0_WSTRB(WriteBack_U0_m_axi_gmem1_0_WSTRB),
    .m_axi_gmem1_0_WLAST(WriteBack_U0_m_axi_gmem1_0_WLAST),
    .m_axi_gmem1_0_WID(WriteBack_U0_m_axi_gmem1_0_WID),
    .m_axi_gmem1_0_WUSER(WriteBack_U0_m_axi_gmem1_0_WUSER),
    .m_axi_gmem1_0_ARVALID(WriteBack_U0_m_axi_gmem1_0_ARVALID),
    .m_axi_gmem1_0_ARREADY(1'b0),
    .m_axi_gmem1_0_ARADDR(WriteBack_U0_m_axi_gmem1_0_ARADDR),
    .m_axi_gmem1_0_ARID(WriteBack_U0_m_axi_gmem1_0_ARID),
    .m_axi_gmem1_0_ARLEN(WriteBack_U0_m_axi_gmem1_0_ARLEN),
    .m_axi_gmem1_0_ARSIZE(WriteBack_U0_m_axi_gmem1_0_ARSIZE),
    .m_axi_gmem1_0_ARBURST(WriteBack_U0_m_axi_gmem1_0_ARBURST),
    .m_axi_gmem1_0_ARLOCK(WriteBack_U0_m_axi_gmem1_0_ARLOCK),
    .m_axi_gmem1_0_ARCACHE(WriteBack_U0_m_axi_gmem1_0_ARCACHE),
    .m_axi_gmem1_0_ARPROT(WriteBack_U0_m_axi_gmem1_0_ARPROT),
    .m_axi_gmem1_0_ARQOS(WriteBack_U0_m_axi_gmem1_0_ARQOS),
    .m_axi_gmem1_0_ARREGION(WriteBack_U0_m_axi_gmem1_0_ARREGION),
    .m_axi_gmem1_0_ARUSER(WriteBack_U0_m_axi_gmem1_0_ARUSER),
    .m_axi_gmem1_0_RVALID(1'b0),
    .m_axi_gmem1_0_RREADY(WriteBack_U0_m_axi_gmem1_0_RREADY),
    .m_axi_gmem1_0_RDATA(256'd0),
    .m_axi_gmem1_0_RLAST(1'b0),
    .m_axi_gmem1_0_RID(1'd0),
    .m_axi_gmem1_0_RFIFONUM(9'd0),
    .m_axi_gmem1_0_RUSER(1'd0),
    .m_axi_gmem1_0_RRESP(2'd0),
    .m_axi_gmem1_0_BVALID(gmem1_0_BVALID),
    .m_axi_gmem1_0_BREADY(WriteBack_U0_m_axi_gmem1_0_BREADY),
    .m_axi_gmem1_0_BRESP(gmem1_0_BRESP),
    .m_axi_gmem1_0_BID(gmem1_0_BID),
    .m_axi_gmem1_0_BUSER(gmem1_0_BUSER),
    .m_axi_gmem2_0_AWVALID(WriteBack_U0_m_axi_gmem2_0_AWVALID),
    .m_axi_gmem2_0_AWREADY(gmem2_0_AWREADY),
    .m_axi_gmem2_0_AWADDR(WriteBack_U0_m_axi_gmem2_0_AWADDR),
    .m_axi_gmem2_0_AWID(WriteBack_U0_m_axi_gmem2_0_AWID),
    .m_axi_gmem2_0_AWLEN(WriteBack_U0_m_axi_gmem2_0_AWLEN),
    .m_axi_gmem2_0_AWSIZE(WriteBack_U0_m_axi_gmem2_0_AWSIZE),
    .m_axi_gmem2_0_AWBURST(WriteBack_U0_m_axi_gmem2_0_AWBURST),
    .m_axi_gmem2_0_AWLOCK(WriteBack_U0_m_axi_gmem2_0_AWLOCK),
    .m_axi_gmem2_0_AWCACHE(WriteBack_U0_m_axi_gmem2_0_AWCACHE),
    .m_axi_gmem2_0_AWPROT(WriteBack_U0_m_axi_gmem2_0_AWPROT),
    .m_axi_gmem2_0_AWQOS(WriteBack_U0_m_axi_gmem2_0_AWQOS),
    .m_axi_gmem2_0_AWREGION(WriteBack_U0_m_axi_gmem2_0_AWREGION),
    .m_axi_gmem2_0_AWUSER(WriteBack_U0_m_axi_gmem2_0_AWUSER),
    .m_axi_gmem2_0_WVALID(WriteBack_U0_m_axi_gmem2_0_WVALID),
    .m_axi_gmem2_0_WREADY(gmem2_0_WREADY),
    .m_axi_gmem2_0_WDATA(WriteBack_U0_m_axi_gmem2_0_WDATA),
    .m_axi_gmem2_0_WSTRB(WriteBack_U0_m_axi_gmem2_0_WSTRB),
    .m_axi_gmem2_0_WLAST(WriteBack_U0_m_axi_gmem2_0_WLAST),
    .m_axi_gmem2_0_WID(WriteBack_U0_m_axi_gmem2_0_WID),
    .m_axi_gmem2_0_WUSER(WriteBack_U0_m_axi_gmem2_0_WUSER),
    .m_axi_gmem2_0_ARVALID(WriteBack_U0_m_axi_gmem2_0_ARVALID),
    .m_axi_gmem2_0_ARREADY(1'b0),
    .m_axi_gmem2_0_ARADDR(WriteBack_U0_m_axi_gmem2_0_ARADDR),
    .m_axi_gmem2_0_ARID(WriteBack_U0_m_axi_gmem2_0_ARID),
    .m_axi_gmem2_0_ARLEN(WriteBack_U0_m_axi_gmem2_0_ARLEN),
    .m_axi_gmem2_0_ARSIZE(WriteBack_U0_m_axi_gmem2_0_ARSIZE),
    .m_axi_gmem2_0_ARBURST(WriteBack_U0_m_axi_gmem2_0_ARBURST),
    .m_axi_gmem2_0_ARLOCK(WriteBack_U0_m_axi_gmem2_0_ARLOCK),
    .m_axi_gmem2_0_ARCACHE(WriteBack_U0_m_axi_gmem2_0_ARCACHE),
    .m_axi_gmem2_0_ARPROT(WriteBack_U0_m_axi_gmem2_0_ARPROT),
    .m_axi_gmem2_0_ARQOS(WriteBack_U0_m_axi_gmem2_0_ARQOS),
    .m_axi_gmem2_0_ARREGION(WriteBack_U0_m_axi_gmem2_0_ARREGION),
    .m_axi_gmem2_0_ARUSER(WriteBack_U0_m_axi_gmem2_0_ARUSER),
    .m_axi_gmem2_0_RVALID(1'b0),
    .m_axi_gmem2_0_RREADY(WriteBack_U0_m_axi_gmem2_0_RREADY),
    .m_axi_gmem2_0_RDATA(256'd0),
    .m_axi_gmem2_0_RLAST(1'b0),
    .m_axi_gmem2_0_RID(1'd0),
    .m_axi_gmem2_0_RFIFONUM(9'd0),
    .m_axi_gmem2_0_RUSER(1'd0),
    .m_axi_gmem2_0_RRESP(2'd0),
    .m_axi_gmem2_0_BVALID(gmem2_0_BVALID),
    .m_axi_gmem2_0_BREADY(WriteBack_U0_m_axi_gmem2_0_BREADY),
    .m_axi_gmem2_0_BRESP(gmem2_0_BRESP),
    .m_axi_gmem2_0_BID(gmem2_0_BID),
    .m_axi_gmem2_0_BUSER(gmem2_0_BUSER),
    .m_axi_gmem3_0_AWVALID(WriteBack_U0_m_axi_gmem3_0_AWVALID),
    .m_axi_gmem3_0_AWREADY(gmem3_0_AWREADY),
    .m_axi_gmem3_0_AWADDR(WriteBack_U0_m_axi_gmem3_0_AWADDR),
    .m_axi_gmem3_0_AWID(WriteBack_U0_m_axi_gmem3_0_AWID),
    .m_axi_gmem3_0_AWLEN(WriteBack_U0_m_axi_gmem3_0_AWLEN),
    .m_axi_gmem3_0_AWSIZE(WriteBack_U0_m_axi_gmem3_0_AWSIZE),
    .m_axi_gmem3_0_AWBURST(WriteBack_U0_m_axi_gmem3_0_AWBURST),
    .m_axi_gmem3_0_AWLOCK(WriteBack_U0_m_axi_gmem3_0_AWLOCK),
    .m_axi_gmem3_0_AWCACHE(WriteBack_U0_m_axi_gmem3_0_AWCACHE),
    .m_axi_gmem3_0_AWPROT(WriteBack_U0_m_axi_gmem3_0_AWPROT),
    .m_axi_gmem3_0_AWQOS(WriteBack_U0_m_axi_gmem3_0_AWQOS),
    .m_axi_gmem3_0_AWREGION(WriteBack_U0_m_axi_gmem3_0_AWREGION),
    .m_axi_gmem3_0_AWUSER(WriteBack_U0_m_axi_gmem3_0_AWUSER),
    .m_axi_gmem3_0_WVALID(WriteBack_U0_m_axi_gmem3_0_WVALID),
    .m_axi_gmem3_0_WREADY(gmem3_0_WREADY),
    .m_axi_gmem3_0_WDATA(WriteBack_U0_m_axi_gmem3_0_WDATA),
    .m_axi_gmem3_0_WSTRB(WriteBack_U0_m_axi_gmem3_0_WSTRB),
    .m_axi_gmem3_0_WLAST(WriteBack_U0_m_axi_gmem3_0_WLAST),
    .m_axi_gmem3_0_WID(WriteBack_U0_m_axi_gmem3_0_WID),
    .m_axi_gmem3_0_WUSER(WriteBack_U0_m_axi_gmem3_0_WUSER),
    .m_axi_gmem3_0_ARVALID(WriteBack_U0_m_axi_gmem3_0_ARVALID),
    .m_axi_gmem3_0_ARREADY(1'b0),
    .m_axi_gmem3_0_ARADDR(WriteBack_U0_m_axi_gmem3_0_ARADDR),
    .m_axi_gmem3_0_ARID(WriteBack_U0_m_axi_gmem3_0_ARID),
    .m_axi_gmem3_0_ARLEN(WriteBack_U0_m_axi_gmem3_0_ARLEN),
    .m_axi_gmem3_0_ARSIZE(WriteBack_U0_m_axi_gmem3_0_ARSIZE),
    .m_axi_gmem3_0_ARBURST(WriteBack_U0_m_axi_gmem3_0_ARBURST),
    .m_axi_gmem3_0_ARLOCK(WriteBack_U0_m_axi_gmem3_0_ARLOCK),
    .m_axi_gmem3_0_ARCACHE(WriteBack_U0_m_axi_gmem3_0_ARCACHE),
    .m_axi_gmem3_0_ARPROT(WriteBack_U0_m_axi_gmem3_0_ARPROT),
    .m_axi_gmem3_0_ARQOS(WriteBack_U0_m_axi_gmem3_0_ARQOS),
    .m_axi_gmem3_0_ARREGION(WriteBack_U0_m_axi_gmem3_0_ARREGION),
    .m_axi_gmem3_0_ARUSER(WriteBack_U0_m_axi_gmem3_0_ARUSER),
    .m_axi_gmem3_0_RVALID(1'b0),
    .m_axi_gmem3_0_RREADY(WriteBack_U0_m_axi_gmem3_0_RREADY),
    .m_axi_gmem3_0_RDATA(256'd0),
    .m_axi_gmem3_0_RLAST(1'b0),
    .m_axi_gmem3_0_RID(1'd0),
    .m_axi_gmem3_0_RFIFONUM(9'd0),
    .m_axi_gmem3_0_RUSER(1'd0),
    .m_axi_gmem3_0_RRESP(2'd0),
    .m_axi_gmem3_0_BVALID(gmem3_0_BVALID),
    .m_axi_gmem3_0_BREADY(WriteBack_U0_m_axi_gmem3_0_BREADY),
    .m_axi_gmem3_0_BRESP(gmem3_0_BRESP),
    .m_axi_gmem3_0_BID(gmem3_0_BID),
    .m_axi_gmem3_0_BUSER(gmem3_0_BUSER),
    .point_result_stream_dout(point_result_stream_dout),
    .point_result_stream_empty_n(point_result_stream_empty_n),
    .point_result_stream_read(WriteBack_U0_point_result_stream_read),
    .point_result_stream_num_data_valid(point_result_stream_num_data_valid),
    .point_result_stream_fifo_cap(point_result_stream_fifo_cap)
);

msm_fifo_w64_d4_S result_x_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(entry_proc_U0_result_x_c_din),
    .if_full_n(result_x_c_full_n),
    .if_write(entry_proc_U0_result_x_c_write),
    .if_dout(result_x_c_dout),
    .if_empty_n(result_x_c_empty_n),
    .if_read(WriteBack_U0_result_x_read),
    .if_num_data_valid(result_x_c_num_data_valid),
    .if_fifo_cap(result_x_c_fifo_cap)
);

msm_fifo_w64_d4_S result_y_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(entry_proc_U0_result_y_c_din),
    .if_full_n(result_y_c_full_n),
    .if_write(entry_proc_U0_result_y_c_write),
    .if_dout(result_y_c_dout),
    .if_empty_n(result_y_c_empty_n),
    .if_read(WriteBack_U0_result_y_read),
    .if_num_data_valid(result_y_c_num_data_valid),
    .if_fifo_cap(result_y_c_fifo_cap)
);

msm_fifo_w64_d4_S result_z_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(entry_proc_U0_result_z_c_din),
    .if_full_n(result_z_c_full_n),
    .if_write(entry_proc_U0_result_z_c_write),
    .if_dout(result_z_c_dout),
    .if_empty_n(result_z_c_empty_n),
    .if_read(WriteBack_U0_result_z_read),
    .if_num_data_valid(result_z_c_num_data_valid),
    .if_fifo_cap(result_z_c_fifo_cap)
);

msm_fifo_w64_d4_S result_t_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(entry_proc_U0_result_t_c_din),
    .if_full_n(result_t_c_full_n),
    .if_write(entry_proc_U0_result_t_c_write),
    .if_dout(result_t_c_dout),
    .if_empty_n(result_t_c_empty_n),
    .if_read(WriteBack_U0_result_t_read),
    .if_num_data_valid(result_t_c_num_data_valid),
    .if_fifo_cap(result_t_c_fifo_cap)
);

msm_fifo_w256_d64_A x_point_stream_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(data_loader_U0_x_point_stream_din),
    .if_full_n(x_point_stream_full_n),
    .if_write(data_loader_U0_x_point_stream_write),
    .if_dout(x_point_stream_dout),
    .if_empty_n(x_point_stream_empty_n),
    .if_read(pippenger_control_U0_x_point_stream_read),
    .if_num_data_valid(x_point_stream_num_data_valid),
    .if_fifo_cap(x_point_stream_fifo_cap)
);

msm_fifo_w256_d64_A y_point_stream_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(data_loader_U0_y_point_stream_din),
    .if_full_n(y_point_stream_full_n),
    .if_write(data_loader_U0_y_point_stream_write),
    .if_dout(y_point_stream_dout),
    .if_empty_n(y_point_stream_empty_n),
    .if_read(pippenger_control_U0_y_point_stream_read),
    .if_num_data_valid(y_point_stream_num_data_valid),
    .if_fifo_cap(y_point_stream_fifo_cap)
);

msm_fifo_w256_d64_A z_point_stream_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(data_loader_U0_z_point_stream_din),
    .if_full_n(z_point_stream_full_n),
    .if_write(data_loader_U0_z_point_stream_write),
    .if_dout(z_point_stream_dout),
    .if_empty_n(z_point_stream_empty_n),
    .if_read(pippenger_control_U0_z_point_stream_read),
    .if_num_data_valid(z_point_stream_num_data_valid),
    .if_fifo_cap(z_point_stream_fifo_cap)
);

msm_fifo_w256_d2_S t_point_stream_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(data_loader_U0_t_point_stream_din),
    .if_full_n(t_point_stream_full_n),
    .if_write(data_loader_U0_t_point_stream_write),
    .if_dout(t_point_stream_dout),
    .if_empty_n(t_point_stream_empty_n),
    .if_read(pippenger_control_U0_t_point_stream_read),
    .if_num_data_valid(t_point_stream_num_data_valid),
    .if_fifo_cap(t_point_stream_fifo_cap)
);

msm_fifo_w256_d64_A scalar_point_stream_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(data_loader_U0_scalar_point_stream_din),
    .if_full_n(scalar_point_stream_full_n),
    .if_write(data_loader_U0_scalar_point_stream_write),
    .if_dout(scalar_point_stream_dout),
    .if_empty_n(scalar_point_stream_empty_n),
    .if_read(pippenger_control_U0_scalar_point_stream_read),
    .if_num_data_valid(scalar_point_stream_num_data_valid),
    .if_fifo_cap(scalar_point_stream_fifo_cap)
);

msm_fifo_w1024_d64_A point_result_stream_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(pippenger_control_U0_point_result_stream_din),
    .if_full_n(point_result_stream_full_n),
    .if_write(pippenger_control_U0_point_result_stream_write),
    .if_dout(point_result_stream_dout),
    .if_empty_n(point_result_stream_empty_n),
    .if_read(WriteBack_U0_point_result_stream_read),
    .if_num_data_valid(point_result_stream_num_data_valid),
    .if_fifo_cap(point_result_stream_fifo_cap)
);

msm_start_for_WriteBack_U0 start_for_WriteBack_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_WriteBack_U0_din),
    .if_full_n(start_for_WriteBack_U0_full_n),
    .if_write(entry_proc_U0_start_write),
    .if_dout(start_for_WriteBack_U0_dout),
    .if_empty_n(start_for_WriteBack_U0_empty_n),
    .if_read(WriteBack_U0_ap_ready)
);

msm_start_for_pippenger_control_U0 start_for_pippenger_control_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_pippenger_control_U0_din),
    .if_full_n(start_for_pippenger_control_U0_full_n),
    .if_write(data_loader_U0_start_write),
    .if_dout(start_for_pippenger_control_U0_dout),
    .if_empty_n(start_for_pippenger_control_U0_empty_n),
    .if_read(pippenger_control_U0_ap_ready)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_data_loader_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_data_loader_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_data_loader_U0_ap_ready <= ap_sync_data_loader_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_entry_proc_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_entry_proc_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_entry_proc_U0_ap_ready <= ap_sync_entry_proc_U0_ap_ready;
        end
    end
end

assign WriteBack_U0_ap_continue = 1'b1;

assign WriteBack_U0_ap_start = start_for_WriteBack_U0_empty_n;

assign ap_done = WriteBack_U0_ap_done;

assign ap_idle = (pippenger_control_U0_ap_idle & entry_proc_U0_ap_idle & data_loader_U0_ap_idle & WriteBack_U0_ap_idle);

assign ap_ready = ap_sync_ready;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign ap_sync_data_loader_U0_ap_ready = (data_loader_U0_ap_ready | ap_sync_reg_data_loader_U0_ap_ready);

assign ap_sync_entry_proc_U0_ap_ready = (entry_proc_U0_ap_ready | ap_sync_reg_entry_proc_U0_ap_ready);

assign ap_sync_ready = (ap_sync_entry_proc_U0_ap_ready & ap_sync_data_loader_U0_ap_ready);

assign data_loader_U0_ap_continue = 1'b1;

assign data_loader_U0_ap_start = ((ap_sync_reg_data_loader_U0_ap_ready ^ 1'b1) & ap_start);

assign entry_proc_U0_ap_continue = 1'b1;

assign entry_proc_U0_ap_start = ((ap_sync_reg_entry_proc_U0_ap_ready ^ 1'b1) & ap_start);

assign gmem0_0_BID = 1'd0;

assign gmem0_0_BRESP = 2'd0;

assign gmem0_0_BUSER = 1'd0;

assign gmem0_0_RID = 1'd0;

assign gmem0_0_RLAST = 1'b0;

assign gmem0_0_RRESP = 2'd0;

assign gmem0_0_RUSER = 1'd0;

assign gmem1_0_BID = 1'd0;

assign gmem1_0_BRESP = 2'd0;

assign gmem1_0_BUSER = 1'd0;

assign gmem1_0_RID = 1'd0;

assign gmem1_0_RLAST = 1'b0;

assign gmem1_0_RRESP = 2'd0;

assign gmem1_0_RUSER = 1'd0;

assign gmem2_0_BID = 1'd0;

assign gmem2_0_BRESP = 2'd0;

assign gmem2_0_BUSER = 1'd0;

assign gmem2_0_RID = 1'd0;

assign gmem2_0_RLAST = 1'b0;

assign gmem2_0_RRESP = 2'd0;

assign gmem2_0_RUSER = 1'd0;

assign gmem3_0_BID = 1'd0;

assign gmem3_0_BRESP = 2'd0;

assign gmem3_0_BUSER = 1'd0;

assign gmem3_0_RID = 1'd0;

assign gmem3_0_RLAST = 1'b0;

assign gmem3_0_RRESP = 2'd0;

assign gmem3_0_RUSER = 1'd0;

assign pippenger_control_U0_ap_continue = 1'b1;

assign pippenger_control_U0_ap_start = start_for_pippenger_control_U0_empty_n;

assign start_for_WriteBack_U0_din = 1'b1;

assign start_for_pippenger_control_U0_din = 1'b1;

endmodule //msm
